* This file was automatically generated by Zimpl
* param Q2 := 1;
* param M := 1000;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nN := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set N := { 1 .. nN };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[N] := read file1 as "<1n> 2n" skip 1 use nN;
* param backCost[N] := read file1 as "<1n> 2n" skip nN+1 use nN;
* param demand[C*N*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nN+1;
* param q[P*N] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*N] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in N with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <j> in P with q[j,i] > 0 };
* var B[C*N*T0] >= 0;
* var I[C*N*T0] >= 0;
* var f[C*N*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var p[P] binary;
* minimize cost: sum <i> in N: ( sum <t> in T: (sum <c> in C : (inveCost[i] * I[c,i,t]  + backCost[i] * B[c,i,t]) ));
* subto select:       sum <j> in P: p[j] <= m;
* subto balance:    forall <c,i,t> in C*N*T with t>=1 do       I[c,i,t-1] - B[c,i,t-1] + Q1*Q2*f[c,i,t] + Q2 * (sum <j> in Pc[c
* ]: q[j,i] * y[c,j,t]) == demand[c,i,t] + I[c,i,t] - B[c,i,t];
* subto valid:    forall <c,i> in C*N do       sum <t> in T: ( min(Q1, D[c,i]) * f[c,i,t] + sum <j> in Pc[c]: ( min(q[j,i], D[c
* ,i] ) * y[c,j,t]) ) >= D[c,i];
* subto BigM:    forall <c,j,t> in C*P*T with t>=1 do       y[c,j,t] <= M*p[j];
* subto init1:    forall <c,i> in C*N do       I[c,i,0] == 0;
* subto init2:    forall <c,i> in C*N do       B[c,i,0] == 0;
* subto init3:    forall <c,i> in C*N do       B[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 L  BigM_101          
 L  BigM_102          
 L  BigM_103          
 L  BigM_104          
 L  BigM_105          
 L  BigM_106          
 L  BigM_107          
 L  BigM_108          
 L  BigM_109          
 L  BigM_110          
 L  BigM_111          
 L  BigM_112          
 L  BigM_113          
 L  BigM_114          
 L  BigM_115          
 L  BigM_116          
 L  BigM_117          
 L  BigM_118          
 L  BigM_119          
 L  BigM_120          
 L  BigM_121          
 L  BigM_122          
 L  BigM_123          
 L  BigM_124          
 L  BigM_125          
 L  BigM_126          
 L  BigM_127          
 L  BigM_128          
 L  BigM_129          
 L  BigM_130          
 L  BigM_131          
 L  BigM_132          
 L  BigM_133          
 L  BigM_134          
 L  BigM_135          
 L  BigM_136          
 L  BigM_137          
 L  BigM_138          
 L  BigM_139          
 L  BigM_140          
 L  BigM_141          
 L  BigM_142          
 L  BigM_143          
 L  BigM_144          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    f#1#1#1   valid_1             72
    f#1#1#1   balanc@1            72
    f#1#1#2   valid_1             72
    f#1#1#2   balanc@2            72
    f#1#1#3   valid_1             72
    f#1#1#3   balanc@3            72
    f#1#1#4   valid_1             72
    f#1#1#4   balanc@4            72
    f#1#1#5   valid_1             72
    f#1#1#5   balanc@5            72
    f#1#1#6   valid_1             72
    f#1#1#6   balanc@6            72
    f#1#2#1   balanc@7            72
    f#1#2#2   balanc@8            72
    f#1#2#3   balanc@9            72
    f#1#2#4   balanc@a            72
    f#1#2#5   balanc@b            72
    f#1#2#6   balanc@c            72
    f#2#1#1   valid_2             72
    f#2#1#1   balanc@d            72
    f#2#1#2   valid_2             72
    f#2#1#2   balanc@e            72
    f#2#1#3   valid_2             72
    f#2#1#3   balanc@f            72
    f#2#1#4   valid_2             72
    f#2#1#4   balan@10            72
    f#2#1#5   valid_2             72
    f#2#1#5   balan@11            72
    f#2#1#6   valid_2             72
    f#2#1#6   balan@12            72
    f#2#2#1   valid_3             72
    f#2#2#1   balan@13            72
    f#2#2#2   valid_3             72
    f#2#2#2   balan@14            72
    f#2#2#3   valid_3             72
    f#2#2#3   balan@15            72
    f#2#2#4   valid_3             72
    f#2#2#4   balan@16            72
    f#2#2#5   valid_3             72
    f#2#2#5   balan@17            72
    f#2#2#6   valid_3             72
    f#2#2#6   balan@18            72
    f#3#1#1   valid_4             72
    f#3#1#1   balan@19            72
    f#3#1#2   valid_4             72
    f#3#1#2   balan@1a            72
    f#3#1#3   valid_4             72
    f#3#1#3   balan@1b            72
    f#3#1#4   valid_4             72
    f#3#1#4   balan@1c            72
    f#3#1#5   valid_4             72
    f#3#1#5   balan@1d            72
    f#3#1#6   valid_4             72
    f#3#1#6   balan@1e            72
    f#3#2#1   valid_5             72
    f#3#2#1   balan@1f            72
    f#3#2#2   valid_5             72
    f#3#2#2   balan@20            72
    f#3#2#3   valid_5             72
    f#3#2#3   balan@21            72
    f#3#2#4   valid_5             72
    f#3#2#4   balan@22            72
    f#3#2#5   valid_5             72
    f#3#2#5   balan@23            72
    f#3#2#6   valid_5             72
    f#3#2#6   balan@24            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_1             49
    y#1#1#1   balanc@7            23
    y#1#1#1   balanc@1            49
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_1             49
    y#1#1#2   balanc@8            23
    y#1#1#2   balanc@2            49
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_1             49
    y#1#1#3   balanc@9            23
    y#1#1#3   balanc@3            49
    y#1#1#4   BigM_4               1
    y#1#1#4   valid_1             49
    y#1#1#4   balanc@a            23
    y#1#1#4   balanc@4            49
    y#1#1#5   BigM_5               1
    y#1#1#5   valid_1             49
    y#1#1#5   balanc@b            23
    y#1#1#5   balanc@5            49
    y#1#1#6   BigM_6               1
    y#1#1#6   valid_1             49
    y#1#1#6   balanc@c            23
    y#1#1#6   balanc@6            49
    y#1#2#1   BigM_7               1
    y#1#2#1   valid_1             26
    y#1#2#1   balanc@7            46
    y#1#2#1   balanc@1            26
    y#1#2#2   BigM_8               1
    y#1#2#2   valid_1             26
    y#1#2#2   balanc@8            46
    y#1#2#2   balanc@2            26
    y#1#2#3   BigM_9               1
    y#1#2#3   valid_1             26
    y#1#2#3   balanc@9            46
    y#1#2#3   balanc@3            26
    y#1#2#4   BigM_10              1
    y#1#2#4   valid_1             26
    y#1#2#4   balanc@a            46
    y#1#2#4   balanc@4            26
    y#1#2#5   BigM_11              1
    y#1#2#5   valid_1             26
    y#1#2#5   balanc@b            46
    y#1#2#5   balanc@5            26
    y#1#2#6   BigM_12              1
    y#1#2#6   valid_1             26
    y#1#2#6   balanc@c            46
    y#1#2#6   balanc@6            26
    y#1#3#1   BigM_13              1
    y#1#3#1   valid_1              9
    y#1#3#1   balanc@7            63
    y#1#3#1   balanc@1             9
    y#1#3#2   BigM_14              1
    y#1#3#2   valid_1              9
    y#1#3#2   balanc@8            63
    y#1#3#2   balanc@2             9
    y#1#3#3   BigM_15              1
    y#1#3#3   valid_1              9
    y#1#3#3   balanc@9            63
    y#1#3#3   balanc@3             9
    y#1#3#4   BigM_16              1
    y#1#3#4   valid_1              9
    y#1#3#4   balanc@a            63
    y#1#3#4   balanc@4             9
    y#1#3#5   BigM_17              1
    y#1#3#5   valid_1              9
    y#1#3#5   balanc@b            63
    y#1#3#5   balanc@5             9
    y#1#3#6   BigM_18              1
    y#1#3#6   valid_1              9
    y#1#3#6   balanc@c            63
    y#1#3#6   balanc@6             9
    y#1#4#1   BigM_19              1
    y#1#4#1   valid_1             40
    y#1#4#1   balanc@7            32
    y#1#4#1   balanc@1            40
    y#1#4#2   BigM_20              1
    y#1#4#2   valid_1             40
    y#1#4#2   balanc@8            32
    y#1#4#2   balanc@2            40
    y#1#4#3   BigM_21              1
    y#1#4#3   valid_1             40
    y#1#4#3   balanc@9            32
    y#1#4#3   balanc@3            40
    y#1#4#4   BigM_22              1
    y#1#4#4   valid_1             40
    y#1#4#4   balanc@a            32
    y#1#4#4   balanc@4            40
    y#1#4#5   BigM_23              1
    y#1#4#5   valid_1             40
    y#1#4#5   balanc@b            32
    y#1#4#5   balanc@5            40
    y#1#4#6   BigM_24              1
    y#1#4#6   valid_1             40
    y#1#4#6   balanc@c            32
    y#1#4#6   balanc@6            40
    y#1#5#1   BigM_25              1
    y#1#5#1   valid_1             38
    y#1#5#1   balanc@7            34
    y#1#5#1   balanc@1            38
    y#1#5#2   BigM_26              1
    y#1#5#2   valid_1             38
    y#1#5#2   balanc@8            34
    y#1#5#2   balanc@2            38
    y#1#5#3   BigM_27              1
    y#1#5#3   valid_1             38
    y#1#5#3   balanc@9            34
    y#1#5#3   balanc@3            38
    y#1#5#4   BigM_28              1
    y#1#5#4   valid_1             38
    y#1#5#4   balanc@a            34
    y#1#5#4   balanc@4            38
    y#1#5#5   BigM_29              1
    y#1#5#5   valid_1             38
    y#1#5#5   balanc@b            34
    y#1#5#5   balanc@5            38
    y#1#5#6   BigM_30              1
    y#1#5#6   valid_1             38
    y#1#5#6   balanc@c            34
    y#1#5#6   balanc@6            38
    y#1#6#1   BigM_31              1
    y#1#6#1   valid_1             46
    y#1#6#1   balanc@7            26
    y#1#6#1   balanc@1            46
    y#1#6#2   BigM_32              1
    y#1#6#2   valid_1             46
    y#1#6#2   balanc@8            26
    y#1#6#2   balanc@2            46
    y#1#6#3   BigM_33              1
    y#1#6#3   valid_1             46
    y#1#6#3   balanc@9            26
    y#1#6#3   balanc@3            46
    y#1#6#4   BigM_34              1
    y#1#6#4   valid_1             46
    y#1#6#4   balanc@a            26
    y#1#6#4   balanc@4            46
    y#1#6#5   BigM_35              1
    y#1#6#5   valid_1             46
    y#1#6#5   balanc@b            26
    y#1#6#5   balanc@5            46
    y#1#6#6   BigM_36              1
    y#1#6#6   valid_1             46
    y#1#6#6   balanc@c            26
    y#1#6#6   balanc@6            46
    y#1#7#1   BigM_37              1
    y#1#7#1   valid_1              7
    y#1#7#1   balanc@7            65
    y#1#7#1   balanc@1             7
    y#1#7#2   BigM_38              1
    y#1#7#2   valid_1              7
    y#1#7#2   balanc@8            65
    y#1#7#2   balanc@2             7
    y#1#7#3   BigM_39              1
    y#1#7#3   valid_1              7
    y#1#7#3   balanc@9            65
    y#1#7#3   balanc@3             7
    y#1#7#4   BigM_40              1
    y#1#7#4   valid_1              7
    y#1#7#4   balanc@a            65
    y#1#7#4   balanc@4             7
    y#1#7#5   BigM_41              1
    y#1#7#5   valid_1              7
    y#1#7#5   balanc@b            65
    y#1#7#5   balanc@5             7
    y#1#7#6   BigM_42              1
    y#1#7#6   valid_1              7
    y#1#7#6   balanc@c            65
    y#1#7#6   balanc@6             7
    y#1#8#1   BigM_43              1
    y#1#8#1   valid_1             25
    y#1#8#1   balanc@7            47
    y#1#8#1   balanc@1            25
    y#1#8#2   BigM_44              1
    y#1#8#2   valid_1             25
    y#1#8#2   balanc@8            47
    y#1#8#2   balanc@2            25
    y#1#8#3   BigM_45              1
    y#1#8#3   valid_1             25
    y#1#8#3   balanc@9            47
    y#1#8#3   balanc@3            25
    y#1#8#4   BigM_46              1
    y#1#8#4   valid_1             25
    y#1#8#4   balanc@a            47
    y#1#8#4   balanc@4            25
    y#1#8#5   BigM_47              1
    y#1#8#5   valid_1             25
    y#1#8#5   balanc@b            47
    y#1#8#5   balanc@5            25
    y#1#8#6   BigM_48              1
    y#1#8#6   valid_1             25
    y#1#8#6   balanc@c            47
    y#1#8#6   balanc@6            25
    y#2#1#1   BigM_49              1
    y#2#1#1   valid_3             23
    y#2#1#1   valid_2             49
    y#2#1#1   balan@13            23
    y#2#1#1   balanc@d            49
    y#2#1#2   BigM_50              1
    y#2#1#2   valid_3             23
    y#2#1#2   valid_2             49
    y#2#1#2   balan@14            23
    y#2#1#2   balanc@e            49
    y#2#1#3   BigM_51              1
    y#2#1#3   valid_3             23
    y#2#1#3   valid_2             49
    y#2#1#3   balan@15            23
    y#2#1#3   balanc@f            49
    y#2#1#4   BigM_52              1
    y#2#1#4   valid_3             23
    y#2#1#4   valid_2             49
    y#2#1#4   balan@16            23
    y#2#1#4   balan@10            49
    y#2#1#5   BigM_53              1
    y#2#1#5   valid_3             23
    y#2#1#5   valid_2             49
    y#2#1#5   balan@17            23
    y#2#1#5   balan@11            49
    y#2#1#6   BigM_54              1
    y#2#1#6   valid_3             23
    y#2#1#6   valid_2             49
    y#2#1#6   balan@18            23
    y#2#1#6   balan@12            49
    y#2#2#1   BigM_55              1
    y#2#2#1   valid_3             46
    y#2#2#1   valid_2             26
    y#2#2#1   balan@13            46
    y#2#2#1   balanc@d            26
    y#2#2#2   BigM_56              1
    y#2#2#2   valid_3             46
    y#2#2#2   valid_2             26
    y#2#2#2   balan@14            46
    y#2#2#2   balanc@e            26
    y#2#2#3   BigM_57              1
    y#2#2#3   valid_3             46
    y#2#2#3   valid_2             26
    y#2#2#3   balan@15            46
    y#2#2#3   balanc@f            26
    y#2#2#4   BigM_58              1
    y#2#2#4   valid_3             46
    y#2#2#4   valid_2             26
    y#2#2#4   balan@16            46
    y#2#2#4   balan@10            26
    y#2#2#5   BigM_59              1
    y#2#2#5   valid_3             46
    y#2#2#5   valid_2             26
    y#2#2#5   balan@17            46
    y#2#2#5   balan@11            26
    y#2#2#6   BigM_60              1
    y#2#2#6   valid_3             46
    y#2#2#6   valid_2             26
    y#2#2#6   balan@18            46
    y#2#2#6   balan@12            26
    y#2#3#1   BigM_61              1
    y#2#3#1   valid_3             63
    y#2#3#1   valid_2              9
    y#2#3#1   balan@13            63
    y#2#3#1   balanc@d             9
    y#2#3#2   BigM_62              1
    y#2#3#2   valid_3             63
    y#2#3#2   valid_2              9
    y#2#3#2   balan@14            63
    y#2#3#2   balanc@e             9
    y#2#3#3   BigM_63              1
    y#2#3#3   valid_3             63
    y#2#3#3   valid_2              9
    y#2#3#3   balan@15            63
    y#2#3#3   balanc@f             9
    y#2#3#4   BigM_64              1
    y#2#3#4   valid_3             63
    y#2#3#4   valid_2              9
    y#2#3#4   balan@16            63
    y#2#3#4   balan@10             9
    y#2#3#5   BigM_65              1
    y#2#3#5   valid_3             63
    y#2#3#5   valid_2              9
    y#2#3#5   balan@17            63
    y#2#3#5   balan@11             9
    y#2#3#6   BigM_66              1
    y#2#3#6   valid_3             63
    y#2#3#6   valid_2              9
    y#2#3#6   balan@18            63
    y#2#3#6   balan@12             9
    y#2#4#1   BigM_67              1
    y#2#4#1   valid_3             32
    y#2#4#1   valid_2             40
    y#2#4#1   balan@13            32
    y#2#4#1   balanc@d            40
    y#2#4#2   BigM_68              1
    y#2#4#2   valid_3             32
    y#2#4#2   valid_2             40
    y#2#4#2   balan@14            32
    y#2#4#2   balanc@e            40
    y#2#4#3   BigM_69              1
    y#2#4#3   valid_3             32
    y#2#4#3   valid_2             40
    y#2#4#3   balan@15            32
    y#2#4#3   balanc@f            40
    y#2#4#4   BigM_70              1
    y#2#4#4   valid_3             32
    y#2#4#4   valid_2             40
    y#2#4#4   balan@16            32
    y#2#4#4   balan@10            40
    y#2#4#5   BigM_71              1
    y#2#4#5   valid_3             32
    y#2#4#5   valid_2             40
    y#2#4#5   balan@17            32
    y#2#4#5   balan@11            40
    y#2#4#6   BigM_72              1
    y#2#4#6   valid_3             32
    y#2#4#6   valid_2             40
    y#2#4#6   balan@18            32
    y#2#4#6   balan@12            40
    y#2#5#1   BigM_73              1
    y#2#5#1   valid_3             34
    y#2#5#1   valid_2             38
    y#2#5#1   balan@13            34
    y#2#5#1   balanc@d            38
    y#2#5#2   BigM_74              1
    y#2#5#2   valid_3             34
    y#2#5#2   valid_2             38
    y#2#5#2   balan@14            34
    y#2#5#2   balanc@e            38
    y#2#5#3   BigM_75              1
    y#2#5#3   valid_3             34
    y#2#5#3   valid_2             38
    y#2#5#3   balan@15            34
    y#2#5#3   balanc@f            38
    y#2#5#4   BigM_76              1
    y#2#5#4   valid_3             34
    y#2#5#4   valid_2             38
    y#2#5#4   balan@16            34
    y#2#5#4   balan@10            38
    y#2#5#5   BigM_77              1
    y#2#5#5   valid_3             34
    y#2#5#5   valid_2             38
    y#2#5#5   balan@17            34
    y#2#5#5   balan@11            38
    y#2#5#6   BigM_78              1
    y#2#5#6   valid_3             34
    y#2#5#6   valid_2             38
    y#2#5#6   balan@18            34
    y#2#5#6   balan@12            38
    y#2#6#1   BigM_79              1
    y#2#6#1   valid_3             26
    y#2#6#1   valid_2             46
    y#2#6#1   balan@13            26
    y#2#6#1   balanc@d            46
    y#2#6#2   BigM_80              1
    y#2#6#2   valid_3             26
    y#2#6#2   valid_2             46
    y#2#6#2   balan@14            26
    y#2#6#2   balanc@e            46
    y#2#6#3   BigM_81              1
    y#2#6#3   valid_3             26
    y#2#6#3   valid_2             46
    y#2#6#3   balan@15            26
    y#2#6#3   balanc@f            46
    y#2#6#4   BigM_82              1
    y#2#6#4   valid_3             26
    y#2#6#4   valid_2             46
    y#2#6#4   balan@16            26
    y#2#6#4   balan@10            46
    y#2#6#5   BigM_83              1
    y#2#6#5   valid_3             26
    y#2#6#5   valid_2             46
    y#2#6#5   balan@17            26
    y#2#6#5   balan@11            46
    y#2#6#6   BigM_84              1
    y#2#6#6   valid_3             26
    y#2#6#6   valid_2             46
    y#2#6#6   balan@18            26
    y#2#6#6   balan@12            46
    y#2#7#1   BigM_85              1
    y#2#7#1   valid_3             65
    y#2#7#1   valid_2              7
    y#2#7#1   balan@13            65
    y#2#7#1   balanc@d             7
    y#2#7#2   BigM_86              1
    y#2#7#2   valid_3             65
    y#2#7#2   valid_2              7
    y#2#7#2   balan@14            65
    y#2#7#2   balanc@e             7
    y#2#7#3   BigM_87              1
    y#2#7#3   valid_3             65
    y#2#7#3   valid_2              7
    y#2#7#3   balan@15            65
    y#2#7#3   balanc@f             7
    y#2#7#4   BigM_88              1
    y#2#7#4   valid_3             65
    y#2#7#4   valid_2              7
    y#2#7#4   balan@16            65
    y#2#7#4   balan@10             7
    y#2#7#5   BigM_89              1
    y#2#7#5   valid_3             65
    y#2#7#5   valid_2              7
    y#2#7#5   balan@17            65
    y#2#7#5   balan@11             7
    y#2#7#6   BigM_90              1
    y#2#7#6   valid_3             65
    y#2#7#6   valid_2              7
    y#2#7#6   balan@18            65
    y#2#7#6   balan@12             7
    y#2#8#1   BigM_91              1
    y#2#8#1   valid_3             47
    y#2#8#1   valid_2             25
    y#2#8#1   balan@13            47
    y#2#8#1   balanc@d            25
    y#2#8#2   BigM_92              1
    y#2#8#2   valid_3             47
    y#2#8#2   valid_2             25
    y#2#8#2   balan@14            47
    y#2#8#2   balanc@e            25
    y#2#8#3   BigM_93              1
    y#2#8#3   valid_3             47
    y#2#8#3   valid_2             25
    y#2#8#3   balan@15            47
    y#2#8#3   balanc@f            25
    y#2#8#4   BigM_94              1
    y#2#8#4   valid_3             47
    y#2#8#4   valid_2             25
    y#2#8#4   balan@16            47
    y#2#8#4   balan@10            25
    y#2#8#5   BigM_95              1
    y#2#8#5   valid_3             47
    y#2#8#5   valid_2             25
    y#2#8#5   balan@17            47
    y#2#8#5   balan@11            25
    y#2#8#6   BigM_96              1
    y#2#8#6   valid_3             47
    y#2#8#6   valid_2             25
    y#2#8#6   balan@18            47
    y#2#8#6   balan@12            25
    y#3#1#1   BigM_97              1
    y#3#1#1   valid_5             23
    y#3#1#1   valid_4             49
    y#3#1#1   balan@1f            23
    y#3#1#1   balan@19            49
    y#3#1#2   BigM_98              1
    y#3#1#2   valid_5             23
    y#3#1#2   valid_4             49
    y#3#1#2   balan@20            23
    y#3#1#2   balan@1a            49
    y#3#1#3   BigM_99              1
    y#3#1#3   valid_5             23
    y#3#1#3   valid_4             49
    y#3#1#3   balan@21            23
    y#3#1#3   balan@1b            49
    y#3#1#4   BigM_100             1
    y#3#1#4   valid_5             23
    y#3#1#4   valid_4             49
    y#3#1#4   balan@22            23
    y#3#1#4   balan@1c            49
    y#3#1#5   BigM_101             1
    y#3#1#5   valid_5             23
    y#3#1#5   valid_4             49
    y#3#1#5   balan@23            23
    y#3#1#5   balan@1d            49
    y#3#1#6   BigM_102             1
    y#3#1#6   valid_5             23
    y#3#1#6   valid_4             49
    y#3#1#6   balan@24            23
    y#3#1#6   balan@1e            49
    y#3#2#1   BigM_103             1
    y#3#2#1   valid_5             46
    y#3#2#1   valid_4             26
    y#3#2#1   balan@1f            46
    y#3#2#1   balan@19            26
    y#3#2#2   BigM_104             1
    y#3#2#2   valid_5             46
    y#3#2#2   valid_4             26
    y#3#2#2   balan@20            46
    y#3#2#2   balan@1a            26
    y#3#2#3   BigM_105             1
    y#3#2#3   valid_5             46
    y#3#2#3   valid_4             26
    y#3#2#3   balan@21            46
    y#3#2#3   balan@1b            26
    y#3#2#4   BigM_106             1
    y#3#2#4   valid_5             46
    y#3#2#4   valid_4             26
    y#3#2#4   balan@22            46
    y#3#2#4   balan@1c            26
    y#3#2#5   BigM_107             1
    y#3#2#5   valid_5             46
    y#3#2#5   valid_4             26
    y#3#2#5   balan@23            46
    y#3#2#5   balan@1d            26
    y#3#2#6   BigM_108             1
    y#3#2#6   valid_5             46
    y#3#2#6   valid_4             26
    y#3#2#6   balan@24            46
    y#3#2#6   balan@1e            26
    y#3#3#1   BigM_109             1
    y#3#3#1   valid_5             63
    y#3#3#1   valid_4              9
    y#3#3#1   balan@1f            63
    y#3#3#1   balan@19             9
    y#3#3#2   BigM_110             1
    y#3#3#2   valid_5             63
    y#3#3#2   valid_4              9
    y#3#3#2   balan@20            63
    y#3#3#2   balan@1a             9
    y#3#3#3   BigM_111             1
    y#3#3#3   valid_5             63
    y#3#3#3   valid_4              9
    y#3#3#3   balan@21            63
    y#3#3#3   balan@1b             9
    y#3#3#4   BigM_112             1
    y#3#3#4   valid_5             63
    y#3#3#4   valid_4              9
    y#3#3#4   balan@22            63
    y#3#3#4   balan@1c             9
    y#3#3#5   BigM_113             1
    y#3#3#5   valid_5             63
    y#3#3#5   valid_4              9
    y#3#3#5   balan@23            63
    y#3#3#5   balan@1d             9
    y#3#3#6   BigM_114             1
    y#3#3#6   valid_5             63
    y#3#3#6   valid_4              9
    y#3#3#6   balan@24            63
    y#3#3#6   balan@1e             9
    y#3#4#1   BigM_115             1
    y#3#4#1   valid_5             32
    y#3#4#1   valid_4             40
    y#3#4#1   balan@1f            32
    y#3#4#1   balan@19            40
    y#3#4#2   BigM_116             1
    y#3#4#2   valid_5             32
    y#3#4#2   valid_4             40
    y#3#4#2   balan@20            32
    y#3#4#2   balan@1a            40
    y#3#4#3   BigM_117             1
    y#3#4#3   valid_5             32
    y#3#4#3   valid_4             40
    y#3#4#3   balan@21            32
    y#3#4#3   balan@1b            40
    y#3#4#4   BigM_118             1
    y#3#4#4   valid_5             32
    y#3#4#4   valid_4             40
    y#3#4#4   balan@22            32
    y#3#4#4   balan@1c            40
    y#3#4#5   BigM_119             1
    y#3#4#5   valid_5             32
    y#3#4#5   valid_4             40
    y#3#4#5   balan@23            32
    y#3#4#5   balan@1d            40
    y#3#4#6   BigM_120             1
    y#3#4#6   valid_5             32
    y#3#4#6   valid_4             40
    y#3#4#6   balan@24            32
    y#3#4#6   balan@1e            40
    y#3#5#1   BigM_121             1
    y#3#5#1   valid_5             34
    y#3#5#1   valid_4             38
    y#3#5#1   balan@1f            34
    y#3#5#1   balan@19            38
    y#3#5#2   BigM_122             1
    y#3#5#2   valid_5             34
    y#3#5#2   valid_4             38
    y#3#5#2   balan@20            34
    y#3#5#2   balan@1a            38
    y#3#5#3   BigM_123             1
    y#3#5#3   valid_5             34
    y#3#5#3   valid_4             38
    y#3#5#3   balan@21            34
    y#3#5#3   balan@1b            38
    y#3#5#4   BigM_124             1
    y#3#5#4   valid_5             34
    y#3#5#4   valid_4             38
    y#3#5#4   balan@22            34
    y#3#5#4   balan@1c            38
    y#3#5#5   BigM_125             1
    y#3#5#5   valid_5             34
    y#3#5#5   valid_4             38
    y#3#5#5   balan@23            34
    y#3#5#5   balan@1d            38
    y#3#5#6   BigM_126             1
    y#3#5#6   valid_5             34
    y#3#5#6   valid_4             38
    y#3#5#6   balan@24            34
    y#3#5#6   balan@1e            38
    y#3#6#1   BigM_127             1
    y#3#6#1   valid_5             26
    y#3#6#1   valid_4             46
    y#3#6#1   balan@1f            26
    y#3#6#1   balan@19            46
    y#3#6#2   BigM_128             1
    y#3#6#2   valid_5             26
    y#3#6#2   valid_4             46
    y#3#6#2   balan@20            26
    y#3#6#2   balan@1a            46
    y#3#6#3   BigM_129             1
    y#3#6#3   valid_5             26
    y#3#6#3   valid_4             46
    y#3#6#3   balan@21            26
    y#3#6#3   balan@1b            46
    y#3#6#4   BigM_130             1
    y#3#6#4   valid_5             26
    y#3#6#4   valid_4             46
    y#3#6#4   balan@22            26
    y#3#6#4   balan@1c            46
    y#3#6#5   BigM_131             1
    y#3#6#5   valid_5             26
    y#3#6#5   valid_4             46
    y#3#6#5   balan@23            26
    y#3#6#5   balan@1d            46
    y#3#6#6   BigM_132             1
    y#3#6#6   valid_5             26
    y#3#6#6   valid_4             46
    y#3#6#6   balan@24            26
    y#3#6#6   balan@1e            46
    y#3#7#1   BigM_133             1
    y#3#7#1   valid_5             65
    y#3#7#1   valid_4              7
    y#3#7#1   balan@1f            65
    y#3#7#1   balan@19             7
    y#3#7#2   BigM_134             1
    y#3#7#2   valid_5             65
    y#3#7#2   valid_4              7
    y#3#7#2   balan@20            65
    y#3#7#2   balan@1a             7
    y#3#7#3   BigM_135             1
    y#3#7#3   valid_5             65
    y#3#7#3   valid_4              7
    y#3#7#3   balan@21            65
    y#3#7#3   balan@1b             7
    y#3#7#4   BigM_136             1
    y#3#7#4   valid_5             65
    y#3#7#4   valid_4              7
    y#3#7#4   balan@22            65
    y#3#7#4   balan@1c             7
    y#3#7#5   BigM_137             1
    y#3#7#5   valid_5             65
    y#3#7#5   valid_4              7
    y#3#7#5   balan@23            65
    y#3#7#5   balan@1d             7
    y#3#7#6   BigM_138             1
    y#3#7#6   valid_5             65
    y#3#7#6   valid_4              7
    y#3#7#6   balan@24            65
    y#3#7#6   balan@1e             7
    y#3#8#1   BigM_139             1
    y#3#8#1   valid_5             47
    y#3#8#1   valid_4             25
    y#3#8#1   balan@1f            47
    y#3#8#1   balan@19            25
    y#3#8#2   BigM_140             1
    y#3#8#2   valid_5             47
    y#3#8#2   valid_4             25
    y#3#8#2   balan@20            47
    y#3#8#2   balan@1a            25
    y#3#8#3   BigM_141             1
    y#3#8#3   valid_5             47
    y#3#8#3   valid_4             25
    y#3#8#3   balan@21            47
    y#3#8#3   balan@1b            25
    y#3#8#4   BigM_142             1
    y#3#8#4   valid_5             47
    y#3#8#4   valid_4             25
    y#3#8#4   balan@22            47
    y#3#8#4   balan@1c            25
    y#3#8#5   BigM_143             1
    y#3#8#5   valid_5             47
    y#3#8#5   valid_4             25
    y#3#8#5   balan@23            47
    y#3#8#5   balan@1d            25
    y#3#8#6   BigM_144             1
    y#3#8#6   valid_5             47
    y#3#8#6   valid_4             25
    y#3#8#6   balan@24            47
    y#3#8#6   balan@1e            25
    p#1       BigM_102         -1000
    p#1       BigM_101         -1000
    p#1       BigM_100         -1000
    p#1       BigM_99          -1000
    p#1       BigM_98          -1000
    p#1       BigM_97          -1000
    p#1       BigM_54          -1000
    p#1       BigM_53          -1000
    p#1       BigM_52          -1000
    p#1       BigM_51          -1000
    p#1       BigM_50          -1000
    p#1       BigM_49          -1000
    p#1       BigM_6           -1000
    p#1       BigM_5           -1000
    p#1       BigM_4           -1000
    p#1       BigM_3           -1000
    p#1       BigM_2           -1000
    p#1       BigM_1           -1000
    p#1       select_1             1
    p#2       BigM_108         -1000
    p#2       BigM_107         -1000
    p#2       BigM_106         -1000
    p#2       BigM_105         -1000
    p#2       BigM_104         -1000
    p#2       BigM_103         -1000
    p#2       BigM_60          -1000
    p#2       BigM_59          -1000
    p#2       BigM_58          -1000
    p#2       BigM_57          -1000
    p#2       BigM_56          -1000
    p#2       BigM_55          -1000
    p#2       BigM_12          -1000
    p#2       BigM_11          -1000
    p#2       BigM_10          -1000
    p#2       BigM_9           -1000
    p#2       BigM_8           -1000
    p#2       BigM_7           -1000
    p#2       select_1             1
    p#3       BigM_114         -1000
    p#3       BigM_113         -1000
    p#3       BigM_112         -1000
    p#3       BigM_111         -1000
    p#3       BigM_110         -1000
    p#3       BigM_109         -1000
    p#3       BigM_66          -1000
    p#3       BigM_65          -1000
    p#3       BigM_64          -1000
    p#3       BigM_63          -1000
    p#3       BigM_62          -1000
    p#3       BigM_61          -1000
    p#3       BigM_18          -1000
    p#3       BigM_17          -1000
    p#3       BigM_16          -1000
    p#3       BigM_15          -1000
    p#3       BigM_14          -1000
    p#3       BigM_13          -1000
    p#3       select_1             1
    p#4       BigM_120         -1000
    p#4       BigM_119         -1000
    p#4       BigM_118         -1000
    p#4       BigM_117         -1000
    p#4       BigM_116         -1000
    p#4       BigM_115         -1000
    p#4       BigM_72          -1000
    p#4       BigM_71          -1000
    p#4       BigM_70          -1000
    p#4       BigM_69          -1000
    p#4       BigM_68          -1000
    p#4       BigM_67          -1000
    p#4       BigM_24          -1000
    p#4       BigM_23          -1000
    p#4       BigM_22          -1000
    p#4       BigM_21          -1000
    p#4       BigM_20          -1000
    p#4       BigM_19          -1000
    p#4       select_1             1
    p#5       BigM_126         -1000
    p#5       BigM_125         -1000
    p#5       BigM_124         -1000
    p#5       BigM_123         -1000
    p#5       BigM_122         -1000
    p#5       BigM_121         -1000
    p#5       BigM_78          -1000
    p#5       BigM_77          -1000
    p#5       BigM_76          -1000
    p#5       BigM_75          -1000
    p#5       BigM_74          -1000
    p#5       BigM_73          -1000
    p#5       BigM_30          -1000
    p#5       BigM_29          -1000
    p#5       BigM_28          -1000
    p#5       BigM_27          -1000
    p#5       BigM_26          -1000
    p#5       BigM_25          -1000
    p#5       select_1             1
    p#6       BigM_132         -1000
    p#6       BigM_131         -1000
    p#6       BigM_130         -1000
    p#6       BigM_129         -1000
    p#6       BigM_128         -1000
    p#6       BigM_127         -1000
    p#6       BigM_84          -1000
    p#6       BigM_83          -1000
    p#6       BigM_82          -1000
    p#6       BigM_81          -1000
    p#6       BigM_80          -1000
    p#6       BigM_79          -1000
    p#6       BigM_36          -1000
    p#6       BigM_35          -1000
    p#6       BigM_34          -1000
    p#6       BigM_33          -1000
    p#6       BigM_32          -1000
    p#6       BigM_31          -1000
    p#6       select_1             1
    p#7       BigM_138         -1000
    p#7       BigM_137         -1000
    p#7       BigM_136         -1000
    p#7       BigM_135         -1000
    p#7       BigM_134         -1000
    p#7       BigM_133         -1000
    p#7       BigM_90          -1000
    p#7       BigM_89          -1000
    p#7       BigM_88          -1000
    p#7       BigM_87          -1000
    p#7       BigM_86          -1000
    p#7       BigM_85          -1000
    p#7       BigM_42          -1000
    p#7       BigM_41          -1000
    p#7       BigM_40          -1000
    p#7       BigM_39          -1000
    p#7       BigM_38          -1000
    p#7       BigM_37          -1000
    p#7       select_1             1
    p#8       BigM_144         -1000
    p#8       BigM_143         -1000
    p#8       BigM_142         -1000
    p#8       BigM_141         -1000
    p#8       BigM_140         -1000
    p#8       BigM_139         -1000
    p#8       BigM_96          -1000
    p#8       BigM_95          -1000
    p#8       BigM_94          -1000
    p#8       BigM_93          -1000
    p#8       BigM_92          -1000
    p#8       BigM_91          -1000
    p#8       BigM_48          -1000
    p#8       BigM_47          -1000
    p#8       BigM_46          -1000
    p#8       BigM_45          -1000
    p#8       BigM_44          -1000
    p#8       BigM_43          -1000
    p#8       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    B#1#1#0   init2_1              1
    B#1#1#0   balanc@1            -1
    B#1#1#1   OBJECTIV             5
    B#1#1#1   balanc@2            -1
    B#1#1#1   balanc@1             1
    B#1#1#2   OBJECTIV             5
    B#1#1#2   balanc@3            -1
    B#1#1#2   balanc@2             1
    B#1#1#3   OBJECTIV             5
    B#1#1#3   balanc@4            -1
    B#1#1#3   balanc@3             1
    B#1#1#4   OBJECTIV             5
    B#1#1#4   balanc@5            -1
    B#1#1#4   balanc@4             1
    B#1#1#5   OBJECTIV             5
    B#1#1#5   balanc@6            -1
    B#1#1#5   balanc@5             1
    B#1#1#6   OBJECTIV             5
    B#1#1#6   init3_1              1
    B#1#1#6   balanc@6             1
    B#1#2#0   init2_2              1
    B#1#2#0   balanc@7            -1
    B#1#2#1   OBJECTIV           5.5
    B#1#2#1   balanc@8            -1
    B#1#2#1   balanc@7             1
    B#1#2#2   OBJECTIV           5.5
    B#1#2#2   balanc@9            -1
    B#1#2#2   balanc@8             1
    B#1#2#3   OBJECTIV           5.5
    B#1#2#3   balanc@a            -1
    B#1#2#3   balanc@9             1
    B#1#2#4   OBJECTIV           5.5
    B#1#2#4   balanc@b            -1
    B#1#2#4   balanc@a             1
    B#1#2#5   OBJECTIV           5.5
    B#1#2#5   balanc@c            -1
    B#1#2#5   balanc@b             1
    B#1#2#6   OBJECTIV           5.5
    B#1#2#6   init3_2              1
    B#1#2#6   balanc@c             1
    B#2#1#0   init2_3              1
    B#2#1#0   balanc@d            -1
    B#2#1#1   OBJECTIV             5
    B#2#1#1   balanc@e            -1
    B#2#1#1   balanc@d             1
    B#2#1#2   OBJECTIV             5
    B#2#1#2   balanc@f            -1
    B#2#1#2   balanc@e             1
    B#2#1#3   OBJECTIV             5
    B#2#1#3   balan@10            -1
    B#2#1#3   balanc@f             1
    B#2#1#4   OBJECTIV             5
    B#2#1#4   balan@11            -1
    B#2#1#4   balan@10             1
    B#2#1#5   OBJECTIV             5
    B#2#1#5   balan@12            -1
    B#2#1#5   balan@11             1
    B#2#1#6   OBJECTIV             5
    B#2#1#6   init3_3              1
    B#2#1#6   balan@12             1
    B#2#2#0   init2_4              1
    B#2#2#0   balan@13            -1
    B#2#2#1   OBJECTIV           5.5
    B#2#2#1   balan@14            -1
    B#2#2#1   balan@13             1
    B#2#2#2   OBJECTIV           5.5
    B#2#2#2   balan@15            -1
    B#2#2#2   balan@14             1
    B#2#2#3   OBJECTIV           5.5
    B#2#2#3   balan@16            -1
    B#2#2#3   balan@15             1
    B#2#2#4   OBJECTIV           5.5
    B#2#2#4   balan@17            -1
    B#2#2#4   balan@16             1
    B#2#2#5   OBJECTIV           5.5
    B#2#2#5   balan@18            -1
    B#2#2#5   balan@17             1
    B#2#2#6   OBJECTIV           5.5
    B#2#2#6   init3_4              1
    B#2#2#6   balan@18             1
    B#3#1#0   init2_5              1
    B#3#1#0   balan@19            -1
    B#3#1#1   OBJECTIV             5
    B#3#1#1   balan@1a            -1
    B#3#1#1   balan@19             1
    B#3#1#2   OBJECTIV             5
    B#3#1#2   balan@1b            -1
    B#3#1#2   balan@1a             1
    B#3#1#3   OBJECTIV             5
    B#3#1#3   balan@1c            -1
    B#3#1#3   balan@1b             1
    B#3#1#4   OBJECTIV             5
    B#3#1#4   balan@1d            -1
    B#3#1#4   balan@1c             1
    B#3#1#5   OBJECTIV             5
    B#3#1#5   balan@1e            -1
    B#3#1#5   balan@1d             1
    B#3#1#6   OBJECTIV             5
    B#3#1#6   init3_5              1
    B#3#1#6   balan@1e             1
    B#3#2#0   init2_6              1
    B#3#2#0   balan@1f            -1
    B#3#2#1   OBJECTIV           5.5
    B#3#2#1   balan@20            -1
    B#3#2#1   balan@1f             1
    B#3#2#2   OBJECTIV           5.5
    B#3#2#2   balan@21            -1
    B#3#2#2   balan@20             1
    B#3#2#3   OBJECTIV           5.5
    B#3#2#3   balan@22            -1
    B#3#2#3   balan@21             1
    B#3#2#4   OBJECTIV           5.5
    B#3#2#4   balan@23            -1
    B#3#2#4   balan@22             1
    B#3#2#5   OBJECTIV           5.5
    B#3#2#5   balan@24            -1
    B#3#2#5   balan@23             1
    B#3#2#6   OBJECTIV           5.5
    B#3#2#6   init3_6              1
    B#3#2#6   balan@24             1
    I#1#1#0   init1_1              1
    I#1#1#0   balanc@1             1
    I#1#1#1   OBJECTIV             1
    I#1#1#1   balanc@2             1
    I#1#1#1   balanc@1            -1
    I#1#1#2   OBJECTIV             1
    I#1#1#2   balanc@3             1
    I#1#1#2   balanc@2            -1
    I#1#1#3   OBJECTIV             1
    I#1#1#3   balanc@4             1
    I#1#1#3   balanc@3            -1
    I#1#1#4   OBJECTIV             1
    I#1#1#4   balanc@5             1
    I#1#1#4   balanc@4            -1
    I#1#1#5   OBJECTIV             1
    I#1#1#5   balanc@6             1
    I#1#1#5   balanc@5            -1
    I#1#1#6   OBJECTIV             1
    I#1#1#6   balanc@6            -1
    I#1#2#0   init1_2              1
    I#1#2#0   balanc@7             1
    I#1#2#1   OBJECTIV           1.1
    I#1#2#1   balanc@8             1
    I#1#2#1   balanc@7            -1
    I#1#2#2   OBJECTIV           1.1
    I#1#2#2   balanc@9             1
    I#1#2#2   balanc@8            -1
    I#1#2#3   OBJECTIV           1.1
    I#1#2#3   balanc@a             1
    I#1#2#3   balanc@9            -1
    I#1#2#4   OBJECTIV           1.1
    I#1#2#4   balanc@b             1
    I#1#2#4   balanc@a            -1
    I#1#2#5   OBJECTIV           1.1
    I#1#2#5   balanc@c             1
    I#1#2#5   balanc@b            -1
    I#1#2#6   OBJECTIV           1.1
    I#1#2#6   balanc@c            -1
    I#2#1#0   init1_3              1
    I#2#1#0   balanc@d             1
    I#2#1#1   OBJECTIV             1
    I#2#1#1   balanc@e             1
    I#2#1#1   balanc@d            -1
    I#2#1#2   OBJECTIV             1
    I#2#1#2   balanc@f             1
    I#2#1#2   balanc@e            -1
    I#2#1#3   OBJECTIV             1
    I#2#1#3   balan@10             1
    I#2#1#3   balanc@f            -1
    I#2#1#4   OBJECTIV             1
    I#2#1#4   balan@11             1
    I#2#1#4   balan@10            -1
    I#2#1#5   OBJECTIV             1
    I#2#1#5   balan@12             1
    I#2#1#5   balan@11            -1
    I#2#1#6   OBJECTIV             1
    I#2#1#6   balan@12            -1
    I#2#2#0   init1_4              1
    I#2#2#0   balan@13             1
    I#2#2#1   OBJECTIV           1.1
    I#2#2#1   balan@14             1
    I#2#2#1   balan@13            -1
    I#2#2#2   OBJECTIV           1.1
    I#2#2#2   balan@15             1
    I#2#2#2   balan@14            -1
    I#2#2#3   OBJECTIV           1.1
    I#2#2#3   balan@16             1
    I#2#2#3   balan@15            -1
    I#2#2#4   OBJECTIV           1.1
    I#2#2#4   balan@17             1
    I#2#2#4   balan@16            -1
    I#2#2#5   OBJECTIV           1.1
    I#2#2#5   balan@18             1
    I#2#2#5   balan@17            -1
    I#2#2#6   OBJECTIV           1.1
    I#2#2#6   balan@18            -1
    I#3#1#0   init1_5              1
    I#3#1#0   balan@19             1
    I#3#1#1   OBJECTIV             1
    I#3#1#1   balan@1a             1
    I#3#1#1   balan@19            -1
    I#3#1#2   OBJECTIV             1
    I#3#1#2   balan@1b             1
    I#3#1#2   balan@1a            -1
    I#3#1#3   OBJECTIV             1
    I#3#1#3   balan@1c             1
    I#3#1#3   balan@1b            -1
    I#3#1#4   OBJECTIV             1
    I#3#1#4   balan@1d             1
    I#3#1#4   balan@1c            -1
    I#3#1#5   OBJECTIV             1
    I#3#1#5   balan@1e             1
    I#3#1#5   balan@1d            -1
    I#3#1#6   OBJECTIV             1
    I#3#1#6   balan@1e            -1
    I#3#2#0   init1_6              1
    I#3#2#0   balan@1f             1
    I#3#2#1   OBJECTIV           1.1
    I#3#2#1   balan@20             1
    I#3#2#1   balan@1f            -1
    I#3#2#2   OBJECTIV           1.1
    I#3#2#2   balan@21             1
    I#3#2#2   balan@20            -1
    I#3#2#3   OBJECTIV           1.1
    I#3#2#3   balan@22             1
    I#3#2#3   balan@21            -1
    I#3#2#4   OBJECTIV           1.1
    I#3#2#4   balan@23             1
    I#3#2#4   balan@22            -1
    I#3#2#5   OBJECTIV           1.1
    I#3#2#5   balan@24             1
    I#3#2#5   balan@23            -1
    I#3#2#6   OBJECTIV           1.1
    I#3#2#6   balan@24            -1
RHS
    RHS       select_1             1
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@4           669
    RHS       balanc@5           180
    RHS       balanc@6            45
    RHS       balanc@d           333
    RHS       balanc@e           776
    RHS       balanc@f           466
    RHS       balan@10           764
    RHS       balan@11           166
    RHS       balan@12           114
    RHS       balan@13           239
    RHS       balan@14           425
    RHS       balan@15           220
    RHS       balan@16           452
    RHS       balan@17           519
    RHS       balan@18            93
    RHS       balan@19           136
    RHS       balan@1a           621
    RHS       balan@1b           192
    RHS       balan@1c            74
    RHS       balan@1d           510
    RHS       balan@1e            49
    RHS       balan@1f             7
    RHS       balan@20            27
    RHS       balan@21           934
    RHS       balan@22           620
    RHS       balan@23           585
    RHS       balan@24           310
    RHS       valid_1           2216
    RHS       valid_2           2619
    RHS       valid_3           1948
    RHS       valid_4           1582
    RHS       valid_5           2483
BOUNDS
 LO BOUND     B#1#1#0              0
 PL BOUND     B#1#1#0 
 LO BOUND     B#1#1#1              0
 PL BOUND     B#1#1#1 
 LO BOUND     B#1#1#2              0
 PL BOUND     B#1#1#2 
 LO BOUND     B#1#1#3              0
 PL BOUND     B#1#1#3 
 LO BOUND     B#1#1#4              0
 PL BOUND     B#1#1#4 
 LO BOUND     B#1#1#5              0
 PL BOUND     B#1#1#5 
 LO BOUND     B#1#1#6              0
 PL BOUND     B#1#1#6 
 LO BOUND     B#1#2#0              0
 PL BOUND     B#1#2#0 
 LO BOUND     B#1#2#1              0
 PL BOUND     B#1#2#1 
 LO BOUND     B#1#2#2              0
 PL BOUND     B#1#2#2 
 LO BOUND     B#1#2#3              0
 PL BOUND     B#1#2#3 
 LO BOUND     B#1#2#4              0
 PL BOUND     B#1#2#4 
 LO BOUND     B#1#2#5              0
 PL BOUND     B#1#2#5 
 LO BOUND     B#1#2#6              0
 PL BOUND     B#1#2#6 
 LO BOUND     B#2#1#0              0
 PL BOUND     B#2#1#0 
 LO BOUND     B#2#1#1              0
 PL BOUND     B#2#1#1 
 LO BOUND     B#2#1#2              0
 PL BOUND     B#2#1#2 
 LO BOUND     B#2#1#3              0
 PL BOUND     B#2#1#3 
 LO BOUND     B#2#1#4              0
 PL BOUND     B#2#1#4 
 LO BOUND     B#2#1#5              0
 PL BOUND     B#2#1#5 
 LO BOUND     B#2#1#6              0
 PL BOUND     B#2#1#6 
 LO BOUND     B#2#2#0              0
 PL BOUND     B#2#2#0 
 LO BOUND     B#2#2#1              0
 PL BOUND     B#2#2#1 
 LO BOUND     B#2#2#2              0
 PL BOUND     B#2#2#2 
 LO BOUND     B#2#2#3              0
 PL BOUND     B#2#2#3 
 LO BOUND     B#2#2#4              0
 PL BOUND     B#2#2#4 
 LO BOUND     B#2#2#5              0
 PL BOUND     B#2#2#5 
 LO BOUND     B#2#2#6              0
 PL BOUND     B#2#2#6 
 LO BOUND     B#3#1#0              0
 PL BOUND     B#3#1#0 
 LO BOUND     B#3#1#1              0
 PL BOUND     B#3#1#1 
 LO BOUND     B#3#1#2              0
 PL BOUND     B#3#1#2 
 LO BOUND     B#3#1#3              0
 PL BOUND     B#3#1#3 
 LO BOUND     B#3#1#4              0
 PL BOUND     B#3#1#4 
 LO BOUND     B#3#1#5              0
 PL BOUND     B#3#1#5 
 LO BOUND     B#3#1#6              0
 PL BOUND     B#3#1#6 
 LO BOUND     B#3#2#0              0
 PL BOUND     B#3#2#0 
 LO BOUND     B#3#2#1              0
 PL BOUND     B#3#2#1 
 LO BOUND     B#3#2#2              0
 PL BOUND     B#3#2#2 
 LO BOUND     B#3#2#3              0
 PL BOUND     B#3#2#3 
 LO BOUND     B#3#2#4              0
 PL BOUND     B#3#2#4 
 LO BOUND     B#3#2#5              0
 PL BOUND     B#3#2#5 
 LO BOUND     B#3#2#6              0
 PL BOUND     B#3#2#6 
 LO BOUND     I#1#1#0              0
 PL BOUND     I#1#1#0 
 LO BOUND     I#1#1#1              0
 PL BOUND     I#1#1#1 
 LO BOUND     I#1#1#2              0
 PL BOUND     I#1#1#2 
 LO BOUND     I#1#1#3              0
 PL BOUND     I#1#1#3 
 LO BOUND     I#1#1#4              0
 PL BOUND     I#1#1#4 
 LO BOUND     I#1#1#5              0
 PL BOUND     I#1#1#5 
 LO BOUND     I#1#1#6              0
 PL BOUND     I#1#1#6 
 LO BOUND     I#1#2#0              0
 PL BOUND     I#1#2#0 
 LO BOUND     I#1#2#1              0
 PL BOUND     I#1#2#1 
 LO BOUND     I#1#2#2              0
 PL BOUND     I#1#2#2 
 LO BOUND     I#1#2#3              0
 PL BOUND     I#1#2#3 
 LO BOUND     I#1#2#4              0
 PL BOUND     I#1#2#4 
 LO BOUND     I#1#2#5              0
 PL BOUND     I#1#2#5 
 LO BOUND     I#1#2#6              0
 PL BOUND     I#1#2#6 
 LO BOUND     I#2#1#0              0
 PL BOUND     I#2#1#0 
 LO BOUND     I#2#1#1              0
 PL BOUND     I#2#1#1 
 LO BOUND     I#2#1#2              0
 PL BOUND     I#2#1#2 
 LO BOUND     I#2#1#3              0
 PL BOUND     I#2#1#3 
 LO BOUND     I#2#1#4              0
 PL BOUND     I#2#1#4 
 LO BOUND     I#2#1#5              0
 PL BOUND     I#2#1#5 
 LO BOUND     I#2#1#6              0
 PL BOUND     I#2#1#6 
 LO BOUND     I#2#2#0              0
 PL BOUND     I#2#2#0 
 LO BOUND     I#2#2#1              0
 PL BOUND     I#2#2#1 
 LO BOUND     I#2#2#2              0
 PL BOUND     I#2#2#2 
 LO BOUND     I#2#2#3              0
 PL BOUND     I#2#2#3 
 LO BOUND     I#2#2#4              0
 PL BOUND     I#2#2#4 
 LO BOUND     I#2#2#5              0
 PL BOUND     I#2#2#5 
 LO BOUND     I#2#2#6              0
 PL BOUND     I#2#2#6 
 LO BOUND     I#3#1#0              0
 PL BOUND     I#3#1#0 
 LO BOUND     I#3#1#1              0
 PL BOUND     I#3#1#1 
 LO BOUND     I#3#1#2              0
 PL BOUND     I#3#1#2 
 LO BOUND     I#3#1#3              0
 PL BOUND     I#3#1#3 
 LO BOUND     I#3#1#4              0
 PL BOUND     I#3#1#4 
 LO BOUND     I#3#1#5              0
 PL BOUND     I#3#1#5 
 LO BOUND     I#3#1#6              0
 PL BOUND     I#3#1#6 
 LO BOUND     I#3#2#0              0
 PL BOUND     I#3#2#0 
 LO BOUND     I#3#2#1              0
 PL BOUND     I#3#2#1 
 LO BOUND     I#3#2#2              0
 PL BOUND     I#3#2#2 
 LO BOUND     I#3#2#3              0
 PL BOUND     I#3#2#3 
 LO BOUND     I#3#2#4              0
 PL BOUND     I#3#2#4 
 LO BOUND     I#3#2#5              0
 PL BOUND     I#3#2#5 
 LO BOUND     I#3#2#6              0
 PL BOUND     I#3#2#6 
 LO BOUND     f#1#1#1              0
 PL BOUND     f#1#1#1 
 LO BOUND     f#1#1#2              0
 PL BOUND     f#1#1#2 
 LO BOUND     f#1#1#3              0
 PL BOUND     f#1#1#3 
 LO BOUND     f#1#1#4              0
 PL BOUND     f#1#1#4 
 LO BOUND     f#1#1#5              0
 PL BOUND     f#1#1#5 
 LO BOUND     f#1#1#6              0
 PL BOUND     f#1#1#6 
 LO BOUND     f#1#2#1              0
 PL BOUND     f#1#2#1 
 LO BOUND     f#1#2#2              0
 PL BOUND     f#1#2#2 
 LO BOUND     f#1#2#3              0
 PL BOUND     f#1#2#3 
 LO BOUND     f#1#2#4              0
 PL BOUND     f#1#2#4 
 LO BOUND     f#1#2#5              0
 PL BOUND     f#1#2#5 
 LO BOUND     f#1#2#6              0
 PL BOUND     f#1#2#6 
 LO BOUND     f#2#1#1              0
 PL BOUND     f#2#1#1 
 LO BOUND     f#2#1#2              0
 PL BOUND     f#2#1#2 
 LO BOUND     f#2#1#3              0
 PL BOUND     f#2#1#3 
 LO BOUND     f#2#1#4              0
 PL BOUND     f#2#1#4 
 LO BOUND     f#2#1#5              0
 PL BOUND     f#2#1#5 
 LO BOUND     f#2#1#6              0
 PL BOUND     f#2#1#6 
 LO BOUND     f#2#2#1              0
 PL BOUND     f#2#2#1 
 LO BOUND     f#2#2#2              0
 PL BOUND     f#2#2#2 
 LO BOUND     f#2#2#3              0
 PL BOUND     f#2#2#3 
 LO BOUND     f#2#2#4              0
 PL BOUND     f#2#2#4 
 LO BOUND     f#2#2#5              0
 PL BOUND     f#2#2#5 
 LO BOUND     f#2#2#6              0
 PL BOUND     f#2#2#6 
 LO BOUND     f#3#1#1              0
 PL BOUND     f#3#1#1 
 LO BOUND     f#3#1#2              0
 PL BOUND     f#3#1#2 
 LO BOUND     f#3#1#3              0
 PL BOUND     f#3#1#3 
 LO BOUND     f#3#1#4              0
 PL BOUND     f#3#1#4 
 LO BOUND     f#3#1#5              0
 PL BOUND     f#3#1#5 
 LO BOUND     f#3#1#6              0
 PL BOUND     f#3#1#6 
 LO BOUND     f#3#2#1              0
 PL BOUND     f#3#2#1 
 LO BOUND     f#3#2#2              0
 PL BOUND     f#3#2#2 
 LO BOUND     f#3#2#3              0
 PL BOUND     f#3#2#3 
 LO BOUND     f#3#2#4              0
 PL BOUND     f#3#2#4 
 LO BOUND     f#3#2#5              0
 PL BOUND     f#3#2#5 
 LO BOUND     f#3#2#6              0
 PL BOUND     f#3#2#6 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#1#4              0
 PL BOUND     y#1#1#4 
 LO BOUND     y#1#1#5              0
 PL BOUND     y#1#1#5 
 LO BOUND     y#1#1#6              0
 PL BOUND     y#1#1#6 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#2#4              0
 PL BOUND     y#1#2#4 
 LO BOUND     y#1#2#5              0
 PL BOUND     y#1#2#5 
 LO BOUND     y#1#2#6              0
 PL BOUND     y#1#2#6 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#3#4              0
 PL BOUND     y#1#3#4 
 LO BOUND     y#1#3#5              0
 PL BOUND     y#1#3#5 
 LO BOUND     y#1#3#6              0
 PL BOUND     y#1#3#6 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#4#4              0
 PL BOUND     y#1#4#4 
 LO BOUND     y#1#4#5              0
 PL BOUND     y#1#4#5 
 LO BOUND     y#1#4#6              0
 PL BOUND     y#1#4#6 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#5#4              0
 PL BOUND     y#1#5#4 
 LO BOUND     y#1#5#5              0
 PL BOUND     y#1#5#5 
 LO BOUND     y#1#5#6              0
 PL BOUND     y#1#5#6 
 LO BOUND     y#1#6#1              0
 PL BOUND     y#1#6#1 
 LO BOUND     y#1#6#2              0
 PL BOUND     y#1#6#2 
 LO BOUND     y#1#6#3              0
 PL BOUND     y#1#6#3 
 LO BOUND     y#1#6#4              0
 PL BOUND     y#1#6#4 
 LO BOUND     y#1#6#5              0
 PL BOUND     y#1#6#5 
 LO BOUND     y#1#6#6              0
 PL BOUND     y#1#6#6 
 LO BOUND     y#1#7#1              0
 PL BOUND     y#1#7#1 
 LO BOUND     y#1#7#2              0
 PL BOUND     y#1#7#2 
 LO BOUND     y#1#7#3              0
 PL BOUND     y#1#7#3 
 LO BOUND     y#1#7#4              0
 PL BOUND     y#1#7#4 
 LO BOUND     y#1#7#5              0
 PL BOUND     y#1#7#5 
 LO BOUND     y#1#7#6              0
 PL BOUND     y#1#7#6 
 LO BOUND     y#1#8#1              0
 PL BOUND     y#1#8#1 
 LO BOUND     y#1#8#2              0
 PL BOUND     y#1#8#2 
 LO BOUND     y#1#8#3              0
 PL BOUND     y#1#8#3 
 LO BOUND     y#1#8#4              0
 PL BOUND     y#1#8#4 
 LO BOUND     y#1#8#5              0
 PL BOUND     y#1#8#5 
 LO BOUND     y#1#8#6              0
 PL BOUND     y#1#8#6 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#1#4              0
 PL BOUND     y#2#1#4 
 LO BOUND     y#2#1#5              0
 PL BOUND     y#2#1#5 
 LO BOUND     y#2#1#6              0
 PL BOUND     y#2#1#6 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#2#4              0
 PL BOUND     y#2#2#4 
 LO BOUND     y#2#2#5              0
 PL BOUND     y#2#2#5 
 LO BOUND     y#2#2#6              0
 PL BOUND     y#2#2#6 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#3#4              0
 PL BOUND     y#2#3#4 
 LO BOUND     y#2#3#5              0
 PL BOUND     y#2#3#5 
 LO BOUND     y#2#3#6              0
 PL BOUND     y#2#3#6 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#4#4              0
 PL BOUND     y#2#4#4 
 LO BOUND     y#2#4#5              0
 PL BOUND     y#2#4#5 
 LO BOUND     y#2#4#6              0
 PL BOUND     y#2#4#6 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#5#4              0
 PL BOUND     y#2#5#4 
 LO BOUND     y#2#5#5              0
 PL BOUND     y#2#5#5 
 LO BOUND     y#2#5#6              0
 PL BOUND     y#2#5#6 
 LO BOUND     y#2#6#1              0
 PL BOUND     y#2#6#1 
 LO BOUND     y#2#6#2              0
 PL BOUND     y#2#6#2 
 LO BOUND     y#2#6#3              0
 PL BOUND     y#2#6#3 
 LO BOUND     y#2#6#4              0
 PL BOUND     y#2#6#4 
 LO BOUND     y#2#6#5              0
 PL BOUND     y#2#6#5 
 LO BOUND     y#2#6#6              0
 PL BOUND     y#2#6#6 
 LO BOUND     y#2#7#1              0
 PL BOUND     y#2#7#1 
 LO BOUND     y#2#7#2              0
 PL BOUND     y#2#7#2 
 LO BOUND     y#2#7#3              0
 PL BOUND     y#2#7#3 
 LO BOUND     y#2#7#4              0
 PL BOUND     y#2#7#4 
 LO BOUND     y#2#7#5              0
 PL BOUND     y#2#7#5 
 LO BOUND     y#2#7#6              0
 PL BOUND     y#2#7#6 
 LO BOUND     y#2#8#1              0
 PL BOUND     y#2#8#1 
 LO BOUND     y#2#8#2              0
 PL BOUND     y#2#8#2 
 LO BOUND     y#2#8#3              0
 PL BOUND     y#2#8#3 
 LO BOUND     y#2#8#4              0
 PL BOUND     y#2#8#4 
 LO BOUND     y#2#8#5              0
 PL BOUND     y#2#8#5 
 LO BOUND     y#2#8#6              0
 PL BOUND     y#2#8#6 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#1#4              0
 PL BOUND     y#3#1#4 
 LO BOUND     y#3#1#5              0
 PL BOUND     y#3#1#5 
 LO BOUND     y#3#1#6              0
 PL BOUND     y#3#1#6 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#2#4              0
 PL BOUND     y#3#2#4 
 LO BOUND     y#3#2#5              0
 PL BOUND     y#3#2#5 
 LO BOUND     y#3#2#6              0
 PL BOUND     y#3#2#6 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#3#4              0
 PL BOUND     y#3#3#4 
 LO BOUND     y#3#3#5              0
 PL BOUND     y#3#3#5 
 LO BOUND     y#3#3#6              0
 PL BOUND     y#3#3#6 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#4#4              0
 PL BOUND     y#3#4#4 
 LO BOUND     y#3#4#5              0
 PL BOUND     y#3#4#5 
 LO BOUND     y#3#4#6              0
 PL BOUND     y#3#4#6 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#5#4              0
 PL BOUND     y#3#5#4 
 LO BOUND     y#3#5#5              0
 PL BOUND     y#3#5#5 
 LO BOUND     y#3#5#6              0
 PL BOUND     y#3#5#6 
 LO BOUND     y#3#6#1              0
 PL BOUND     y#3#6#1 
 LO BOUND     y#3#6#2              0
 PL BOUND     y#3#6#2 
 LO BOUND     y#3#6#3              0
 PL BOUND     y#3#6#3 
 LO BOUND     y#3#6#4              0
 PL BOUND     y#3#6#4 
 LO BOUND     y#3#6#5              0
 PL BOUND     y#3#6#5 
 LO BOUND     y#3#6#6              0
 PL BOUND     y#3#6#6 
 LO BOUND     y#3#7#1              0
 PL BOUND     y#3#7#1 
 LO BOUND     y#3#7#2              0
 PL BOUND     y#3#7#2 
 LO BOUND     y#3#7#3              0
 PL BOUND     y#3#7#3 
 LO BOUND     y#3#7#4              0
 PL BOUND     y#3#7#4 
 LO BOUND     y#3#7#5              0
 PL BOUND     y#3#7#5 
 LO BOUND     y#3#7#6              0
 PL BOUND     y#3#7#6 
 LO BOUND     y#3#8#1              0
 PL BOUND     y#3#8#1 
 LO BOUND     y#3#8#2              0
 PL BOUND     y#3#8#2 
 LO BOUND     y#3#8#3              0
 PL BOUND     y#3#8#3 
 LO BOUND     y#3#8#4              0
 PL BOUND     y#3#8#4 
 LO BOUND     y#3#8#5              0
 PL BOUND     y#3#8#5 
 LO BOUND     y#3#8#6              0
 PL BOUND     y#3#8#6 
 LO BOUND     p#1                  0
 UP BOUND     p#1                  1
 LO BOUND     p#2                  0
 UP BOUND     p#2                  1
 LO BOUND     p#3                  0
 UP BOUND     p#3                  1
 LO BOUND     p#4                  0
 UP BOUND     p#4                  1
 LO BOUND     p#5                  0
 UP BOUND     p#5                  1
 LO BOUND     p#6                  0
 UP BOUND     p#6                  1
 LO BOUND     p#7                  0
 UP BOUND     p#7                  1
 LO BOUND     p#8                  0
 UP BOUND     p#8                  1
ENDATA
