* This file was automatically generated by Zimpl
* param Q2 := 1;
* param M := 1000;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nN := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set N := { 1 .. nN };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[N] := read file1 as "<1n> 2n" skip 1 use nN;
* param backCost[N] := read file1 as "<1n> 2n" skip nN+1 use nN;
* param demand[C*N*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nN+1;
* param q[P*N] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*N] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in N with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <j> in P with q[j,i] > 0 };
* var B[C*N*T0] >= 0;
* var I[C*N*T0] >= 0;
* var f[C*N*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var p[P] binary;
* minimize cost: sum <i> in N: ( sum <t> in T: (sum <c> in C : (inveCost[i] * I[c,i,t]  + backCost[i] * B[c,i,t]) ));
* subto select:       sum <j> in P: p[j] <= m;
* subto balance:    forall <c,i,t> in C*N*T with t>=1 do       I[c,i,t-1] - B[c,i,t-1] + Q1*Q2*f[c,i,t] + Q2 * (sum <j> in Pc[c
* ]: q[j,i] * y[c,j,t]) == demand[c,i,t] + I[c,i,t] - B[c,i,t];
* subto valid:    forall <c,i> in C*N do       sum <t> in T: ( min(Q1, D[c,i]) * f[c,i,t] + sum <j> in Pc[c]: ( min(q[j,i], D[c
* ,i] ) * y[c,j,t]) ) >= D[c,i];
* subto BigM:    forall <c,j,t> in C*P*T with t>=1 do       y[c,j,t] <= M*p[j];
* subto init1:    forall <c,i> in C*N do       I[c,i,0] == 0;
* subto init2:    forall <c,i> in C*N do       B[c,i,0] == 0;
* subto init3:    forall <c,i> in C*N do       B[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 G  valid_7           
 G  valid_8           
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 L  BigM_101          
 L  BigM_102          
 L  BigM_103          
 L  BigM_104          
 L  BigM_105          
 L  BigM_106          
 L  BigM_107          
 L  BigM_108          
 L  BigM_109          
 L  BigM_110          
 L  BigM_111          
 L  BigM_112          
 L  BigM_113          
 L  BigM_114          
 L  BigM_115          
 L  BigM_116          
 L  BigM_117          
 L  BigM_118          
 L  BigM_119          
 L  BigM_120          
 L  BigM_121          
 L  BigM_122          
 L  BigM_123          
 L  BigM_124          
 L  BigM_125          
 L  BigM_126          
 L  BigM_127          
 L  BigM_128          
 L  BigM_129          
 L  BigM_130          
 L  BigM_131          
 L  BigM_132          
 L  BigM_133          
 L  BigM_134          
 L  BigM_135          
 L  BigM_136          
 L  BigM_137          
 L  BigM_138          
 L  BigM_139          
 L  BigM_140          
 L  BigM_141          
 L  BigM_142          
 L  BigM_143          
 L  BigM_144          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init1_9           
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init2_9           
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
 E  init3_9           
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    f#1#1#1   valid_1             72
    f#1#1#1   balanc@1            72
    f#1#1#2   valid_1             72
    f#1#1#2   balanc@2            72
    f#1#1#3   valid_1             72
    f#1#1#3   balanc@3            72
    f#1#2#1   balanc@4            72
    f#1#2#2   balanc@5            72
    f#1#2#3   balanc@6            72
    f#1#3#1   valid_2             72
    f#1#3#1   balanc@7            72
    f#1#3#2   valid_2             72
    f#1#3#2   balanc@8            72
    f#1#3#3   valid_2             72
    f#1#3#3   balanc@9            72
    f#2#1#1   valid_3             72
    f#2#1#1   balanc@a            72
    f#2#1#2   valid_3             72
    f#2#1#2   balanc@b            72
    f#2#1#3   valid_3             72
    f#2#1#3   balanc@c            72
    f#2#2#1   valid_4             72
    f#2#2#1   balanc@d            72
    f#2#2#2   valid_4             72
    f#2#2#2   balanc@e            72
    f#2#2#3   valid_4             72
    f#2#2#3   balanc@f            72
    f#2#3#1   valid_5             72
    f#2#3#1   balan@10            72
    f#2#3#2   valid_5             72
    f#2#3#2   balan@11            72
    f#2#3#3   valid_5             72
    f#2#3#3   balan@12            72
    f#3#1#1   valid_6             72
    f#3#1#1   balan@13            72
    f#3#1#2   valid_6             72
    f#3#1#2   balan@14            72
    f#3#1#3   valid_6             72
    f#3#1#3   balan@15            72
    f#3#2#1   valid_7             72
    f#3#2#1   balan@16            72
    f#3#2#2   valid_7             72
    f#3#2#2   balan@17            72
    f#3#2#3   valid_7             72
    f#3#2#3   balan@18            72
    f#3#3#1   valid_8             72
    f#3#3#1   balan@19            72
    f#3#3#2   valid_8             72
    f#3#3#2   balan@1a            72
    f#3#3#3   valid_8             72
    f#3#3#3   balan@1b            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_2              5
    y#1#1#1   valid_1             51
    y#1#1#1   balanc@7             5
    y#1#1#1   balanc@4            16
    y#1#1#1   balanc@1            51
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_2              5
    y#1#1#2   valid_1             51
    y#1#1#2   balanc@8             5
    y#1#1#2   balanc@5            16
    y#1#1#2   balanc@2            51
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_2              5
    y#1#1#3   valid_1             51
    y#1#1#3   balanc@9             5
    y#1#1#3   balanc@6            16
    y#1#1#3   balanc@3            51
    y#1#2#1   BigM_4               1
    y#1#2#1   valid_2             46
    y#1#2#1   valid_1             19
    y#1#2#1   balanc@7            46
    y#1#2#1   balanc@4             7
    y#1#2#1   balanc@1            19
    y#1#2#2   BigM_5               1
    y#1#2#2   valid_2             46
    y#1#2#2   valid_1             19
    y#1#2#2   balanc@8            46
    y#1#2#2   balanc@5             7
    y#1#2#2   balanc@2            19
    y#1#2#3   BigM_6               1
    y#1#2#3   valid_2             46
    y#1#2#3   valid_1             19
    y#1#2#3   balanc@9            46
    y#1#2#3   balanc@6             7
    y#1#2#3   balanc@3            19
    y#1#3#1   BigM_7               1
    y#1#3#1   valid_2             42
    y#1#3#1   valid_1              6
    y#1#3#1   balanc@7            42
    y#1#3#1   balanc@4            24
    y#1#3#1   balanc@1             6
    y#1#3#2   BigM_8               1
    y#1#3#2   valid_2             42
    y#1#3#2   valid_1              6
    y#1#3#2   balanc@8            42
    y#1#3#2   balanc@5            24
    y#1#3#2   balanc@2             6
    y#1#3#3   BigM_9               1
    y#1#3#3   valid_2             42
    y#1#3#3   valid_1              6
    y#1#3#3   balanc@9            42
    y#1#3#3   balanc@6            24
    y#1#3#3   balanc@3             6
    y#1#4#1   BigM_10              1
    y#1#4#1   valid_2              7
    y#1#4#1   valid_1              1
    y#1#4#1   balanc@7             7
    y#1#4#1   balanc@4            64
    y#1#4#1   balanc@1             1
    y#1#4#2   BigM_11              1
    y#1#4#2   valid_2              7
    y#1#4#2   valid_1              1
    y#1#4#2   balanc@8             7
    y#1#4#2   balanc@5            64
    y#1#4#2   balanc@2             1
    y#1#4#3   BigM_12              1
    y#1#4#3   valid_2              7
    y#1#4#3   valid_1              1
    y#1#4#3   balanc@9             7
    y#1#4#3   balanc@6            64
    y#1#4#3   balanc@3             1
    y#1#5#1   BigM_13              1
    y#1#5#1   valid_2             30
    y#1#5#1   valid_1             20
    y#1#5#1   balanc@7            30
    y#1#5#1   balanc@4            22
    y#1#5#1   balanc@1            20
    y#1#5#2   BigM_14              1
    y#1#5#2   valid_2             30
    y#1#5#2   valid_1             20
    y#1#5#2   balanc@8            30
    y#1#5#2   balanc@5            22
    y#1#5#2   balanc@2            20
    y#1#5#3   BigM_15              1
    y#1#5#3   valid_2             30
    y#1#5#3   valid_1             20
    y#1#5#3   balanc@9            30
    y#1#5#3   balanc@6            22
    y#1#5#3   balanc@3            20
    y#1#6#1   BigM_16              1
    y#1#6#1   valid_2             36
    y#1#6#1   valid_1             18
    y#1#6#1   balanc@7            36
    y#1#6#1   balanc@4            18
    y#1#6#1   balanc@1            18
    y#1#6#2   BigM_17              1
    y#1#6#2   valid_2             36
    y#1#6#2   valid_1             18
    y#1#6#2   balanc@8            36
    y#1#6#2   balanc@5            18
    y#1#6#2   balanc@2            18
    y#1#6#3   BigM_18              1
    y#1#6#3   valid_2             36
    y#1#6#3   valid_1             18
    y#1#6#3   balanc@9            36
    y#1#6#3   balanc@6            18
    y#1#6#3   balanc@3            18
    y#1#7#1   BigM_19              1
    y#1#7#2   BigM_20              1
    y#1#7#3   BigM_21              1
    y#1#8#1   BigM_22              1
    y#1#8#1   valid_2             45
    y#1#8#1   valid_1             27
    y#1#8#1   balanc@7            45
    y#1#8#1   balanc@1            27
    y#1#8#2   BigM_23              1
    y#1#8#2   valid_2             45
    y#1#8#2   valid_1             27
    y#1#8#2   balanc@8            45
    y#1#8#2   balanc@2            27
    y#1#8#3   BigM_24              1
    y#1#8#3   valid_2             45
    y#1#8#3   valid_1             27
    y#1#8#3   balanc@9            45
    y#1#8#3   balanc@3            27
    y#1#9#1   BigM_25              1
    y#1#9#1   valid_2             31
    y#1#9#1   valid_1             30
    y#1#9#1   balanc@7            31
    y#1#9#1   balanc@4            11
    y#1#9#1   balanc@1            30
    y#1#9#2   BigM_26              1
    y#1#9#2   valid_2             31
    y#1#9#2   valid_1             30
    y#1#9#2   balanc@8            31
    y#1#9#2   balanc@5            11
    y#1#9#2   balanc@2            30
    y#1#9#3   BigM_27              1
    y#1#9#3   valid_2             31
    y#1#9#3   valid_1             30
    y#1#9#3   balanc@9            31
    y#1#9#3   balanc@6            11
    y#1#9#3   balanc@3            30
    y#1#10#1  BigM_28              1
    y#1#10#1  valid_2              6
    y#1#10#1  valid_1             11
    y#1#10#1  balanc@7             6
    y#1#10#1  balanc@4            55
    y#1#10#1  balanc@1            11
    y#1#10#2  BigM_29              1
    y#1#10#2  valid_2              6
    y#1#10#2  valid_1             11
    y#1#10#2  balanc@8             6
    y#1#10#2  balanc@5            55
    y#1#10#2  balanc@2            11
    y#1#10#3  BigM_30              1
    y#1#10#3  valid_2              6
    y#1#10#3  valid_1             11
    y#1#10#3  balanc@9             6
    y#1#10#3  balanc@6            55
    y#1#10#3  balanc@3            11
    y#1#11#1  BigM_31              1
    y#1#11#1  valid_2             33
    y#1#11#1  valid_1              5
    y#1#11#1  balanc@7            33
    y#1#11#1  balanc@4            34
    y#1#11#1  balanc@1             5
    y#1#11#2  BigM_32              1
    y#1#11#2  valid_2             33
    y#1#11#2  valid_1              5
    y#1#11#2  balanc@8            33
    y#1#11#2  balanc@5            34
    y#1#11#2  balanc@2             5
    y#1#11#3  BigM_33              1
    y#1#11#3  valid_2             33
    y#1#11#3  valid_1              5
    y#1#11#3  balanc@9            33
    y#1#11#3  balanc@6            34
    y#1#11#3  balanc@3             5
    y#1#12#1  BigM_34              1
    y#1#12#1  valid_2             34
    y#1#12#1  valid_1              1
    y#1#12#1  balanc@7            34
    y#1#12#1  balanc@4            37
    y#1#12#1  balanc@1             1
    y#1#12#2  BigM_35              1
    y#1#12#2  valid_2             34
    y#1#12#2  valid_1              1
    y#1#12#2  balanc@8            34
    y#1#12#2  balanc@5            37
    y#1#12#2  balanc@2             1
    y#1#12#3  BigM_36              1
    y#1#12#3  valid_2             34
    y#1#12#3  valid_1              1
    y#1#12#3  balanc@9            34
    y#1#12#3  balanc@6            37
    y#1#12#3  balanc@3             1
    y#1#13#1  BigM_37              1
    y#1#13#1  valid_2              1
    y#1#13#1  valid_1             16
    y#1#13#1  balanc@7             1
    y#1#13#1  balanc@4            55
    y#1#13#1  balanc@1            16
    y#1#13#2  BigM_38              1
    y#1#13#2  valid_2              1
    y#1#13#2  valid_1             16
    y#1#13#2  balanc@8             1
    y#1#13#2  balanc@5            55
    y#1#13#2  balanc@2            16
    y#1#13#3  BigM_39              1
    y#1#13#3  valid_2              1
    y#1#13#3  valid_1             16
    y#1#13#3  balanc@9             1
    y#1#13#3  balanc@6            55
    y#1#13#3  balanc@3            16
    y#1#14#1  BigM_40              1
    y#1#14#1  valid_2             17
    y#1#14#1  valid_1              3
    y#1#14#1  balanc@7            17
    y#1#14#1  balanc@4            52
    y#1#14#1  balanc@1             3
    y#1#14#2  BigM_41              1
    y#1#14#2  valid_2             17
    y#1#14#2  valid_1              3
    y#1#14#2  balanc@8            17
    y#1#14#2  balanc@5            52
    y#1#14#2  balanc@2             3
    y#1#14#3  BigM_42              1
    y#1#14#3  valid_2             17
    y#1#14#3  valid_1              3
    y#1#14#3  balanc@9            17
    y#1#14#3  balanc@6            52
    y#1#14#3  balanc@3             3
    y#1#15#1  BigM_43              1
    y#1#15#1  valid_2             44
    y#1#15#1  valid_1              6
    y#1#15#1  balanc@7            44
    y#1#15#1  balanc@4            22
    y#1#15#1  balanc@1             6
    y#1#15#2  BigM_44              1
    y#1#15#2  valid_2             44
    y#1#15#2  valid_1              6
    y#1#15#2  balanc@8            44
    y#1#15#2  balanc@5            22
    y#1#15#2  balanc@2             6
    y#1#15#3  BigM_45              1
    y#1#15#3  valid_2             44
    y#1#15#3  valid_1              6
    y#1#15#3  balanc@9            44
    y#1#15#3  balanc@6            22
    y#1#15#3  balanc@3             6
    y#1#16#1  BigM_46              1
    y#1#16#1  valid_2             62
    y#1#16#1  valid_1              7
    y#1#16#1  balanc@7            62
    y#1#16#1  balanc@4             3
    y#1#16#1  balanc@1             7
    y#1#16#2  BigM_47              1
    y#1#16#2  valid_2             62
    y#1#16#2  valid_1              7
    y#1#16#2  balanc@8            62
    y#1#16#2  balanc@5             3
    y#1#16#2  balanc@2             7
    y#1#16#3  BigM_48              1
    y#1#16#3  valid_2             62
    y#1#16#3  valid_1              7
    y#1#16#3  balanc@9            62
    y#1#16#3  balanc@6             3
    y#1#16#3  balanc@3             7
    y#2#1#1   BigM_49              1
    y#2#1#1   valid_5              5
    y#2#1#1   valid_4             16
    y#2#1#1   valid_3             51
    y#2#1#1   balan@10             5
    y#2#1#1   balanc@d            16
    y#2#1#1   balanc@a            51
    y#2#1#2   BigM_50              1
    y#2#1#2   valid_5              5
    y#2#1#2   valid_4             16
    y#2#1#2   valid_3             51
    y#2#1#2   balan@11             5
    y#2#1#2   balanc@e            16
    y#2#1#2   balanc@b            51
    y#2#1#3   BigM_51              1
    y#2#1#3   valid_5              5
    y#2#1#3   valid_4             16
    y#2#1#3   valid_3             51
    y#2#1#3   balan@12             5
    y#2#1#3   balanc@f            16
    y#2#1#3   balanc@c            51
    y#2#2#1   BigM_52              1
    y#2#2#1   valid_5             46
    y#2#2#1   valid_4              7
    y#2#2#1   valid_3             19
    y#2#2#1   balan@10            46
    y#2#2#1   balanc@d             7
    y#2#2#1   balanc@a            19
    y#2#2#2   BigM_53              1
    y#2#2#2   valid_5             46
    y#2#2#2   valid_4              7
    y#2#2#2   valid_3             19
    y#2#2#2   balan@11            46
    y#2#2#2   balanc@e             7
    y#2#2#2   balanc@b            19
    y#2#2#3   BigM_54              1
    y#2#2#3   valid_5             46
    y#2#2#3   valid_4              7
    y#2#2#3   valid_3             19
    y#2#2#3   balan@12            46
    y#2#2#3   balanc@f             7
    y#2#2#3   balanc@c            19
    y#2#3#1   BigM_55              1
    y#2#3#1   valid_5             42
    y#2#3#1   valid_4             24
    y#2#3#1   valid_3              6
    y#2#3#1   balan@10            42
    y#2#3#1   balanc@d            24
    y#2#3#1   balanc@a             6
    y#2#3#2   BigM_56              1
    y#2#3#2   valid_5             42
    y#2#3#2   valid_4             24
    y#2#3#2   valid_3              6
    y#2#3#2   balan@11            42
    y#2#3#2   balanc@e            24
    y#2#3#2   balanc@b             6
    y#2#3#3   BigM_57              1
    y#2#3#3   valid_5             42
    y#2#3#3   valid_4             24
    y#2#3#3   valid_3              6
    y#2#3#3   balan@12            42
    y#2#3#3   balanc@f            24
    y#2#3#3   balanc@c             6
    y#2#4#1   BigM_58              1
    y#2#4#1   valid_5              7
    y#2#4#1   valid_4             64
    y#2#4#1   valid_3              1
    y#2#4#1   balan@10             7
    y#2#4#1   balanc@d            64
    y#2#4#1   balanc@a             1
    y#2#4#2   BigM_59              1
    y#2#4#2   valid_5              7
    y#2#4#2   valid_4             64
    y#2#4#2   valid_3              1
    y#2#4#2   balan@11             7
    y#2#4#2   balanc@e            64
    y#2#4#2   balanc@b             1
    y#2#4#3   BigM_60              1
    y#2#4#3   valid_5              7
    y#2#4#3   valid_4             64
    y#2#4#3   valid_3              1
    y#2#4#3   balan@12             7
    y#2#4#3   balanc@f            64
    y#2#4#3   balanc@c             1
    y#2#5#1   BigM_61              1
    y#2#5#1   valid_5             30
    y#2#5#1   valid_4             22
    y#2#5#1   valid_3             20
    y#2#5#1   balan@10            30
    y#2#5#1   balanc@d            22
    y#2#5#1   balanc@a            20
    y#2#5#2   BigM_62              1
    y#2#5#2   valid_5             30
    y#2#5#2   valid_4             22
    y#2#5#2   valid_3             20
    y#2#5#2   balan@11            30
    y#2#5#2   balanc@e            22
    y#2#5#2   balanc@b            20
    y#2#5#3   BigM_63              1
    y#2#5#3   valid_5             30
    y#2#5#3   valid_4             22
    y#2#5#3   valid_3             20
    y#2#5#3   balan@12            30
    y#2#5#3   balanc@f            22
    y#2#5#3   balanc@c            20
    y#2#6#1   BigM_64              1
    y#2#6#1   valid_5             36
    y#2#6#1   valid_4             18
    y#2#6#1   valid_3             18
    y#2#6#1   balan@10            36
    y#2#6#1   balanc@d            18
    y#2#6#1   balanc@a            18
    y#2#6#2   BigM_65              1
    y#2#6#2   valid_5             36
    y#2#6#2   valid_4             18
    y#2#6#2   valid_3             18
    y#2#6#2   balan@11            36
    y#2#6#2   balanc@e            18
    y#2#6#2   balanc@b            18
    y#2#6#3   BigM_66              1
    y#2#6#3   valid_5             36
    y#2#6#3   valid_4             18
    y#2#6#3   valid_3             18
    y#2#6#3   balan@12            36
    y#2#6#3   balanc@f            18
    y#2#6#3   balanc@c            18
    y#2#7#1   BigM_67              1
    y#2#7#2   BigM_68              1
    y#2#7#3   BigM_69              1
    y#2#8#1   BigM_70              1
    y#2#8#2   BigM_71              1
    y#2#8#3   BigM_72              1
    y#2#9#1   BigM_73              1
    y#2#9#1   valid_5             31
    y#2#9#1   valid_4             11
    y#2#9#1   valid_3             30
    y#2#9#1   balan@10            31
    y#2#9#1   balanc@d            11
    y#2#9#1   balanc@a            30
    y#2#9#2   BigM_74              1
    y#2#9#2   valid_5             31
    y#2#9#2   valid_4             11
    y#2#9#2   valid_3             30
    y#2#9#2   balan@11            31
    y#2#9#2   balanc@e            11
    y#2#9#2   balanc@b            30
    y#2#9#3   BigM_75              1
    y#2#9#3   valid_5             31
    y#2#9#3   valid_4             11
    y#2#9#3   valid_3             30
    y#2#9#3   balan@12            31
    y#2#9#3   balanc@f            11
    y#2#9#3   balanc@c            30
    y#2#10#1  BigM_76              1
    y#2#10#1  valid_5              6
    y#2#10#1  valid_4             55
    y#2#10#1  valid_3             11
    y#2#10#1  balan@10             6
    y#2#10#1  balanc@d            55
    y#2#10#1  balanc@a            11
    y#2#10#2  BigM_77              1
    y#2#10#2  valid_5              6
    y#2#10#2  valid_4             55
    y#2#10#2  valid_3             11
    y#2#10#2  balan@11             6
    y#2#10#2  balanc@e            55
    y#2#10#2  balanc@b            11
    y#2#10#3  BigM_78              1
    y#2#10#3  valid_5              6
    y#2#10#3  valid_4             55
    y#2#10#3  valid_3             11
    y#2#10#3  balan@12             6
    y#2#10#3  balanc@f            55
    y#2#10#3  balanc@c            11
    y#2#11#1  BigM_79              1
    y#2#11#1  valid_5             33
    y#2#11#1  valid_4             34
    y#2#11#1  valid_3              5
    y#2#11#1  balan@10            33
    y#2#11#1  balanc@d            34
    y#2#11#1  balanc@a             5
    y#2#11#2  BigM_80              1
    y#2#11#2  valid_5             33
    y#2#11#2  valid_4             34
    y#2#11#2  valid_3              5
    y#2#11#2  balan@11            33
    y#2#11#2  balanc@e            34
    y#2#11#2  balanc@b             5
    y#2#11#3  BigM_81              1
    y#2#11#3  valid_5             33
    y#2#11#3  valid_4             34
    y#2#11#3  valid_3              5
    y#2#11#3  balan@12            33
    y#2#11#3  balanc@f            34
    y#2#11#3  balanc@c             5
    y#2#12#1  BigM_82              1
    y#2#12#1  valid_5             34
    y#2#12#1  valid_4             37
    y#2#12#1  valid_3              1
    y#2#12#1  balan@10            34
    y#2#12#1  balanc@d            37
    y#2#12#1  balanc@a             1
    y#2#12#2  BigM_83              1
    y#2#12#2  valid_5             34
    y#2#12#2  valid_4             37
    y#2#12#2  valid_3              1
    y#2#12#2  balan@11            34
    y#2#12#2  balanc@e            37
    y#2#12#2  balanc@b             1
    y#2#12#3  BigM_84              1
    y#2#12#3  valid_5             34
    y#2#12#3  valid_4             37
    y#2#12#3  valid_3              1
    y#2#12#3  balan@12            34
    y#2#12#3  balanc@f            37
    y#2#12#3  balanc@c             1
    y#2#13#1  BigM_85              1
    y#2#13#1  valid_5              1
    y#2#13#1  valid_4             55
    y#2#13#1  valid_3             16
    y#2#13#1  balan@10             1
    y#2#13#1  balanc@d            55
    y#2#13#1  balanc@a            16
    y#2#13#2  BigM_86              1
    y#2#13#2  valid_5              1
    y#2#13#2  valid_4             55
    y#2#13#2  valid_3             16
    y#2#13#2  balan@11             1
    y#2#13#2  balanc@e            55
    y#2#13#2  balanc@b            16
    y#2#13#3  BigM_87              1
    y#2#13#3  valid_5              1
    y#2#13#3  valid_4             55
    y#2#13#3  valid_3             16
    y#2#13#3  balan@12             1
    y#2#13#3  balanc@f            55
    y#2#13#3  balanc@c            16
    y#2#14#1  BigM_88              1
    y#2#14#1  valid_5             17
    y#2#14#1  valid_4             52
    y#2#14#1  valid_3              3
    y#2#14#1  balan@10            17
    y#2#14#1  balanc@d            52
    y#2#14#1  balanc@a             3
    y#2#14#2  BigM_89              1
    y#2#14#2  valid_5             17
    y#2#14#2  valid_4             52
    y#2#14#2  valid_3              3
    y#2#14#2  balan@11            17
    y#2#14#2  balanc@e            52
    y#2#14#2  balanc@b             3
    y#2#14#3  BigM_90              1
    y#2#14#3  valid_5             17
    y#2#14#3  valid_4             52
    y#2#14#3  valid_3              3
    y#2#14#3  balan@12            17
    y#2#14#3  balanc@f            52
    y#2#14#3  balanc@c             3
    y#2#15#1  BigM_91              1
    y#2#15#1  valid_5             44
    y#2#15#1  valid_4             22
    y#2#15#1  valid_3              6
    y#2#15#1  balan@10            44
    y#2#15#1  balanc@d            22
    y#2#15#1  balanc@a             6
    y#2#15#2  BigM_92              1
    y#2#15#2  valid_5             44
    y#2#15#2  valid_4             22
    y#2#15#2  valid_3              6
    y#2#15#2  balan@11            44
    y#2#15#2  balanc@e            22
    y#2#15#2  balanc@b             6
    y#2#15#3  BigM_93              1
    y#2#15#3  valid_5             44
    y#2#15#3  valid_4             22
    y#2#15#3  valid_3              6
    y#2#15#3  balan@12            44
    y#2#15#3  balanc@f            22
    y#2#15#3  balanc@c             6
    y#2#16#1  BigM_94              1
    y#2#16#1  valid_5             62
    y#2#16#1  valid_4              3
    y#2#16#1  valid_3              7
    y#2#16#1  balan@10            62
    y#2#16#1  balanc@d             3
    y#2#16#1  balanc@a             7
    y#2#16#2  BigM_95              1
    y#2#16#2  valid_5             62
    y#2#16#2  valid_4              3
    y#2#16#2  valid_3              7
    y#2#16#2  balan@11            62
    y#2#16#2  balanc@e             3
    y#2#16#2  balanc@b             7
    y#2#16#3  BigM_96              1
    y#2#16#3  valid_5             62
    y#2#16#3  valid_4              3
    y#2#16#3  valid_3              7
    y#2#16#3  balan@12            62
    y#2#16#3  balanc@f             3
    y#2#16#3  balanc@c             7
    y#3#1#1   BigM_97              1
    y#3#1#1   valid_8              5
    y#3#1#1   valid_7             16
    y#3#1#1   valid_6             51
    y#3#1#1   balan@19             5
    y#3#1#1   balan@16            16
    y#3#1#1   balan@13            51
    y#3#1#2   BigM_98              1
    y#3#1#2   valid_8              5
    y#3#1#2   valid_7             16
    y#3#1#2   valid_6             51
    y#3#1#2   balan@1a             5
    y#3#1#2   balan@17            16
    y#3#1#2   balan@14            51
    y#3#1#3   BigM_99              1
    y#3#1#3   valid_8              5
    y#3#1#3   valid_7             16
    y#3#1#3   valid_6             51
    y#3#1#3   balan@1b             5
    y#3#1#3   balan@18            16
    y#3#1#3   balan@15            51
    y#3#2#1   BigM_100             1
    y#3#2#1   valid_8             46
    y#3#2#1   valid_7              7
    y#3#2#1   valid_6             19
    y#3#2#1   balan@19            46
    y#3#2#1   balan@16             7
    y#3#2#1   balan@13            19
    y#3#2#2   BigM_101             1
    y#3#2#2   valid_8             46
    y#3#2#2   valid_7              7
    y#3#2#2   valid_6             19
    y#3#2#2   balan@1a            46
    y#3#2#2   balan@17             7
    y#3#2#2   balan@14            19
    y#3#2#3   BigM_102             1
    y#3#2#3   valid_8             46
    y#3#2#3   valid_7              7
    y#3#2#3   valid_6             19
    y#3#2#3   balan@1b            46
    y#3#2#3   balan@18             7
    y#3#2#3   balan@15            19
    y#3#3#1   BigM_103             1
    y#3#3#1   valid_8             42
    y#3#3#1   valid_7             24
    y#3#3#1   valid_6              6
    y#3#3#1   balan@19            42
    y#3#3#1   balan@16            24
    y#3#3#1   balan@13             6
    y#3#3#2   BigM_104             1
    y#3#3#2   valid_8             42
    y#3#3#2   valid_7             24
    y#3#3#2   valid_6              6
    y#3#3#2   balan@1a            42
    y#3#3#2   balan@17            24
    y#3#3#2   balan@14             6
    y#3#3#3   BigM_105             1
    y#3#3#3   valid_8             42
    y#3#3#3   valid_7             24
    y#3#3#3   valid_6              6
    y#3#3#3   balan@1b            42
    y#3#3#3   balan@18            24
    y#3#3#3   balan@15             6
    y#3#4#1   BigM_106             1
    y#3#4#1   valid_8              7
    y#3#4#1   valid_7             64
    y#3#4#1   valid_6              1
    y#3#4#1   balan@19             7
    y#3#4#1   balan@16            64
    y#3#4#1   balan@13             1
    y#3#4#2   BigM_107             1
    y#3#4#2   valid_8              7
    y#3#4#2   valid_7             64
    y#3#4#2   valid_6              1
    y#3#4#2   balan@1a             7
    y#3#4#2   balan@17            64
    y#3#4#2   balan@14             1
    y#3#4#3   BigM_108             1
    y#3#4#3   valid_8              7
    y#3#4#3   valid_7             64
    y#3#4#3   valid_6              1
    y#3#4#3   balan@1b             7
    y#3#4#3   balan@18            64
    y#3#4#3   balan@15             1
    y#3#5#1   BigM_109             1
    y#3#5#1   valid_8             30
    y#3#5#1   valid_7             22
    y#3#5#1   valid_6             20
    y#3#5#1   balan@19            30
    y#3#5#1   balan@16            22
    y#3#5#1   balan@13            20
    y#3#5#2   BigM_110             1
    y#3#5#2   valid_8             30
    y#3#5#2   valid_7             22
    y#3#5#2   valid_6             20
    y#3#5#2   balan@1a            30
    y#3#5#2   balan@17            22
    y#3#5#2   balan@14            20
    y#3#5#3   BigM_111             1
    y#3#5#3   valid_8             30
    y#3#5#3   valid_7             22
    y#3#5#3   valid_6             20
    y#3#5#3   balan@1b            30
    y#3#5#3   balan@18            22
    y#3#5#3   balan@15            20
    y#3#6#1   BigM_112             1
    y#3#6#1   valid_8             36
    y#3#6#1   valid_7             18
    y#3#6#1   valid_6             18
    y#3#6#1   balan@19            36
    y#3#6#1   balan@16            18
    y#3#6#1   balan@13            18
    y#3#6#2   BigM_113             1
    y#3#6#2   valid_8             36
    y#3#6#2   valid_7             18
    y#3#6#2   valid_6             18
    y#3#6#2   balan@1a            36
    y#3#6#2   balan@17            18
    y#3#6#2   balan@14            18
    y#3#6#3   BigM_114             1
    y#3#6#3   valid_8             36
    y#3#6#3   valid_7             18
    y#3#6#3   valid_6             18
    y#3#6#3   balan@1b            36
    y#3#6#3   balan@18            18
    y#3#6#3   balan@15            18
    y#3#7#1   BigM_115             1
    y#3#7#2   BigM_116             1
    y#3#7#3   BigM_117             1
    y#3#8#1   BigM_118             1
    y#3#8#2   BigM_119             1
    y#3#8#3   BigM_120             1
    y#3#9#1   BigM_121             1
    y#3#9#1   valid_8             31
    y#3#9#1   valid_7             11
    y#3#9#1   valid_6             30
    y#3#9#1   balan@19            31
    y#3#9#1   balan@16            11
    y#3#9#1   balan@13            30
    y#3#9#2   BigM_122             1
    y#3#9#2   valid_8             31
    y#3#9#2   valid_7             11
    y#3#9#2   valid_6             30
    y#3#9#2   balan@1a            31
    y#3#9#2   balan@17            11
    y#3#9#2   balan@14            30
    y#3#9#3   BigM_123             1
    y#3#9#3   valid_8             31
    y#3#9#3   valid_7             11
    y#3#9#3   valid_6             30
    y#3#9#3   balan@1b            31
    y#3#9#3   balan@18            11
    y#3#9#3   balan@15            30
    y#3#10#1  BigM_124             1
    y#3#10#1  valid_8              6
    y#3#10#1  valid_7             55
    y#3#10#1  valid_6             11
    y#3#10#1  balan@19             6
    y#3#10#1  balan@16            55
    y#3#10#1  balan@13            11
    y#3#10#2  BigM_125             1
    y#3#10#2  valid_8              6
    y#3#10#2  valid_7             55
    y#3#10#2  valid_6             11
    y#3#10#2  balan@1a             6
    y#3#10#2  balan@17            55
    y#3#10#2  balan@14            11
    y#3#10#3  BigM_126             1
    y#3#10#3  valid_8              6
    y#3#10#3  valid_7             55
    y#3#10#3  valid_6             11
    y#3#10#3  balan@1b             6
    y#3#10#3  balan@18            55
    y#3#10#3  balan@15            11
    y#3#11#1  BigM_127             1
    y#3#11#1  valid_8             33
    y#3#11#1  valid_7             34
    y#3#11#1  valid_6              5
    y#3#11#1  balan@19            33
    y#3#11#1  balan@16            34
    y#3#11#1  balan@13             5
    y#3#11#2  BigM_128             1
    y#3#11#2  valid_8             33
    y#3#11#2  valid_7             34
    y#3#11#2  valid_6              5
    y#3#11#2  balan@1a            33
    y#3#11#2  balan@17            34
    y#3#11#2  balan@14             5
    y#3#11#3  BigM_129             1
    y#3#11#3  valid_8             33
    y#3#11#3  valid_7             34
    y#3#11#3  valid_6              5
    y#3#11#3  balan@1b            33
    y#3#11#3  balan@18            34
    y#3#11#3  balan@15             5
    y#3#12#1  BigM_130             1
    y#3#12#1  valid_8             34
    y#3#12#1  valid_7             37
    y#3#12#1  valid_6              1
    y#3#12#1  balan@19            34
    y#3#12#1  balan@16            37
    y#3#12#1  balan@13             1
    y#3#12#2  BigM_131             1
    y#3#12#2  valid_8             34
    y#3#12#2  valid_7             37
    y#3#12#2  valid_6              1
    y#3#12#2  balan@1a            34
    y#3#12#2  balan@17            37
    y#3#12#2  balan@14             1
    y#3#12#3  BigM_132             1
    y#3#12#3  valid_8             34
    y#3#12#3  valid_7             37
    y#3#12#3  valid_6              1
    y#3#12#3  balan@1b            34
    y#3#12#3  balan@18            37
    y#3#12#3  balan@15             1
    y#3#13#1  BigM_133             1
    y#3#13#1  valid_8              1
    y#3#13#1  valid_7             55
    y#3#13#1  valid_6             16
    y#3#13#1  balan@19             1
    y#3#13#1  balan@16            55
    y#3#13#1  balan@13            16
    y#3#13#2  BigM_134             1
    y#3#13#2  valid_8              1
    y#3#13#2  valid_7             55
    y#3#13#2  valid_6             16
    y#3#13#2  balan@1a             1
    y#3#13#2  balan@17            55
    y#3#13#2  balan@14            16
    y#3#13#3  BigM_135             1
    y#3#13#3  valid_8              1
    y#3#13#3  valid_7             55
    y#3#13#3  valid_6             16
    y#3#13#3  balan@1b             1
    y#3#13#3  balan@18            55
    y#3#13#3  balan@15            16
    y#3#14#1  BigM_136             1
    y#3#14#1  valid_8             17
    y#3#14#1  valid_7             52
    y#3#14#1  valid_6              3
    y#3#14#1  balan@19            17
    y#3#14#1  balan@16            52
    y#3#14#1  balan@13             3
    y#3#14#2  BigM_137             1
    y#3#14#2  valid_8             17
    y#3#14#2  valid_7             52
    y#3#14#2  valid_6              3
    y#3#14#2  balan@1a            17
    y#3#14#2  balan@17            52
    y#3#14#2  balan@14             3
    y#3#14#3  BigM_138             1
    y#3#14#3  valid_8             17
    y#3#14#3  valid_7             52
    y#3#14#3  valid_6              3
    y#3#14#3  balan@1b            17
    y#3#14#3  balan@18            52
    y#3#14#3  balan@15             3
    y#3#15#1  BigM_139             1
    y#3#15#1  valid_8             44
    y#3#15#1  valid_7             22
    y#3#15#1  valid_6              6
    y#3#15#1  balan@19            44
    y#3#15#1  balan@16            22
    y#3#15#1  balan@13             6
    y#3#15#2  BigM_140             1
    y#3#15#2  valid_8             44
    y#3#15#2  valid_7             22
    y#3#15#2  valid_6              6
    y#3#15#2  balan@1a            44
    y#3#15#2  balan@17            22
    y#3#15#2  balan@14             6
    y#3#15#3  BigM_141             1
    y#3#15#3  valid_8             44
    y#3#15#3  valid_7             22
    y#3#15#3  valid_6              6
    y#3#15#3  balan@1b            44
    y#3#15#3  balan@18            22
    y#3#15#3  balan@15             6
    y#3#16#1  BigM_142             1
    y#3#16#1  valid_8             62
    y#3#16#1  valid_7              3
    y#3#16#1  valid_6              7
    y#3#16#1  balan@19            62
    y#3#16#1  balan@16             3
    y#3#16#1  balan@13             7
    y#3#16#2  BigM_143             1
    y#3#16#2  valid_8             62
    y#3#16#2  valid_7              3
    y#3#16#2  valid_6              7
    y#3#16#2  balan@1a            62
    y#3#16#2  balan@17             3
    y#3#16#2  balan@14             7
    y#3#16#3  BigM_144             1
    y#3#16#3  valid_8             62
    y#3#16#3  valid_7              3
    y#3#16#3  valid_6              7
    y#3#16#3  balan@1b            62
    y#3#16#3  balan@18             3
    y#3#16#3  balan@15             7
    p#1       BigM_99          -1000
    p#1       BigM_98          -1000
    p#1       BigM_97          -1000
    p#1       BigM_51          -1000
    p#1       BigM_50          -1000
    p#1       BigM_49          -1000
    p#1       BigM_3           -1000
    p#1       BigM_2           -1000
    p#1       BigM_1           -1000
    p#1       select_1             1
    p#2       BigM_102         -1000
    p#2       BigM_101         -1000
    p#2       BigM_100         -1000
    p#2       BigM_54          -1000
    p#2       BigM_53          -1000
    p#2       BigM_52          -1000
    p#2       BigM_6           -1000
    p#2       BigM_5           -1000
    p#2       BigM_4           -1000
    p#2       select_1             1
    p#3       BigM_105         -1000
    p#3       BigM_104         -1000
    p#3       BigM_103         -1000
    p#3       BigM_57          -1000
    p#3       BigM_56          -1000
    p#3       BigM_55          -1000
    p#3       BigM_9           -1000
    p#3       BigM_8           -1000
    p#3       BigM_7           -1000
    p#3       select_1             1
    p#4       BigM_108         -1000
    p#4       BigM_107         -1000
    p#4       BigM_106         -1000
    p#4       BigM_60          -1000
    p#4       BigM_59          -1000
    p#4       BigM_58          -1000
    p#4       BigM_12          -1000
    p#4       BigM_11          -1000
    p#4       BigM_10          -1000
    p#4       select_1             1
    p#5       BigM_111         -1000
    p#5       BigM_110         -1000
    p#5       BigM_109         -1000
    p#5       BigM_63          -1000
    p#5       BigM_62          -1000
    p#5       BigM_61          -1000
    p#5       BigM_15          -1000
    p#5       BigM_14          -1000
    p#5       BigM_13          -1000
    p#5       select_1             1
    p#6       BigM_114         -1000
    p#6       BigM_113         -1000
    p#6       BigM_112         -1000
    p#6       BigM_66          -1000
    p#6       BigM_65          -1000
    p#6       BigM_64          -1000
    p#6       BigM_18          -1000
    p#6       BigM_17          -1000
    p#6       BigM_16          -1000
    p#6       select_1             1
    p#7       BigM_117         -1000
    p#7       BigM_116         -1000
    p#7       BigM_115         -1000
    p#7       BigM_69          -1000
    p#7       BigM_68          -1000
    p#7       BigM_67          -1000
    p#7       BigM_21          -1000
    p#7       BigM_20          -1000
    p#7       BigM_19          -1000
    p#7       select_1             1
    p#8       BigM_120         -1000
    p#8       BigM_119         -1000
    p#8       BigM_118         -1000
    p#8       BigM_72          -1000
    p#8       BigM_71          -1000
    p#8       BigM_70          -1000
    p#8       BigM_24          -1000
    p#8       BigM_23          -1000
    p#8       BigM_22          -1000
    p#8       select_1             1
    p#9       BigM_123         -1000
    p#9       BigM_122         -1000
    p#9       BigM_121         -1000
    p#9       BigM_75          -1000
    p#9       BigM_74          -1000
    p#9       BigM_73          -1000
    p#9       BigM_27          -1000
    p#9       BigM_26          -1000
    p#9       BigM_25          -1000
    p#9       select_1             1
    p#10      BigM_126         -1000
    p#10      BigM_125         -1000
    p#10      BigM_124         -1000
    p#10      BigM_78          -1000
    p#10      BigM_77          -1000
    p#10      BigM_76          -1000
    p#10      BigM_30          -1000
    p#10      BigM_29          -1000
    p#10      BigM_28          -1000
    p#10      select_1             1
    p#11      BigM_129         -1000
    p#11      BigM_128         -1000
    p#11      BigM_127         -1000
    p#11      BigM_81          -1000
    p#11      BigM_80          -1000
    p#11      BigM_79          -1000
    p#11      BigM_33          -1000
    p#11      BigM_32          -1000
    p#11      BigM_31          -1000
    p#11      select_1             1
    p#12      BigM_132         -1000
    p#12      BigM_131         -1000
    p#12      BigM_130         -1000
    p#12      BigM_84          -1000
    p#12      BigM_83          -1000
    p#12      BigM_82          -1000
    p#12      BigM_36          -1000
    p#12      BigM_35          -1000
    p#12      BigM_34          -1000
    p#12      select_1             1
    p#13      BigM_135         -1000
    p#13      BigM_134         -1000
    p#13      BigM_133         -1000
    p#13      BigM_87          -1000
    p#13      BigM_86          -1000
    p#13      BigM_85          -1000
    p#13      BigM_39          -1000
    p#13      BigM_38          -1000
    p#13      BigM_37          -1000
    p#13      select_1             1
    p#14      BigM_138         -1000
    p#14      BigM_137         -1000
    p#14      BigM_136         -1000
    p#14      BigM_90          -1000
    p#14      BigM_89          -1000
    p#14      BigM_88          -1000
    p#14      BigM_42          -1000
    p#14      BigM_41          -1000
    p#14      BigM_40          -1000
    p#14      select_1             1
    p#15      BigM_141         -1000
    p#15      BigM_140         -1000
    p#15      BigM_139         -1000
    p#15      BigM_93          -1000
    p#15      BigM_92          -1000
    p#15      BigM_91          -1000
    p#15      BigM_45          -1000
    p#15      BigM_44          -1000
    p#15      BigM_43          -1000
    p#15      select_1             1
    p#16      BigM_144         -1000
    p#16      BigM_143         -1000
    p#16      BigM_142         -1000
    p#16      BigM_96          -1000
    p#16      BigM_95          -1000
    p#16      BigM_94          -1000
    p#16      BigM_48          -1000
    p#16      BigM_47          -1000
    p#16      BigM_46          -1000
    p#16      select_1             1
    MARK0001  'MARKER'                 'INTEND'
    B#1#1#0   init2_1              1
    B#1#1#0   balanc@1            -1
    B#1#1#1   OBJECTIV             5
    B#1#1#1   balanc@2            -1
    B#1#1#1   balanc@1             1
    B#1#1#2   OBJECTIV             5
    B#1#1#2   balanc@3            -1
    B#1#1#2   balanc@2             1
    B#1#1#3   OBJECTIV             5
    B#1#1#3   init3_1              1
    B#1#1#3   balanc@3             1
    B#1#2#0   init2_2              1
    B#1#2#0   balanc@4            -1
    B#1#2#1   OBJECTIV           5.5
    B#1#2#1   balanc@5            -1
    B#1#2#1   balanc@4             1
    B#1#2#2   OBJECTIV           5.5
    B#1#2#2   balanc@6            -1
    B#1#2#2   balanc@5             1
    B#1#2#3   OBJECTIV           5.5
    B#1#2#3   init3_2              1
    B#1#2#3   balanc@6             1
    B#1#3#0   init2_3              1
    B#1#3#0   balanc@7            -1
    B#1#3#1   OBJECTIV           5.5
    B#1#3#1   balanc@8            -1
    B#1#3#1   balanc@7             1
    B#1#3#2   OBJECTIV           5.5
    B#1#3#2   balanc@9            -1
    B#1#3#2   balanc@8             1
    B#1#3#3   OBJECTIV           5.5
    B#1#3#3   init3_3              1
    B#1#3#3   balanc@9             1
    B#2#1#0   init2_4              1
    B#2#1#0   balanc@a            -1
    B#2#1#1   OBJECTIV             5
    B#2#1#1   balanc@b            -1
    B#2#1#1   balanc@a             1
    B#2#1#2   OBJECTIV             5
    B#2#1#2   balanc@c            -1
    B#2#1#2   balanc@b             1
    B#2#1#3   OBJECTIV             5
    B#2#1#3   init3_4              1
    B#2#1#3   balanc@c             1
    B#2#2#0   init2_5              1
    B#2#2#0   balanc@d            -1
    B#2#2#1   OBJECTIV           5.5
    B#2#2#1   balanc@e            -1
    B#2#2#1   balanc@d             1
    B#2#2#2   OBJECTIV           5.5
    B#2#2#2   balanc@f            -1
    B#2#2#2   balanc@e             1
    B#2#2#3   OBJECTIV           5.5
    B#2#2#3   init3_5              1
    B#2#2#3   balanc@f             1
    B#2#3#0   init2_6              1
    B#2#3#0   balan@10            -1
    B#2#3#1   OBJECTIV           5.5
    B#2#3#1   balan@11            -1
    B#2#3#1   balan@10             1
    B#2#3#2   OBJECTIV           5.5
    B#2#3#2   balan@12            -1
    B#2#3#2   balan@11             1
    B#2#3#3   OBJECTIV           5.5
    B#2#3#3   init3_6              1
    B#2#3#3   balan@12             1
    B#3#1#0   init2_7              1
    B#3#1#0   balan@13            -1
    B#3#1#1   OBJECTIV             5
    B#3#1#1   balan@14            -1
    B#3#1#1   balan@13             1
    B#3#1#2   OBJECTIV             5
    B#3#1#2   balan@15            -1
    B#3#1#2   balan@14             1
    B#3#1#3   OBJECTIV             5
    B#3#1#3   init3_7              1
    B#3#1#3   balan@15             1
    B#3#2#0   init2_8              1
    B#3#2#0   balan@16            -1
    B#3#2#1   OBJECTIV           5.5
    B#3#2#1   balan@17            -1
    B#3#2#1   balan@16             1
    B#3#2#2   OBJECTIV           5.5
    B#3#2#2   balan@18            -1
    B#3#2#2   balan@17             1
    B#3#2#3   OBJECTIV           5.5
    B#3#2#3   init3_8              1
    B#3#2#3   balan@18             1
    B#3#3#0   init2_9              1
    B#3#3#0   balan@19            -1
    B#3#3#1   OBJECTIV           5.5
    B#3#3#1   balan@1a            -1
    B#3#3#1   balan@19             1
    B#3#3#2   OBJECTIV           5.5
    B#3#3#2   balan@1b            -1
    B#3#3#2   balan@1a             1
    B#3#3#3   OBJECTIV           5.5
    B#3#3#3   init3_9              1
    B#3#3#3   balan@1b             1
    I#1#1#0   init1_1              1
    I#1#1#0   balanc@1             1
    I#1#1#1   OBJECTIV             1
    I#1#1#1   balanc@2             1
    I#1#1#1   balanc@1            -1
    I#1#1#2   OBJECTIV             1
    I#1#1#2   balanc@3             1
    I#1#1#2   balanc@2            -1
    I#1#1#3   OBJECTIV             1
    I#1#1#3   balanc@3            -1
    I#1#2#0   init1_2              1
    I#1#2#0   balanc@4             1
    I#1#2#1   OBJECTIV           1.1
    I#1#2#1   balanc@5             1
    I#1#2#1   balanc@4            -1
    I#1#2#2   OBJECTIV           1.1
    I#1#2#2   balanc@6             1
    I#1#2#2   balanc@5            -1
    I#1#2#3   OBJECTIV           1.1
    I#1#2#3   balanc@6            -1
    I#1#3#0   init1_3              1
    I#1#3#0   balanc@7             1
    I#1#3#1   OBJECTIV           1.1
    I#1#3#1   balanc@8             1
    I#1#3#1   balanc@7            -1
    I#1#3#2   OBJECTIV           1.1
    I#1#3#2   balanc@9             1
    I#1#3#2   balanc@8            -1
    I#1#3#3   OBJECTIV           1.1
    I#1#3#3   balanc@9            -1
    I#2#1#0   init1_4              1
    I#2#1#0   balanc@a             1
    I#2#1#1   OBJECTIV             1
    I#2#1#1   balanc@b             1
    I#2#1#1   balanc@a            -1
    I#2#1#2   OBJECTIV             1
    I#2#1#2   balanc@c             1
    I#2#1#2   balanc@b            -1
    I#2#1#3   OBJECTIV             1
    I#2#1#3   balanc@c            -1
    I#2#2#0   init1_5              1
    I#2#2#0   balanc@d             1
    I#2#2#1   OBJECTIV           1.1
    I#2#2#1   balanc@e             1
    I#2#2#1   balanc@d            -1
    I#2#2#2   OBJECTIV           1.1
    I#2#2#2   balanc@f             1
    I#2#2#2   balanc@e            -1
    I#2#2#3   OBJECTIV           1.1
    I#2#2#3   balanc@f            -1
    I#2#3#0   init1_6              1
    I#2#3#0   balan@10             1
    I#2#3#1   OBJECTIV           1.1
    I#2#3#1   balan@11             1
    I#2#3#1   balan@10            -1
    I#2#3#2   OBJECTIV           1.1
    I#2#3#2   balan@12             1
    I#2#3#2   balan@11            -1
    I#2#3#3   OBJECTIV           1.1
    I#2#3#3   balan@12            -1
    I#3#1#0   init1_7              1
    I#3#1#0   balan@13             1
    I#3#1#1   OBJECTIV             1
    I#3#1#1   balan@14             1
    I#3#1#1   balan@13            -1
    I#3#1#2   OBJECTIV             1
    I#3#1#2   balan@15             1
    I#3#1#2   balan@14            -1
    I#3#1#3   OBJECTIV             1
    I#3#1#3   balan@15            -1
    I#3#2#0   init1_8              1
    I#3#2#0   balan@16             1
    I#3#2#1   OBJECTIV           1.1
    I#3#2#1   balan@17             1
    I#3#2#1   balan@16            -1
    I#3#2#2   OBJECTIV           1.1
    I#3#2#2   balan@18             1
    I#3#2#2   balan@17            -1
    I#3#2#3   OBJECTIV           1.1
    I#3#2#3   balan@18            -1
    I#3#3#0   init1_9              1
    I#3#3#0   balan@19             1
    I#3#3#1   OBJECTIV           1.1
    I#3#3#1   balan@1a             1
    I#3#3#1   balan@19            -1
    I#3#3#2   OBJECTIV           1.1
    I#3#3#2   balan@1b             1
    I#3#3#2   balan@1a            -1
    I#3#3#3   OBJECTIV           1.1
    I#3#3#3   balan@1b            -1
RHS
    RHS       select_1             1
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@7           371
    RHS       balanc@8           573
    RHS       balanc@9           153
    RHS       balanc@a           333
    RHS       balanc@b           776
    RHS       balanc@c           466
    RHS       balanc@d           239
    RHS       balanc@e           425
    RHS       balanc@f           220
    RHS       balan@10           852
    RHS       balan@11            50
    RHS       balan@12           791
    RHS       balan@13           136
    RHS       balan@14           621
    RHS       balan@15           192
    RHS       balan@16             7
    RHS       balan@17            27
    RHS       balan@18           934
    RHS       balan@19          1000
    RHS       balan@1a           237
    RHS       balan@1b           292
    RHS       valid_1           1322
    RHS       valid_2           1097
    RHS       valid_3           1575
    RHS       valid_4            884
    RHS       valid_5           1693
    RHS       valid_6            949
    RHS       valid_7            968
    RHS       valid_8           1529
BOUNDS
 LO BOUND     B#1#1#0              0
 PL BOUND     B#1#1#0 
 LO BOUND     B#1#1#1              0
 PL BOUND     B#1#1#1 
 LO BOUND     B#1#1#2              0
 PL BOUND     B#1#1#2 
 LO BOUND     B#1#1#3              0
 PL BOUND     B#1#1#3 
 LO BOUND     B#1#2#0              0
 PL BOUND     B#1#2#0 
 LO BOUND     B#1#2#1              0
 PL BOUND     B#1#2#1 
 LO BOUND     B#1#2#2              0
 PL BOUND     B#1#2#2 
 LO BOUND     B#1#2#3              0
 PL BOUND     B#1#2#3 
 LO BOUND     B#1#3#0              0
 PL BOUND     B#1#3#0 
 LO BOUND     B#1#3#1              0
 PL BOUND     B#1#3#1 
 LO BOUND     B#1#3#2              0
 PL BOUND     B#1#3#2 
 LO BOUND     B#1#3#3              0
 PL BOUND     B#1#3#3 
 LO BOUND     B#2#1#0              0
 PL BOUND     B#2#1#0 
 LO BOUND     B#2#1#1              0
 PL BOUND     B#2#1#1 
 LO BOUND     B#2#1#2              0
 PL BOUND     B#2#1#2 
 LO BOUND     B#2#1#3              0
 PL BOUND     B#2#1#3 
 LO BOUND     B#2#2#0              0
 PL BOUND     B#2#2#0 
 LO BOUND     B#2#2#1              0
 PL BOUND     B#2#2#1 
 LO BOUND     B#2#2#2              0
 PL BOUND     B#2#2#2 
 LO BOUND     B#2#2#3              0
 PL BOUND     B#2#2#3 
 LO BOUND     B#2#3#0              0
 PL BOUND     B#2#3#0 
 LO BOUND     B#2#3#1              0
 PL BOUND     B#2#3#1 
 LO BOUND     B#2#3#2              0
 PL BOUND     B#2#3#2 
 LO BOUND     B#2#3#3              0
 PL BOUND     B#2#3#3 
 LO BOUND     B#3#1#0              0
 PL BOUND     B#3#1#0 
 LO BOUND     B#3#1#1              0
 PL BOUND     B#3#1#1 
 LO BOUND     B#3#1#2              0
 PL BOUND     B#3#1#2 
 LO BOUND     B#3#1#3              0
 PL BOUND     B#3#1#3 
 LO BOUND     B#3#2#0              0
 PL BOUND     B#3#2#0 
 LO BOUND     B#3#2#1              0
 PL BOUND     B#3#2#1 
 LO BOUND     B#3#2#2              0
 PL BOUND     B#3#2#2 
 LO BOUND     B#3#2#3              0
 PL BOUND     B#3#2#3 
 LO BOUND     B#3#3#0              0
 PL BOUND     B#3#3#0 
 LO BOUND     B#3#3#1              0
 PL BOUND     B#3#3#1 
 LO BOUND     B#3#3#2              0
 PL BOUND     B#3#3#2 
 LO BOUND     B#3#3#3              0
 PL BOUND     B#3#3#3 
 LO BOUND     I#1#1#0              0
 PL BOUND     I#1#1#0 
 LO BOUND     I#1#1#1              0
 PL BOUND     I#1#1#1 
 LO BOUND     I#1#1#2              0
 PL BOUND     I#1#1#2 
 LO BOUND     I#1#1#3              0
 PL BOUND     I#1#1#3 
 LO BOUND     I#1#2#0              0
 PL BOUND     I#1#2#0 
 LO BOUND     I#1#2#1              0
 PL BOUND     I#1#2#1 
 LO BOUND     I#1#2#2              0
 PL BOUND     I#1#2#2 
 LO BOUND     I#1#2#3              0
 PL BOUND     I#1#2#3 
 LO BOUND     I#1#3#0              0
 PL BOUND     I#1#3#0 
 LO BOUND     I#1#3#1              0
 PL BOUND     I#1#3#1 
 LO BOUND     I#1#3#2              0
 PL BOUND     I#1#3#2 
 LO BOUND     I#1#3#3              0
 PL BOUND     I#1#3#3 
 LO BOUND     I#2#1#0              0
 PL BOUND     I#2#1#0 
 LO BOUND     I#2#1#1              0
 PL BOUND     I#2#1#1 
 LO BOUND     I#2#1#2              0
 PL BOUND     I#2#1#2 
 LO BOUND     I#2#1#3              0
 PL BOUND     I#2#1#3 
 LO BOUND     I#2#2#0              0
 PL BOUND     I#2#2#0 
 LO BOUND     I#2#2#1              0
 PL BOUND     I#2#2#1 
 LO BOUND     I#2#2#2              0
 PL BOUND     I#2#2#2 
 LO BOUND     I#2#2#3              0
 PL BOUND     I#2#2#3 
 LO BOUND     I#2#3#0              0
 PL BOUND     I#2#3#0 
 LO BOUND     I#2#3#1              0
 PL BOUND     I#2#3#1 
 LO BOUND     I#2#3#2              0
 PL BOUND     I#2#3#2 
 LO BOUND     I#2#3#3              0
 PL BOUND     I#2#3#3 
 LO BOUND     I#3#1#0              0
 PL BOUND     I#3#1#0 
 LO BOUND     I#3#1#1              0
 PL BOUND     I#3#1#1 
 LO BOUND     I#3#1#2              0
 PL BOUND     I#3#1#2 
 LO BOUND     I#3#1#3              0
 PL BOUND     I#3#1#3 
 LO BOUND     I#3#2#0              0
 PL BOUND     I#3#2#0 
 LO BOUND     I#3#2#1              0
 PL BOUND     I#3#2#1 
 LO BOUND     I#3#2#2              0
 PL BOUND     I#3#2#2 
 LO BOUND     I#3#2#3              0
 PL BOUND     I#3#2#3 
 LO BOUND     I#3#3#0              0
 PL BOUND     I#3#3#0 
 LO BOUND     I#3#3#1              0
 PL BOUND     I#3#3#1 
 LO BOUND     I#3#3#2              0
 PL BOUND     I#3#3#2 
 LO BOUND     I#3#3#3              0
 PL BOUND     I#3#3#3 
 LO BOUND     f#1#1#1              0
 PL BOUND     f#1#1#1 
 LO BOUND     f#1#1#2              0
 PL BOUND     f#1#1#2 
 LO BOUND     f#1#1#3              0
 PL BOUND     f#1#1#3 
 LO BOUND     f#1#2#1              0
 PL BOUND     f#1#2#1 
 LO BOUND     f#1#2#2              0
 PL BOUND     f#1#2#2 
 LO BOUND     f#1#2#3              0
 PL BOUND     f#1#2#3 
 LO BOUND     f#1#3#1              0
 PL BOUND     f#1#3#1 
 LO BOUND     f#1#3#2              0
 PL BOUND     f#1#3#2 
 LO BOUND     f#1#3#3              0
 PL BOUND     f#1#3#3 
 LO BOUND     f#2#1#1              0
 PL BOUND     f#2#1#1 
 LO BOUND     f#2#1#2              0
 PL BOUND     f#2#1#2 
 LO BOUND     f#2#1#3              0
 PL BOUND     f#2#1#3 
 LO BOUND     f#2#2#1              0
 PL BOUND     f#2#2#1 
 LO BOUND     f#2#2#2              0
 PL BOUND     f#2#2#2 
 LO BOUND     f#2#2#3              0
 PL BOUND     f#2#2#3 
 LO BOUND     f#2#3#1              0
 PL BOUND     f#2#3#1 
 LO BOUND     f#2#3#2              0
 PL BOUND     f#2#3#2 
 LO BOUND     f#2#3#3              0
 PL BOUND     f#2#3#3 
 LO BOUND     f#3#1#1              0
 PL BOUND     f#3#1#1 
 LO BOUND     f#3#1#2              0
 PL BOUND     f#3#1#2 
 LO BOUND     f#3#1#3              0
 PL BOUND     f#3#1#3 
 LO BOUND     f#3#2#1              0
 PL BOUND     f#3#2#1 
 LO BOUND     f#3#2#2              0
 PL BOUND     f#3#2#2 
 LO BOUND     f#3#2#3              0
 PL BOUND     f#3#2#3 
 LO BOUND     f#3#3#1              0
 PL BOUND     f#3#3#1 
 LO BOUND     f#3#3#2              0
 PL BOUND     f#3#3#2 
 LO BOUND     f#3#3#3              0
 PL BOUND     f#3#3#3 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#6#1              0
 PL BOUND     y#1#6#1 
 LO BOUND     y#1#6#2              0
 PL BOUND     y#1#6#2 
 LO BOUND     y#1#6#3              0
 PL BOUND     y#1#6#3 
 LO BOUND     y#1#7#1              0
 PL BOUND     y#1#7#1 
 LO BOUND     y#1#7#2              0
 PL BOUND     y#1#7#2 
 LO BOUND     y#1#7#3              0
 PL BOUND     y#1#7#3 
 LO BOUND     y#1#8#1              0
 PL BOUND     y#1#8#1 
 LO BOUND     y#1#8#2              0
 PL BOUND     y#1#8#2 
 LO BOUND     y#1#8#3              0
 PL BOUND     y#1#8#3 
 LO BOUND     y#1#9#1              0
 PL BOUND     y#1#9#1 
 LO BOUND     y#1#9#2              0
 PL BOUND     y#1#9#2 
 LO BOUND     y#1#9#3              0
 PL BOUND     y#1#9#3 
 LO BOUND     y#1#10#1             0
 PL BOUND     y#1#10#1
 LO BOUND     y#1#10#2             0
 PL BOUND     y#1#10#2
 LO BOUND     y#1#10#3             0
 PL BOUND     y#1#10#3
 LO BOUND     y#1#11#1             0
 PL BOUND     y#1#11#1
 LO BOUND     y#1#11#2             0
 PL BOUND     y#1#11#2
 LO BOUND     y#1#11#3             0
 PL BOUND     y#1#11#3
 LO BOUND     y#1#12#1             0
 PL BOUND     y#1#12#1
 LO BOUND     y#1#12#2             0
 PL BOUND     y#1#12#2
 LO BOUND     y#1#12#3             0
 PL BOUND     y#1#12#3
 LO BOUND     y#1#13#1             0
 PL BOUND     y#1#13#1
 LO BOUND     y#1#13#2             0
 PL BOUND     y#1#13#2
 LO BOUND     y#1#13#3             0
 PL BOUND     y#1#13#3
 LO BOUND     y#1#14#1             0
 PL BOUND     y#1#14#1
 LO BOUND     y#1#14#2             0
 PL BOUND     y#1#14#2
 LO BOUND     y#1#14#3             0
 PL BOUND     y#1#14#3
 LO BOUND     y#1#15#1             0
 PL BOUND     y#1#15#1
 LO BOUND     y#1#15#2             0
 PL BOUND     y#1#15#2
 LO BOUND     y#1#15#3             0
 PL BOUND     y#1#15#3
 LO BOUND     y#1#16#1             0
 PL BOUND     y#1#16#1
 LO BOUND     y#1#16#2             0
 PL BOUND     y#1#16#2
 LO BOUND     y#1#16#3             0
 PL BOUND     y#1#16#3
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#6#1              0
 PL BOUND     y#2#6#1 
 LO BOUND     y#2#6#2              0
 PL BOUND     y#2#6#2 
 LO BOUND     y#2#6#3              0
 PL BOUND     y#2#6#3 
 LO BOUND     y#2#7#1              0
 PL BOUND     y#2#7#1 
 LO BOUND     y#2#7#2              0
 PL BOUND     y#2#7#2 
 LO BOUND     y#2#7#3              0
 PL BOUND     y#2#7#3 
 LO BOUND     y#2#8#1              0
 PL BOUND     y#2#8#1 
 LO BOUND     y#2#8#2              0
 PL BOUND     y#2#8#2 
 LO BOUND     y#2#8#3              0
 PL BOUND     y#2#8#3 
 LO BOUND     y#2#9#1              0
 PL BOUND     y#2#9#1 
 LO BOUND     y#2#9#2              0
 PL BOUND     y#2#9#2 
 LO BOUND     y#2#9#3              0
 PL BOUND     y#2#9#3 
 LO BOUND     y#2#10#1             0
 PL BOUND     y#2#10#1
 LO BOUND     y#2#10#2             0
 PL BOUND     y#2#10#2
 LO BOUND     y#2#10#3             0
 PL BOUND     y#2#10#3
 LO BOUND     y#2#11#1             0
 PL BOUND     y#2#11#1
 LO BOUND     y#2#11#2             0
 PL BOUND     y#2#11#2
 LO BOUND     y#2#11#3             0
 PL BOUND     y#2#11#3
 LO BOUND     y#2#12#1             0
 PL BOUND     y#2#12#1
 LO BOUND     y#2#12#2             0
 PL BOUND     y#2#12#2
 LO BOUND     y#2#12#3             0
 PL BOUND     y#2#12#3
 LO BOUND     y#2#13#1             0
 PL BOUND     y#2#13#1
 LO BOUND     y#2#13#2             0
 PL BOUND     y#2#13#2
 LO BOUND     y#2#13#3             0
 PL BOUND     y#2#13#3
 LO BOUND     y#2#14#1             0
 PL BOUND     y#2#14#1
 LO BOUND     y#2#14#2             0
 PL BOUND     y#2#14#2
 LO BOUND     y#2#14#3             0
 PL BOUND     y#2#14#3
 LO BOUND     y#2#15#1             0
 PL BOUND     y#2#15#1
 LO BOUND     y#2#15#2             0
 PL BOUND     y#2#15#2
 LO BOUND     y#2#15#3             0
 PL BOUND     y#2#15#3
 LO BOUND     y#2#16#1             0
 PL BOUND     y#2#16#1
 LO BOUND     y#2#16#2             0
 PL BOUND     y#2#16#2
 LO BOUND     y#2#16#3             0
 PL BOUND     y#2#16#3
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#6#1              0
 PL BOUND     y#3#6#1 
 LO BOUND     y#3#6#2              0
 PL BOUND     y#3#6#2 
 LO BOUND     y#3#6#3              0
 PL BOUND     y#3#6#3 
 LO BOUND     y#3#7#1              0
 PL BOUND     y#3#7#1 
 LO BOUND     y#3#7#2              0
 PL BOUND     y#3#7#2 
 LO BOUND     y#3#7#3              0
 PL BOUND     y#3#7#3 
 LO BOUND     y#3#8#1              0
 PL BOUND     y#3#8#1 
 LO BOUND     y#3#8#2              0
 PL BOUND     y#3#8#2 
 LO BOUND     y#3#8#3              0
 PL BOUND     y#3#8#3 
 LO BOUND     y#3#9#1              0
 PL BOUND     y#3#9#1 
 LO BOUND     y#3#9#2              0
 PL BOUND     y#3#9#2 
 LO BOUND     y#3#9#3              0
 PL BOUND     y#3#9#3 
 LO BOUND     y#3#10#1             0
 PL BOUND     y#3#10#1
 LO BOUND     y#3#10#2             0
 PL BOUND     y#3#10#2
 LO BOUND     y#3#10#3             0
 PL BOUND     y#3#10#3
 LO BOUND     y#3#11#1             0
 PL BOUND     y#3#11#1
 LO BOUND     y#3#11#2             0
 PL BOUND     y#3#11#2
 LO BOUND     y#3#11#3             0
 PL BOUND     y#3#11#3
 LO BOUND     y#3#12#1             0
 PL BOUND     y#3#12#1
 LO BOUND     y#3#12#2             0
 PL BOUND     y#3#12#2
 LO BOUND     y#3#12#3             0
 PL BOUND     y#3#12#3
 LO BOUND     y#3#13#1             0
 PL BOUND     y#3#13#1
 LO BOUND     y#3#13#2             0
 PL BOUND     y#3#13#2
 LO BOUND     y#3#13#3             0
 PL BOUND     y#3#13#3
 LO BOUND     y#3#14#1             0
 PL BOUND     y#3#14#1
 LO BOUND     y#3#14#2             0
 PL BOUND     y#3#14#2
 LO BOUND     y#3#14#3             0
 PL BOUND     y#3#14#3
 LO BOUND     y#3#15#1             0
 PL BOUND     y#3#15#1
 LO BOUND     y#3#15#2             0
 PL BOUND     y#3#15#2
 LO BOUND     y#3#15#3             0
 PL BOUND     y#3#15#3
 LO BOUND     y#3#16#1             0
 PL BOUND     y#3#16#1
 LO BOUND     y#3#16#2             0
 PL BOUND     y#3#16#2
 LO BOUND     y#3#16#3             0
 PL BOUND     y#3#16#3
 LO BOUND     p#1                  0
 UP BOUND     p#1                  1
 LO BOUND     p#2                  0
 UP BOUND     p#2                  1
 LO BOUND     p#3                  0
 UP BOUND     p#3                  1
 LO BOUND     p#4                  0
 UP BOUND     p#4                  1
 LO BOUND     p#5                  0
 UP BOUND     p#5                  1
 LO BOUND     p#6                  0
 UP BOUND     p#6                  1
 LO BOUND     p#7                  0
 UP BOUND     p#7                  1
 LO BOUND     p#8                  0
 UP BOUND     p#8                  1
 LO BOUND     p#9                  0
 UP BOUND     p#9                  1
 LO BOUND     p#10                 0
 UP BOUND     p#10                 1
 LO BOUND     p#11                 0
 UP BOUND     p#11                 1
 LO BOUND     p#12                 0
 UP BOUND     p#12                 1
 LO BOUND     p#13                 0
 UP BOUND     p#13                 1
 LO BOUND     p#14                 0
 UP BOUND     p#14                 1
 LO BOUND     p#15                 0
 UP BOUND     p#15                 1
 LO BOUND     p#16                 0
 UP BOUND     p#16                 1
ENDATA
