* This file was automatically generated by Zimpl
* param Q2 := 1;
* param M := 1000;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nN := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set N := { 1 .. nN };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[N] := read file1 as "<1n> 2n" skip 1 use nN;
* param backCost[N] := read file1 as "<1n> 2n" skip nN+1 use nN;
* param demand[C*N*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nN+1;
* param q[P*N] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*N] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in N with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <j> in P with q[j,i] > 0 };
* var B[C*N*T0] >= 0;
* var I[C*N*T0] >= 0;
* var f[C*N*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var p[P] binary;
* minimize cost: sum <i> in N: ( sum <t> in T: (sum <c> in C : (inveCost[i] * I[c,i,t]  + backCost[i] * B[c,i,t]) ));
* subto select:       sum <j> in P: p[j] <= m;
* subto balance:    forall <c,i,t> in C*N*T with t>=1 do       I[c,i,t-1] - B[c,i,t-1] + Q1*Q2*f[c,i,t] + Q2 * (sum <j> in Pc[c
* ]: q[j,i] * y[c,j,t]) == demand[c,i,t] + I[c,i,t] - B[c,i,t];
* subto valid:    forall <c,i> in C*N do       sum <t> in T: ( min(Q1, D[c,i]) * f[c,i,t] + sum <j> in Pc[c]: ( min(q[j,i], D[c
* ,i] ) * y[c,j,t]) ) >= D[c,i];
* subto BigM:    forall <c,j,t> in C*P*T with t>=1 do       y[c,j,t] <= M*p[j];
* subto init1:    forall <c,i> in C*N do       I[c,i,0] == 0;
* subto init2:    forall <c,i> in C*N do       B[c,i,0] == 0;
* subto init3:    forall <c,i> in C*N do       B[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 E  balan@25          
 E  balan@26          
 E  balan@27          
 E  balan@28          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 L  BigM_101          
 L  BigM_102          
 L  BigM_103          
 L  BigM_104          
 L  BigM_105          
 L  BigM_106          
 L  BigM_107          
 L  BigM_108          
 L  BigM_109          
 L  BigM_110          
 L  BigM_111          
 L  BigM_112          
 L  BigM_113          
 L  BigM_114          
 L  BigM_115          
 L  BigM_116          
 L  BigM_117          
 L  BigM_118          
 L  BigM_119          
 L  BigM_120          
 L  BigM_121          
 L  BigM_122          
 L  BigM_123          
 L  BigM_124          
 L  BigM_125          
 L  BigM_126          
 L  BigM_127          
 L  BigM_128          
 L  BigM_129          
 L  BigM_130          
 L  BigM_131          
 L  BigM_132          
 L  BigM_133          
 L  BigM_134          
 L  BigM_135          
 L  BigM_136          
 L  BigM_137          
 L  BigM_138          
 L  BigM_139          
 L  BigM_140          
 L  BigM_141          
 L  BigM_142          
 L  BigM_143          
 L  BigM_144          
 L  BigM_145          
 L  BigM_146          
 L  BigM_147          
 L  BigM_148          
 L  BigM_149          
 L  BigM_150          
 L  BigM_151          
 L  BigM_152          
 L  BigM_153          
 L  BigM_154          
 L  BigM_155          
 L  BigM_156          
 L  BigM_157          
 L  BigM_158          
 L  BigM_159          
 L  BigM_160          
 L  BigM_161          
 L  BigM_162          
 L  BigM_163          
 L  BigM_164          
 L  BigM_165          
 L  BigM_166          
 L  BigM_167          
 L  BigM_168          
 L  BigM_169          
 L  BigM_170          
 L  BigM_171          
 L  BigM_172          
 L  BigM_173          
 L  BigM_174          
 L  BigM_175          
 L  BigM_176          
 L  BigM_177          
 L  BigM_178          
 L  BigM_179          
 L  BigM_180          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    f#1#1#1   valid_1             72
    f#1#1#1   balanc@1            72
    f#1#1#2   valid_1             72
    f#1#1#2   balanc@2            72
    f#1#1#3   valid_1             72
    f#1#1#3   balanc@3            72
    f#1#1#4   valid_1             72
    f#1#1#4   balanc@4            72
    f#1#1#5   valid_1             72
    f#1#1#5   balanc@5            72
    f#1#2#1   balanc@6            72
    f#1#2#2   balanc@7            72
    f#1#2#3   balanc@8            72
    f#1#2#4   balanc@9            72
    f#1#2#5   balanc@a            72
    f#2#1#1   valid_2             72
    f#2#1#1   balanc@b            72
    f#2#1#2   valid_2             72
    f#2#1#2   balanc@c            72
    f#2#1#3   valid_2             72
    f#2#1#3   balanc@d            72
    f#2#1#4   valid_2             72
    f#2#1#4   balanc@e            72
    f#2#1#5   valid_2             72
    f#2#1#5   balanc@f            72
    f#2#2#1   valid_3             72
    f#2#2#1   balan@10            72
    f#2#2#2   valid_3             72
    f#2#2#2   balan@11            72
    f#2#2#3   valid_3             72
    f#2#2#3   balan@12            72
    f#2#2#4   valid_3             72
    f#2#2#4   balan@13            72
    f#2#2#5   valid_3             72
    f#2#2#5   balan@14            72
    f#3#1#1   valid_4             72
    f#3#1#1   balan@15            72
    f#3#1#2   valid_4             72
    f#3#1#2   balan@16            72
    f#3#1#3   valid_4             72
    f#3#1#3   balan@17            72
    f#3#1#4   valid_4             72
    f#3#1#4   balan@18            72
    f#3#1#5   valid_4             72
    f#3#1#5   balan@19            72
    f#3#2#1   valid_5             72
    f#3#2#1   balan@1a            72
    f#3#2#2   valid_5             72
    f#3#2#2   balan@1b            72
    f#3#2#3   valid_5             72
    f#3#2#3   balan@1c            72
    f#3#2#4   valid_5             72
    f#3#2#4   balan@1d            72
    f#3#2#5   valid_5             72
    f#3#2#5   balan@1e            72
    f#4#1#1   balan@1f            72
    f#4#1#2   balan@20            72
    f#4#1#3   balan@21            72
    f#4#1#4   balan@22            72
    f#4#1#5   balan@23            72
    f#4#2#1   valid_6             72
    f#4#2#1   balan@24            72
    f#4#2#2   valid_6             72
    f#4#2#2   balan@25            72
    f#4#2#3   valid_6             72
    f#4#2#3   balan@26            72
    f#4#2#4   valid_6             72
    f#4#2#4   balan@27            72
    f#4#2#5   valid_6             72
    f#4#2#5   balan@28            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_1             51
    y#1#1#1   balanc@6            21
    y#1#1#1   balanc@1            51
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_1             51
    y#1#1#2   balanc@7            21
    y#1#1#2   balanc@2            51
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_1             51
    y#1#1#3   balanc@8            21
    y#1#1#3   balanc@3            51
    y#1#1#4   BigM_4               1
    y#1#1#4   valid_1             51
    y#1#1#4   balanc@9            21
    y#1#1#4   balanc@4            51
    y#1#1#5   BigM_5               1
    y#1#1#5   valid_1             51
    y#1#1#5   balanc@a            21
    y#1#1#5   balanc@5            51
    y#1#2#1   BigM_6               1
    y#1#2#1   valid_1             27
    y#1#2#1   balanc@6            45
    y#1#2#1   balanc@1            27
    y#1#2#2   BigM_7               1
    y#1#2#2   valid_1             27
    y#1#2#2   balanc@7            45
    y#1#2#2   balanc@2            27
    y#1#2#3   BigM_8               1
    y#1#2#3   valid_1             27
    y#1#2#3   balanc@8            45
    y#1#2#3   balanc@3            27
    y#1#2#4   BigM_9               1
    y#1#2#4   valid_1             27
    y#1#2#4   balanc@9            45
    y#1#2#4   balanc@4            27
    y#1#2#5   BigM_10              1
    y#1#2#5   valid_1             27
    y#1#2#5   balanc@a            45
    y#1#2#5   balanc@5            27
    y#1#3#1   BigM_11              1
    y#1#3#1   valid_1             17
    y#1#3#1   balanc@6            55
    y#1#3#1   balanc@1            17
    y#1#3#2   BigM_12              1
    y#1#3#2   valid_1             17
    y#1#3#2   balanc@7            55
    y#1#3#2   balanc@2            17
    y#1#3#3   BigM_13              1
    y#1#3#3   valid_1             17
    y#1#3#3   balanc@8            55
    y#1#3#3   balanc@3            17
    y#1#3#4   BigM_14              1
    y#1#3#4   valid_1             17
    y#1#3#4   balanc@9            55
    y#1#3#4   balanc@4            17
    y#1#3#5   BigM_15              1
    y#1#3#5   valid_1             17
    y#1#3#5   balanc@a            55
    y#1#3#5   balanc@5            17
    y#1#4#1   BigM_16              1
    y#1#4#1   valid_1             22
    y#1#4#1   balanc@6            50
    y#1#4#1   balanc@1            22
    y#1#4#2   BigM_17              1
    y#1#4#2   valid_1             22
    y#1#4#2   balanc@7            50
    y#1#4#2   balanc@2            22
    y#1#4#3   BigM_18              1
    y#1#4#3   valid_1             22
    y#1#4#3   balanc@8            50
    y#1#4#3   balanc@3            22
    y#1#4#4   BigM_19              1
    y#1#4#4   valid_1             22
    y#1#4#4   balanc@9            50
    y#1#4#4   balanc@4            22
    y#1#4#5   BigM_20              1
    y#1#4#5   valid_1             22
    y#1#4#5   balanc@a            50
    y#1#4#5   balanc@5            22
    y#1#5#1   BigM_21              1
    y#1#5#1   valid_1             12
    y#1#5#1   balanc@6            60
    y#1#5#1   balanc@1            12
    y#1#5#2   BigM_22              1
    y#1#5#2   valid_1             12
    y#1#5#2   balanc@7            60
    y#1#5#2   balanc@2            12
    y#1#5#3   BigM_23              1
    y#1#5#3   valid_1             12
    y#1#5#3   balanc@8            60
    y#1#5#3   balanc@3            12
    y#1#5#4   BigM_24              1
    y#1#5#4   valid_1             12
    y#1#5#4   balanc@9            60
    y#1#5#4   balanc@4            12
    y#1#5#5   BigM_25              1
    y#1#5#5   valid_1             12
    y#1#5#5   balanc@a            60
    y#1#5#5   balanc@5            12
    y#1#6#1   BigM_26              1
    y#1#6#1   valid_1             52
    y#1#6#1   balanc@6            20
    y#1#6#1   balanc@1            52
    y#1#6#2   BigM_27              1
    y#1#6#2   valid_1             52
    y#1#6#2   balanc@7            20
    y#1#6#2   balanc@2            52
    y#1#6#3   BigM_28              1
    y#1#6#3   valid_1             52
    y#1#6#3   balanc@8            20
    y#1#6#3   balanc@3            52
    y#1#6#4   BigM_29              1
    y#1#6#4   valid_1             52
    y#1#6#4   balanc@9            20
    y#1#6#4   balanc@4            52
    y#1#6#5   BigM_30              1
    y#1#6#5   valid_1             52
    y#1#6#5   balanc@a            20
    y#1#6#5   balanc@5            52
    y#1#7#1   BigM_31              1
    y#1#7#1   valid_1             58
    y#1#7#1   balanc@6            14
    y#1#7#1   balanc@1            58
    y#1#7#2   BigM_32              1
    y#1#7#2   valid_1             58
    y#1#7#2   balanc@7            14
    y#1#7#2   balanc@2            58
    y#1#7#3   BigM_33              1
    y#1#7#3   valid_1             58
    y#1#7#3   balanc@8            14
    y#1#7#3   balanc@3            58
    y#1#7#4   BigM_34              1
    y#1#7#4   valid_1             58
    y#1#7#4   balanc@9            14
    y#1#7#4   balanc@4            58
    y#1#7#5   BigM_35              1
    y#1#7#5   valid_1             58
    y#1#7#5   balanc@a            14
    y#1#7#5   balanc@5            58
    y#1#8#1   BigM_36              1
    y#1#8#1   valid_1             32
    y#1#8#1   balanc@6            40
    y#1#8#1   balanc@1            32
    y#1#8#2   BigM_37              1
    y#1#8#2   valid_1             32
    y#1#8#2   balanc@7            40
    y#1#8#2   balanc@2            32
    y#1#8#3   BigM_38              1
    y#1#8#3   valid_1             32
    y#1#8#3   balanc@8            40
    y#1#8#3   balanc@3            32
    y#1#8#4   BigM_39              1
    y#1#8#4   valid_1             32
    y#1#8#4   balanc@9            40
    y#1#8#4   balanc@4            32
    y#1#8#5   BigM_40              1
    y#1#8#5   valid_1             32
    y#1#8#5   balanc@a            40
    y#1#8#5   balanc@5            32
    y#1#9#1   BigM_41              1
    y#1#9#1   valid_1             13
    y#1#9#1   balanc@6            59
    y#1#9#1   balanc@1            13
    y#1#9#2   BigM_42              1
    y#1#9#2   valid_1             13
    y#1#9#2   balanc@7            59
    y#1#9#2   balanc@2            13
    y#1#9#3   BigM_43              1
    y#1#9#3   valid_1             13
    y#1#9#3   balanc@8            59
    y#1#9#3   balanc@3            13
    y#1#9#4   BigM_44              1
    y#1#9#4   valid_1             13
    y#1#9#4   balanc@9            59
    y#1#9#4   balanc@4            13
    y#1#9#5   BigM_45              1
    y#1#9#5   valid_1             13
    y#1#9#5   balanc@a            59
    y#1#9#5   balanc@5            13
    y#2#1#1   BigM_46              1
    y#2#1#1   valid_3             21
    y#2#1#1   valid_2             51
    y#2#1#1   balan@10            21
    y#2#1#1   balanc@b            51
    y#2#1#2   BigM_47              1
    y#2#1#2   valid_3             21
    y#2#1#2   valid_2             51
    y#2#1#2   balan@11            21
    y#2#1#2   balanc@c            51
    y#2#1#3   BigM_48              1
    y#2#1#3   valid_3             21
    y#2#1#3   valid_2             51
    y#2#1#3   balan@12            21
    y#2#1#3   balanc@d            51
    y#2#1#4   BigM_49              1
    y#2#1#4   valid_3             21
    y#2#1#4   valid_2             51
    y#2#1#4   balan@13            21
    y#2#1#4   balanc@e            51
    y#2#1#5   BigM_50              1
    y#2#1#5   valid_3             21
    y#2#1#5   valid_2             51
    y#2#1#5   balan@14            21
    y#2#1#5   balanc@f            51
    y#2#2#1   BigM_51              1
    y#2#2#1   valid_3             45
    y#2#2#1   valid_2             27
    y#2#2#1   balan@10            45
    y#2#2#1   balanc@b            27
    y#2#2#2   BigM_52              1
    y#2#2#2   valid_3             45
    y#2#2#2   valid_2             27
    y#2#2#2   balan@11            45
    y#2#2#2   balanc@c            27
    y#2#2#3   BigM_53              1
    y#2#2#3   valid_3             45
    y#2#2#3   valid_2             27
    y#2#2#3   balan@12            45
    y#2#2#3   balanc@d            27
    y#2#2#4   BigM_54              1
    y#2#2#4   valid_3             45
    y#2#2#4   valid_2             27
    y#2#2#4   balan@13            45
    y#2#2#4   balanc@e            27
    y#2#2#5   BigM_55              1
    y#2#2#5   valid_3             45
    y#2#2#5   valid_2             27
    y#2#2#5   balan@14            45
    y#2#2#5   balanc@f            27
    y#2#3#1   BigM_56              1
    y#2#3#1   valid_3             55
    y#2#3#1   valid_2             17
    y#2#3#1   balan@10            55
    y#2#3#1   balanc@b            17
    y#2#3#2   BigM_57              1
    y#2#3#2   valid_3             55
    y#2#3#2   valid_2             17
    y#2#3#2   balan@11            55
    y#2#3#2   balanc@c            17
    y#2#3#3   BigM_58              1
    y#2#3#3   valid_3             55
    y#2#3#3   valid_2             17
    y#2#3#3   balan@12            55
    y#2#3#3   balanc@d            17
    y#2#3#4   BigM_59              1
    y#2#3#4   valid_3             55
    y#2#3#4   valid_2             17
    y#2#3#4   balan@13            55
    y#2#3#4   balanc@e            17
    y#2#3#5   BigM_60              1
    y#2#3#5   valid_3             55
    y#2#3#5   valid_2             17
    y#2#3#5   balan@14            55
    y#2#3#5   balanc@f            17
    y#2#4#1   BigM_61              1
    y#2#4#1   valid_3             50
    y#2#4#1   valid_2             22
    y#2#4#1   balan@10            50
    y#2#4#1   balanc@b            22
    y#2#4#2   BigM_62              1
    y#2#4#2   valid_3             50
    y#2#4#2   valid_2             22
    y#2#4#2   balan@11            50
    y#2#4#2   balanc@c            22
    y#2#4#3   BigM_63              1
    y#2#4#3   valid_3             50
    y#2#4#3   valid_2             22
    y#2#4#3   balan@12            50
    y#2#4#3   balanc@d            22
    y#2#4#4   BigM_64              1
    y#2#4#4   valid_3             50
    y#2#4#4   valid_2             22
    y#2#4#4   balan@13            50
    y#2#4#4   balanc@e            22
    y#2#4#5   BigM_65              1
    y#2#4#5   valid_3             50
    y#2#4#5   valid_2             22
    y#2#4#5   balan@14            50
    y#2#4#5   balanc@f            22
    y#2#5#1   BigM_66              1
    y#2#5#1   valid_3             60
    y#2#5#1   valid_2             12
    y#2#5#1   balan@10            60
    y#2#5#1   balanc@b            12
    y#2#5#2   BigM_67              1
    y#2#5#2   valid_3             60
    y#2#5#2   valid_2             12
    y#2#5#2   balan@11            60
    y#2#5#2   balanc@c            12
    y#2#5#3   BigM_68              1
    y#2#5#3   valid_3             60
    y#2#5#3   valid_2             12
    y#2#5#3   balan@12            60
    y#2#5#3   balanc@d            12
    y#2#5#4   BigM_69              1
    y#2#5#4   valid_3             60
    y#2#5#4   valid_2             12
    y#2#5#4   balan@13            60
    y#2#5#4   balanc@e            12
    y#2#5#5   BigM_70              1
    y#2#5#5   valid_3             60
    y#2#5#5   valid_2             12
    y#2#5#5   balan@14            60
    y#2#5#5   balanc@f            12
    y#2#6#1   BigM_71              1
    y#2#6#1   valid_3             20
    y#2#6#1   valid_2             52
    y#2#6#1   balan@10            20
    y#2#6#1   balanc@b            52
    y#2#6#2   BigM_72              1
    y#2#6#2   valid_3             20
    y#2#6#2   valid_2             52
    y#2#6#2   balan@11            20
    y#2#6#2   balanc@c            52
    y#2#6#3   BigM_73              1
    y#2#6#3   valid_3             20
    y#2#6#3   valid_2             52
    y#2#6#3   balan@12            20
    y#2#6#3   balanc@d            52
    y#2#6#4   BigM_74              1
    y#2#6#4   valid_3             20
    y#2#6#4   valid_2             52
    y#2#6#4   balan@13            20
    y#2#6#4   balanc@e            52
    y#2#6#5   BigM_75              1
    y#2#6#5   valid_3             20
    y#2#6#5   valid_2             52
    y#2#6#5   balan@14            20
    y#2#6#5   balanc@f            52
    y#2#7#1   BigM_76              1
    y#2#7#1   valid_3             14
    y#2#7#1   valid_2             58
    y#2#7#1   balan@10            14
    y#2#7#1   balanc@b            58
    y#2#7#2   BigM_77              1
    y#2#7#2   valid_3             14
    y#2#7#2   valid_2             58
    y#2#7#2   balan@11            14
    y#2#7#2   balanc@c            58
    y#2#7#3   BigM_78              1
    y#2#7#3   valid_3             14
    y#2#7#3   valid_2             58
    y#2#7#3   balan@12            14
    y#2#7#3   balanc@d            58
    y#2#7#4   BigM_79              1
    y#2#7#4   valid_3             14
    y#2#7#4   valid_2             58
    y#2#7#4   balan@13            14
    y#2#7#4   balanc@e            58
    y#2#7#5   BigM_80              1
    y#2#7#5   valid_3             14
    y#2#7#5   valid_2             58
    y#2#7#5   balan@14            14
    y#2#7#5   balanc@f            58
    y#2#8#1   BigM_81              1
    y#2#8#1   valid_3             40
    y#2#8#1   valid_2             32
    y#2#8#1   balan@10            40
    y#2#8#1   balanc@b            32
    y#2#8#2   BigM_82              1
    y#2#8#2   valid_3             40
    y#2#8#2   valid_2             32
    y#2#8#2   balan@11            40
    y#2#8#2   balanc@c            32
    y#2#8#3   BigM_83              1
    y#2#8#3   valid_3             40
    y#2#8#3   valid_2             32
    y#2#8#3   balan@12            40
    y#2#8#3   balanc@d            32
    y#2#8#4   BigM_84              1
    y#2#8#4   valid_3             40
    y#2#8#4   valid_2             32
    y#2#8#4   balan@13            40
    y#2#8#4   balanc@e            32
    y#2#8#5   BigM_85              1
    y#2#8#5   valid_3             40
    y#2#8#5   valid_2             32
    y#2#8#5   balan@14            40
    y#2#8#5   balanc@f            32
    y#2#9#1   BigM_86              1
    y#2#9#1   valid_3             59
    y#2#9#1   valid_2             13
    y#2#9#1   balan@10            59
    y#2#9#1   balanc@b            13
    y#2#9#2   BigM_87              1
    y#2#9#2   valid_3             59
    y#2#9#2   valid_2             13
    y#2#9#2   balan@11            59
    y#2#9#2   balanc@c            13
    y#2#9#3   BigM_88              1
    y#2#9#3   valid_3             59
    y#2#9#3   valid_2             13
    y#2#9#3   balan@12            59
    y#2#9#3   balanc@d            13
    y#2#9#4   BigM_89              1
    y#2#9#4   valid_3             59
    y#2#9#4   valid_2             13
    y#2#9#4   balan@13            59
    y#2#9#4   balanc@e            13
    y#2#9#5   BigM_90              1
    y#2#9#5   valid_3             59
    y#2#9#5   valid_2             13
    y#2#9#5   balan@14            59
    y#2#9#5   balanc@f            13
    y#3#1#1   BigM_91              1
    y#3#1#1   valid_5             21
    y#3#1#1   valid_4             51
    y#3#1#1   balan@1a            21
    y#3#1#1   balan@15            51
    y#3#1#2   BigM_92              1
    y#3#1#2   valid_5             21
    y#3#1#2   valid_4             51
    y#3#1#2   balan@1b            21
    y#3#1#2   balan@16            51
    y#3#1#3   BigM_93              1
    y#3#1#3   valid_5             21
    y#3#1#3   valid_4             51
    y#3#1#3   balan@1c            21
    y#3#1#3   balan@17            51
    y#3#1#4   BigM_94              1
    y#3#1#4   valid_5             21
    y#3#1#4   valid_4             51
    y#3#1#4   balan@1d            21
    y#3#1#4   balan@18            51
    y#3#1#5   BigM_95              1
    y#3#1#5   valid_5             21
    y#3#1#5   valid_4             51
    y#3#1#5   balan@1e            21
    y#3#1#5   balan@19            51
    y#3#2#1   BigM_96              1
    y#3#2#1   valid_5             45
    y#3#2#1   valid_4             27
    y#3#2#1   balan@1a            45
    y#3#2#1   balan@15            27
    y#3#2#2   BigM_97              1
    y#3#2#2   valid_5             45
    y#3#2#2   valid_4             27
    y#3#2#2   balan@1b            45
    y#3#2#2   balan@16            27
    y#3#2#3   BigM_98              1
    y#3#2#3   valid_5             45
    y#3#2#3   valid_4             27
    y#3#2#3   balan@1c            45
    y#3#2#3   balan@17            27
    y#3#2#4   BigM_99              1
    y#3#2#4   valid_5             45
    y#3#2#4   valid_4             27
    y#3#2#4   balan@1d            45
    y#3#2#4   balan@18            27
    y#3#2#5   BigM_100             1
    y#3#2#5   valid_5             45
    y#3#2#5   valid_4             27
    y#3#2#5   balan@1e            45
    y#3#2#5   balan@19            27
    y#3#3#1   BigM_101             1
    y#3#3#1   valid_5             55
    y#3#3#1   valid_4             17
    y#3#3#1   balan@1a            55
    y#3#3#1   balan@15            17
    y#3#3#2   BigM_102             1
    y#3#3#2   valid_5             55
    y#3#3#2   valid_4             17
    y#3#3#2   balan@1b            55
    y#3#3#2   balan@16            17
    y#3#3#3   BigM_103             1
    y#3#3#3   valid_5             55
    y#3#3#3   valid_4             17
    y#3#3#3   balan@1c            55
    y#3#3#3   balan@17            17
    y#3#3#4   BigM_104             1
    y#3#3#4   valid_5             55
    y#3#3#4   valid_4             17
    y#3#3#4   balan@1d            55
    y#3#3#4   balan@18            17
    y#3#3#5   BigM_105             1
    y#3#3#5   valid_5             55
    y#3#3#5   valid_4             17
    y#3#3#5   balan@1e            55
    y#3#3#5   balan@19            17
    y#3#4#1   BigM_106             1
    y#3#4#1   valid_5             50
    y#3#4#1   valid_4             22
    y#3#4#1   balan@1a            50
    y#3#4#1   balan@15            22
    y#3#4#2   BigM_107             1
    y#3#4#2   valid_5             50
    y#3#4#2   valid_4             22
    y#3#4#2   balan@1b            50
    y#3#4#2   balan@16            22
    y#3#4#3   BigM_108             1
    y#3#4#3   valid_5             50
    y#3#4#3   valid_4             22
    y#3#4#3   balan@1c            50
    y#3#4#3   balan@17            22
    y#3#4#4   BigM_109             1
    y#3#4#4   valid_5             50
    y#3#4#4   valid_4             22
    y#3#4#4   balan@1d            50
    y#3#4#4   balan@18            22
    y#3#4#5   BigM_110             1
    y#3#4#5   valid_5             50
    y#3#4#5   valid_4             22
    y#3#4#5   balan@1e            50
    y#3#4#5   balan@19            22
    y#3#5#1   BigM_111             1
    y#3#5#1   valid_5             60
    y#3#5#1   valid_4             12
    y#3#5#1   balan@1a            60
    y#3#5#1   balan@15            12
    y#3#5#2   BigM_112             1
    y#3#5#2   valid_5             60
    y#3#5#2   valid_4             12
    y#3#5#2   balan@1b            60
    y#3#5#2   balan@16            12
    y#3#5#3   BigM_113             1
    y#3#5#3   valid_5             60
    y#3#5#3   valid_4             12
    y#3#5#3   balan@1c            60
    y#3#5#3   balan@17            12
    y#3#5#4   BigM_114             1
    y#3#5#4   valid_5             60
    y#3#5#4   valid_4             12
    y#3#5#4   balan@1d            60
    y#3#5#4   balan@18            12
    y#3#5#5   BigM_115             1
    y#3#5#5   valid_5             60
    y#3#5#5   valid_4             12
    y#3#5#5   balan@1e            60
    y#3#5#5   balan@19            12
    y#3#6#1   BigM_116             1
    y#3#6#1   valid_5             20
    y#3#6#1   valid_4             52
    y#3#6#1   balan@1a            20
    y#3#6#1   balan@15            52
    y#3#6#2   BigM_117             1
    y#3#6#2   valid_5             20
    y#3#6#2   valid_4             52
    y#3#6#2   balan@1b            20
    y#3#6#2   balan@16            52
    y#3#6#3   BigM_118             1
    y#3#6#3   valid_5             20
    y#3#6#3   valid_4             52
    y#3#6#3   balan@1c            20
    y#3#6#3   balan@17            52
    y#3#6#4   BigM_119             1
    y#3#6#4   valid_5             20
    y#3#6#4   valid_4             52
    y#3#6#4   balan@1d            20
    y#3#6#4   balan@18            52
    y#3#6#5   BigM_120             1
    y#3#6#5   valid_5             20
    y#3#6#5   valid_4             52
    y#3#6#5   balan@1e            20
    y#3#6#5   balan@19            52
    y#3#7#1   BigM_121             1
    y#3#7#1   valid_5             14
    y#3#7#1   valid_4             58
    y#3#7#1   balan@1a            14
    y#3#7#1   balan@15            58
    y#3#7#2   BigM_122             1
    y#3#7#2   valid_5             14
    y#3#7#2   valid_4             58
    y#3#7#2   balan@1b            14
    y#3#7#2   balan@16            58
    y#3#7#3   BigM_123             1
    y#3#7#3   valid_5             14
    y#3#7#3   valid_4             58
    y#3#7#3   balan@1c            14
    y#3#7#3   balan@17            58
    y#3#7#4   BigM_124             1
    y#3#7#4   valid_5             14
    y#3#7#4   valid_4             58
    y#3#7#4   balan@1d            14
    y#3#7#4   balan@18            58
    y#3#7#5   BigM_125             1
    y#3#7#5   valid_5             14
    y#3#7#5   valid_4             58
    y#3#7#5   balan@1e            14
    y#3#7#5   balan@19            58
    y#3#8#1   BigM_126             1
    y#3#8#1   valid_5             40
    y#3#8#1   valid_4             32
    y#3#8#1   balan@1a            40
    y#3#8#1   balan@15            32
    y#3#8#2   BigM_127             1
    y#3#8#2   valid_5             40
    y#3#8#2   valid_4             32
    y#3#8#2   balan@1b            40
    y#3#8#2   balan@16            32
    y#3#8#3   BigM_128             1
    y#3#8#3   valid_5             40
    y#3#8#3   valid_4             32
    y#3#8#3   balan@1c            40
    y#3#8#3   balan@17            32
    y#3#8#4   BigM_129             1
    y#3#8#4   valid_5             40
    y#3#8#4   valid_4             32
    y#3#8#4   balan@1d            40
    y#3#8#4   balan@18            32
    y#3#8#5   BigM_130             1
    y#3#8#5   valid_5             40
    y#3#8#5   valid_4             32
    y#3#8#5   balan@1e            40
    y#3#8#5   balan@19            32
    y#3#9#1   BigM_131             1
    y#3#9#1   valid_5             59
    y#3#9#1   valid_4             13
    y#3#9#1   balan@1a            59
    y#3#9#1   balan@15            13
    y#3#9#2   BigM_132             1
    y#3#9#2   valid_5             59
    y#3#9#2   valid_4             13
    y#3#9#2   balan@1b            59
    y#3#9#2   balan@16            13
    y#3#9#3   BigM_133             1
    y#3#9#3   valid_5             59
    y#3#9#3   valid_4             13
    y#3#9#3   balan@1c            59
    y#3#9#3   balan@17            13
    y#3#9#4   BigM_134             1
    y#3#9#4   valid_5             59
    y#3#9#4   valid_4             13
    y#3#9#4   balan@1d            59
    y#3#9#4   balan@18            13
    y#3#9#5   BigM_135             1
    y#3#9#5   valid_5             59
    y#3#9#5   valid_4             13
    y#3#9#5   balan@1e            59
    y#3#9#5   balan@19            13
    y#4#1#1   BigM_136             1
    y#4#1#1   valid_6             21
    y#4#1#1   balan@24            21
    y#4#1#1   balan@1f            51
    y#4#1#2   BigM_137             1
    y#4#1#2   valid_6             21
    y#4#1#2   balan@25            21
    y#4#1#2   balan@20            51
    y#4#1#3   BigM_138             1
    y#4#1#3   valid_6             21
    y#4#1#3   balan@26            21
    y#4#1#3   balan@21            51
    y#4#1#4   BigM_139             1
    y#4#1#4   valid_6             21
    y#4#1#4   balan@27            21
    y#4#1#4   balan@22            51
    y#4#1#5   BigM_140             1
    y#4#1#5   valid_6             21
    y#4#1#5   balan@28            21
    y#4#1#5   balan@23            51
    y#4#2#1   BigM_141             1
    y#4#2#1   valid_6             45
    y#4#2#1   balan@24            45
    y#4#2#1   balan@1f            27
    y#4#2#2   BigM_142             1
    y#4#2#2   valid_6             45
    y#4#2#2   balan@25            45
    y#4#2#2   balan@20            27
    y#4#2#3   BigM_143             1
    y#4#2#3   valid_6             45
    y#4#2#3   balan@26            45
    y#4#2#3   balan@21            27
    y#4#2#4   BigM_144             1
    y#4#2#4   valid_6             45
    y#4#2#4   balan@27            45
    y#4#2#4   balan@22            27
    y#4#2#5   BigM_145             1
    y#4#2#5   valid_6             45
    y#4#2#5   balan@28            45
    y#4#2#5   balan@23            27
    y#4#3#1   BigM_146             1
    y#4#3#1   valid_6             55
    y#4#3#1   balan@24            55
    y#4#3#1   balan@1f            17
    y#4#3#2   BigM_147             1
    y#4#3#2   valid_6             55
    y#4#3#2   balan@25            55
    y#4#3#2   balan@20            17
    y#4#3#3   BigM_148             1
    y#4#3#3   valid_6             55
    y#4#3#3   balan@26            55
    y#4#3#3   balan@21            17
    y#4#3#4   BigM_149             1
    y#4#3#4   valid_6             55
    y#4#3#4   balan@27            55
    y#4#3#4   balan@22            17
    y#4#3#5   BigM_150             1
    y#4#3#5   valid_6             55
    y#4#3#5   balan@28            55
    y#4#3#5   balan@23            17
    y#4#4#1   BigM_151             1
    y#4#4#1   valid_6             50
    y#4#4#1   balan@24            50
    y#4#4#1   balan@1f            22
    y#4#4#2   BigM_152             1
    y#4#4#2   valid_6             50
    y#4#4#2   balan@25            50
    y#4#4#2   balan@20            22
    y#4#4#3   BigM_153             1
    y#4#4#3   valid_6             50
    y#4#4#3   balan@26            50
    y#4#4#3   balan@21            22
    y#4#4#4   BigM_154             1
    y#4#4#4   valid_6             50
    y#4#4#4   balan@27            50
    y#4#4#4   balan@22            22
    y#4#4#5   BigM_155             1
    y#4#4#5   valid_6             50
    y#4#4#5   balan@28            50
    y#4#4#5   balan@23            22
    y#4#5#1   BigM_156             1
    y#4#5#1   valid_6             60
    y#4#5#1   balan@24            60
    y#4#5#1   balan@1f            12
    y#4#5#2   BigM_157             1
    y#4#5#2   valid_6             60
    y#4#5#2   balan@25            60
    y#4#5#2   balan@20            12
    y#4#5#3   BigM_158             1
    y#4#5#3   valid_6             60
    y#4#5#3   balan@26            60
    y#4#5#3   balan@21            12
    y#4#5#4   BigM_159             1
    y#4#5#4   valid_6             60
    y#4#5#4   balan@27            60
    y#4#5#4   balan@22            12
    y#4#5#5   BigM_160             1
    y#4#5#5   valid_6             60
    y#4#5#5   balan@28            60
    y#4#5#5   balan@23            12
    y#4#6#1   BigM_161             1
    y#4#6#1   valid_6             20
    y#4#6#1   balan@24            20
    y#4#6#1   balan@1f            52
    y#4#6#2   BigM_162             1
    y#4#6#2   valid_6             20
    y#4#6#2   balan@25            20
    y#4#6#2   balan@20            52
    y#4#6#3   BigM_163             1
    y#4#6#3   valid_6             20
    y#4#6#3   balan@26            20
    y#4#6#3   balan@21            52
    y#4#6#4   BigM_164             1
    y#4#6#4   valid_6             20
    y#4#6#4   balan@27            20
    y#4#6#4   balan@22            52
    y#4#6#5   BigM_165             1
    y#4#6#5   valid_6             20
    y#4#6#5   balan@28            20
    y#4#6#5   balan@23            52
    y#4#7#1   BigM_166             1
    y#4#7#1   valid_6             14
    y#4#7#1   balan@24            14
    y#4#7#1   balan@1f            58
    y#4#7#2   BigM_167             1
    y#4#7#2   valid_6             14
    y#4#7#2   balan@25            14
    y#4#7#2   balan@20            58
    y#4#7#3   BigM_168             1
    y#4#7#3   valid_6             14
    y#4#7#3   balan@26            14
    y#4#7#3   balan@21            58
    y#4#7#4   BigM_169             1
    y#4#7#4   valid_6             14
    y#4#7#4   balan@27            14
    y#4#7#4   balan@22            58
    y#4#7#5   BigM_170             1
    y#4#7#5   valid_6             14
    y#4#7#5   balan@28            14
    y#4#7#5   balan@23            58
    y#4#8#1   BigM_171             1
    y#4#8#1   valid_6             40
    y#4#8#1   balan@24            40
    y#4#8#1   balan@1f            32
    y#4#8#2   BigM_172             1
    y#4#8#2   valid_6             40
    y#4#8#2   balan@25            40
    y#4#8#2   balan@20            32
    y#4#8#3   BigM_173             1
    y#4#8#3   valid_6             40
    y#4#8#3   balan@26            40
    y#4#8#3   balan@21            32
    y#4#8#4   BigM_174             1
    y#4#8#4   valid_6             40
    y#4#8#4   balan@27            40
    y#4#8#4   balan@22            32
    y#4#8#5   BigM_175             1
    y#4#8#5   valid_6             40
    y#4#8#5   balan@28            40
    y#4#8#5   balan@23            32
    y#4#9#1   BigM_176             1
    y#4#9#1   valid_6             59
    y#4#9#1   balan@24            59
    y#4#9#1   balan@1f            13
    y#4#9#2   BigM_177             1
    y#4#9#2   valid_6             59
    y#4#9#2   balan@25            59
    y#4#9#2   balan@20            13
    y#4#9#3   BigM_178             1
    y#4#9#3   valid_6             59
    y#4#9#3   balan@26            59
    y#4#9#3   balan@21            13
    y#4#9#4   BigM_179             1
    y#4#9#4   valid_6             59
    y#4#9#4   balan@27            59
    y#4#9#4   balan@22            13
    y#4#9#5   BigM_180             1
    y#4#9#5   valid_6             59
    y#4#9#5   balan@28            59
    y#4#9#5   balan@23            13
    p#1       BigM_140         -1000
    p#1       BigM_139         -1000
    p#1       BigM_138         -1000
    p#1       BigM_137         -1000
    p#1       BigM_136         -1000
    p#1       BigM_95          -1000
    p#1       BigM_94          -1000
    p#1       BigM_93          -1000
    p#1       BigM_92          -1000
    p#1       BigM_91          -1000
    p#1       BigM_50          -1000
    p#1       BigM_49          -1000
    p#1       BigM_48          -1000
    p#1       BigM_47          -1000
    p#1       BigM_46          -1000
    p#1       BigM_5           -1000
    p#1       BigM_4           -1000
    p#1       BigM_3           -1000
    p#1       BigM_2           -1000
    p#1       BigM_1           -1000
    p#1       select_1             1
    p#2       BigM_145         -1000
    p#2       BigM_144         -1000
    p#2       BigM_143         -1000
    p#2       BigM_142         -1000
    p#2       BigM_141         -1000
    p#2       BigM_100         -1000
    p#2       BigM_99          -1000
    p#2       BigM_98          -1000
    p#2       BigM_97          -1000
    p#2       BigM_96          -1000
    p#2       BigM_55          -1000
    p#2       BigM_54          -1000
    p#2       BigM_53          -1000
    p#2       BigM_52          -1000
    p#2       BigM_51          -1000
    p#2       BigM_10          -1000
    p#2       BigM_9           -1000
    p#2       BigM_8           -1000
    p#2       BigM_7           -1000
    p#2       BigM_6           -1000
    p#2       select_1             1
    p#3       BigM_150         -1000
    p#3       BigM_149         -1000
    p#3       BigM_148         -1000
    p#3       BigM_147         -1000
    p#3       BigM_146         -1000
    p#3       BigM_105         -1000
    p#3       BigM_104         -1000
    p#3       BigM_103         -1000
    p#3       BigM_102         -1000
    p#3       BigM_101         -1000
    p#3       BigM_60          -1000
    p#3       BigM_59          -1000
    p#3       BigM_58          -1000
    p#3       BigM_57          -1000
    p#3       BigM_56          -1000
    p#3       BigM_15          -1000
    p#3       BigM_14          -1000
    p#3       BigM_13          -1000
    p#3       BigM_12          -1000
    p#3       BigM_11          -1000
    p#3       select_1             1
    p#4       BigM_155         -1000
    p#4       BigM_154         -1000
    p#4       BigM_153         -1000
    p#4       BigM_152         -1000
    p#4       BigM_151         -1000
    p#4       BigM_110         -1000
    p#4       BigM_109         -1000
    p#4       BigM_108         -1000
    p#4       BigM_107         -1000
    p#4       BigM_106         -1000
    p#4       BigM_65          -1000
    p#4       BigM_64          -1000
    p#4       BigM_63          -1000
    p#4       BigM_62          -1000
    p#4       BigM_61          -1000
    p#4       BigM_20          -1000
    p#4       BigM_19          -1000
    p#4       BigM_18          -1000
    p#4       BigM_17          -1000
    p#4       BigM_16          -1000
    p#4       select_1             1
    p#5       BigM_160         -1000
    p#5       BigM_159         -1000
    p#5       BigM_158         -1000
    p#5       BigM_157         -1000
    p#5       BigM_156         -1000
    p#5       BigM_115         -1000
    p#5       BigM_114         -1000
    p#5       BigM_113         -1000
    p#5       BigM_112         -1000
    p#5       BigM_111         -1000
    p#5       BigM_70          -1000
    p#5       BigM_69          -1000
    p#5       BigM_68          -1000
    p#5       BigM_67          -1000
    p#5       BigM_66          -1000
    p#5       BigM_25          -1000
    p#5       BigM_24          -1000
    p#5       BigM_23          -1000
    p#5       BigM_22          -1000
    p#5       BigM_21          -1000
    p#5       select_1             1
    p#6       BigM_165         -1000
    p#6       BigM_164         -1000
    p#6       BigM_163         -1000
    p#6       BigM_162         -1000
    p#6       BigM_161         -1000
    p#6       BigM_120         -1000
    p#6       BigM_119         -1000
    p#6       BigM_118         -1000
    p#6       BigM_117         -1000
    p#6       BigM_116         -1000
    p#6       BigM_75          -1000
    p#6       BigM_74          -1000
    p#6       BigM_73          -1000
    p#6       BigM_72          -1000
    p#6       BigM_71          -1000
    p#6       BigM_30          -1000
    p#6       BigM_29          -1000
    p#6       BigM_28          -1000
    p#6       BigM_27          -1000
    p#6       BigM_26          -1000
    p#6       select_1             1
    p#7       BigM_170         -1000
    p#7       BigM_169         -1000
    p#7       BigM_168         -1000
    p#7       BigM_167         -1000
    p#7       BigM_166         -1000
    p#7       BigM_125         -1000
    p#7       BigM_124         -1000
    p#7       BigM_123         -1000
    p#7       BigM_122         -1000
    p#7       BigM_121         -1000
    p#7       BigM_80          -1000
    p#7       BigM_79          -1000
    p#7       BigM_78          -1000
    p#7       BigM_77          -1000
    p#7       BigM_76          -1000
    p#7       BigM_35          -1000
    p#7       BigM_34          -1000
    p#7       BigM_33          -1000
    p#7       BigM_32          -1000
    p#7       BigM_31          -1000
    p#7       select_1             1
    p#8       BigM_175         -1000
    p#8       BigM_174         -1000
    p#8       BigM_173         -1000
    p#8       BigM_172         -1000
    p#8       BigM_171         -1000
    p#8       BigM_130         -1000
    p#8       BigM_129         -1000
    p#8       BigM_128         -1000
    p#8       BigM_127         -1000
    p#8       BigM_126         -1000
    p#8       BigM_85          -1000
    p#8       BigM_84          -1000
    p#8       BigM_83          -1000
    p#8       BigM_82          -1000
    p#8       BigM_81          -1000
    p#8       BigM_40          -1000
    p#8       BigM_39          -1000
    p#8       BigM_38          -1000
    p#8       BigM_37          -1000
    p#8       BigM_36          -1000
    p#8       select_1             1
    p#9       BigM_180         -1000
    p#9       BigM_179         -1000
    p#9       BigM_178         -1000
    p#9       BigM_177         -1000
    p#9       BigM_176         -1000
    p#9       BigM_135         -1000
    p#9       BigM_134         -1000
    p#9       BigM_133         -1000
    p#9       BigM_132         -1000
    p#9       BigM_131         -1000
    p#9       BigM_90          -1000
    p#9       BigM_89          -1000
    p#9       BigM_88          -1000
    p#9       BigM_87          -1000
    p#9       BigM_86          -1000
    p#9       BigM_45          -1000
    p#9       BigM_44          -1000
    p#9       BigM_43          -1000
    p#9       BigM_42          -1000
    p#9       BigM_41          -1000
    p#9       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    B#1#1#0   init2_1              1
    B#1#1#0   balanc@1            -1
    B#1#1#1   OBJECTIV             5
    B#1#1#1   balanc@2            -1
    B#1#1#1   balanc@1             1
    B#1#1#2   OBJECTIV             5
    B#1#1#2   balanc@3            -1
    B#1#1#2   balanc@2             1
    B#1#1#3   OBJECTIV             5
    B#1#1#3   balanc@4            -1
    B#1#1#3   balanc@3             1
    B#1#1#4   OBJECTIV             5
    B#1#1#4   balanc@5            -1
    B#1#1#4   balanc@4             1
    B#1#1#5   OBJECTIV             5
    B#1#1#5   init3_1              1
    B#1#1#5   balanc@5             1
    B#1#2#0   init2_2              1
    B#1#2#0   balanc@6            -1
    B#1#2#1   OBJECTIV           5.5
    B#1#2#1   balanc@7            -1
    B#1#2#1   balanc@6             1
    B#1#2#2   OBJECTIV           5.5
    B#1#2#2   balanc@8            -1
    B#1#2#2   balanc@7             1
    B#1#2#3   OBJECTIV           5.5
    B#1#2#3   balanc@9            -1
    B#1#2#3   balanc@8             1
    B#1#2#4   OBJECTIV           5.5
    B#1#2#4   balanc@a            -1
    B#1#2#4   balanc@9             1
    B#1#2#5   OBJECTIV           5.5
    B#1#2#5   init3_2              1
    B#1#2#5   balanc@a             1
    B#2#1#0   init2_3              1
    B#2#1#0   balanc@b            -1
    B#2#1#1   OBJECTIV             5
    B#2#1#1   balanc@c            -1
    B#2#1#1   balanc@b             1
    B#2#1#2   OBJECTIV             5
    B#2#1#2   balanc@d            -1
    B#2#1#2   balanc@c             1
    B#2#1#3   OBJECTIV             5
    B#2#1#3   balanc@e            -1
    B#2#1#3   balanc@d             1
    B#2#1#4   OBJECTIV             5
    B#2#1#4   balanc@f            -1
    B#2#1#4   balanc@e             1
    B#2#1#5   OBJECTIV             5
    B#2#1#5   init3_3              1
    B#2#1#5   balanc@f             1
    B#2#2#0   init2_4              1
    B#2#2#0   balan@10            -1
    B#2#2#1   OBJECTIV           5.5
    B#2#2#1   balan@11            -1
    B#2#2#1   balan@10             1
    B#2#2#2   OBJECTIV           5.5
    B#2#2#2   balan@12            -1
    B#2#2#2   balan@11             1
    B#2#2#3   OBJECTIV           5.5
    B#2#2#3   balan@13            -1
    B#2#2#3   balan@12             1
    B#2#2#4   OBJECTIV           5.5
    B#2#2#4   balan@14            -1
    B#2#2#4   balan@13             1
    B#2#2#5   OBJECTIV           5.5
    B#2#2#5   init3_4              1
    B#2#2#5   balan@14             1
    B#3#1#0   init2_5              1
    B#3#1#0   balan@15            -1
    B#3#1#1   OBJECTIV             5
    B#3#1#1   balan@16            -1
    B#3#1#1   balan@15             1
    B#3#1#2   OBJECTIV             5
    B#3#1#2   balan@17            -1
    B#3#1#2   balan@16             1
    B#3#1#3   OBJECTIV             5
    B#3#1#3   balan@18            -1
    B#3#1#3   balan@17             1
    B#3#1#4   OBJECTIV             5
    B#3#1#4   balan@19            -1
    B#3#1#4   balan@18             1
    B#3#1#5   OBJECTIV             5
    B#3#1#5   init3_5              1
    B#3#1#5   balan@19             1
    B#3#2#0   init2_6              1
    B#3#2#0   balan@1a            -1
    B#3#2#1   OBJECTIV           5.5
    B#3#2#1   balan@1b            -1
    B#3#2#1   balan@1a             1
    B#3#2#2   OBJECTIV           5.5
    B#3#2#2   balan@1c            -1
    B#3#2#2   balan@1b             1
    B#3#2#3   OBJECTIV           5.5
    B#3#2#3   balan@1d            -1
    B#3#2#3   balan@1c             1
    B#3#2#4   OBJECTIV           5.5
    B#3#2#4   balan@1e            -1
    B#3#2#4   balan@1d             1
    B#3#2#5   OBJECTIV           5.5
    B#3#2#5   init3_6              1
    B#3#2#5   balan@1e             1
    B#4#1#0   init2_7              1
    B#4#1#0   balan@1f            -1
    B#4#1#1   OBJECTIV             5
    B#4#1#1   balan@20            -1
    B#4#1#1   balan@1f             1
    B#4#1#2   OBJECTIV             5
    B#4#1#2   balan@21            -1
    B#4#1#2   balan@20             1
    B#4#1#3   OBJECTIV             5
    B#4#1#3   balan@22            -1
    B#4#1#3   balan@21             1
    B#4#1#4   OBJECTIV             5
    B#4#1#4   balan@23            -1
    B#4#1#4   balan@22             1
    B#4#1#5   OBJECTIV             5
    B#4#1#5   init3_7              1
    B#4#1#5   balan@23             1
    B#4#2#0   init2_8              1
    B#4#2#0   balan@24            -1
    B#4#2#1   OBJECTIV           5.5
    B#4#2#1   balan@25            -1
    B#4#2#1   balan@24             1
    B#4#2#2   OBJECTIV           5.5
    B#4#2#2   balan@26            -1
    B#4#2#2   balan@25             1
    B#4#2#3   OBJECTIV           5.5
    B#4#2#3   balan@27            -1
    B#4#2#3   balan@26             1
    B#4#2#4   OBJECTIV           5.5
    B#4#2#4   balan@28            -1
    B#4#2#4   balan@27             1
    B#4#2#5   OBJECTIV           5.5
    B#4#2#5   init3_8              1
    B#4#2#5   balan@28             1
    I#1#1#0   init1_1              1
    I#1#1#0   balanc@1             1
    I#1#1#1   OBJECTIV             1
    I#1#1#1   balanc@2             1
    I#1#1#1   balanc@1            -1
    I#1#1#2   OBJECTIV             1
    I#1#1#2   balanc@3             1
    I#1#1#2   balanc@2            -1
    I#1#1#3   OBJECTIV             1
    I#1#1#3   balanc@4             1
    I#1#1#3   balanc@3            -1
    I#1#1#4   OBJECTIV             1
    I#1#1#4   balanc@5             1
    I#1#1#4   balanc@4            -1
    I#1#1#5   OBJECTIV             1
    I#1#1#5   balanc@5            -1
    I#1#2#0   init1_2              1
    I#1#2#0   balanc@6             1
    I#1#2#1   OBJECTIV           1.1
    I#1#2#1   balanc@7             1
    I#1#2#1   balanc@6            -1
    I#1#2#2   OBJECTIV           1.1
    I#1#2#2   balanc@8             1
    I#1#2#2   balanc@7            -1
    I#1#2#3   OBJECTIV           1.1
    I#1#2#3   balanc@9             1
    I#1#2#3   balanc@8            -1
    I#1#2#4   OBJECTIV           1.1
    I#1#2#4   balanc@a             1
    I#1#2#4   balanc@9            -1
    I#1#2#5   OBJECTIV           1.1
    I#1#2#5   balanc@a            -1
    I#2#1#0   init1_3              1
    I#2#1#0   balanc@b             1
    I#2#1#1   OBJECTIV             1
    I#2#1#1   balanc@c             1
    I#2#1#1   balanc@b            -1
    I#2#1#2   OBJECTIV             1
    I#2#1#2   balanc@d             1
    I#2#1#2   balanc@c            -1
    I#2#1#3   OBJECTIV             1
    I#2#1#3   balanc@e             1
    I#2#1#3   balanc@d            -1
    I#2#1#4   OBJECTIV             1
    I#2#1#4   balanc@f             1
    I#2#1#4   balanc@e            -1
    I#2#1#5   OBJECTIV             1
    I#2#1#5   balanc@f            -1
    I#2#2#0   init1_4              1
    I#2#2#0   balan@10             1
    I#2#2#1   OBJECTIV           1.1
    I#2#2#1   balan@11             1
    I#2#2#1   balan@10            -1
    I#2#2#2   OBJECTIV           1.1
    I#2#2#2   balan@12             1
    I#2#2#2   balan@11            -1
    I#2#2#3   OBJECTIV           1.1
    I#2#2#3   balan@13             1
    I#2#2#3   balan@12            -1
    I#2#2#4   OBJECTIV           1.1
    I#2#2#4   balan@14             1
    I#2#2#4   balan@13            -1
    I#2#2#5   OBJECTIV           1.1
    I#2#2#5   balan@14            -1
    I#3#1#0   init1_5              1
    I#3#1#0   balan@15             1
    I#3#1#1   OBJECTIV             1
    I#3#1#1   balan@16             1
    I#3#1#1   balan@15            -1
    I#3#1#2   OBJECTIV             1
    I#3#1#2   balan@17             1
    I#3#1#2   balan@16            -1
    I#3#1#3   OBJECTIV             1
    I#3#1#3   balan@18             1
    I#3#1#3   balan@17            -1
    I#3#1#4   OBJECTIV             1
    I#3#1#4   balan@19             1
    I#3#1#4   balan@18            -1
    I#3#1#5   OBJECTIV             1
    I#3#1#5   balan@19            -1
    I#3#2#0   init1_6              1
    I#3#2#0   balan@1a             1
    I#3#2#1   OBJECTIV           1.1
    I#3#2#1   balan@1b             1
    I#3#2#1   balan@1a            -1
    I#3#2#2   OBJECTIV           1.1
    I#3#2#2   balan@1c             1
    I#3#2#2   balan@1b            -1
    I#3#2#3   OBJECTIV           1.1
    I#3#2#3   balan@1d             1
    I#3#2#3   balan@1c            -1
    I#3#2#4   OBJECTIV           1.1
    I#3#2#4   balan@1e             1
    I#3#2#4   balan@1d            -1
    I#3#2#5   OBJECTIV           1.1
    I#3#2#5   balan@1e            -1
    I#4#1#0   init1_7              1
    I#4#1#0   balan@1f             1
    I#4#1#1   OBJECTIV             1
    I#4#1#1   balan@20             1
    I#4#1#1   balan@1f            -1
    I#4#1#2   OBJECTIV             1
    I#4#1#2   balan@21             1
    I#4#1#2   balan@20            -1
    I#4#1#3   OBJECTIV             1
    I#4#1#3   balan@22             1
    I#4#1#3   balan@21            -1
    I#4#1#4   OBJECTIV             1
    I#4#1#4   balan@23             1
    I#4#1#4   balan@22            -1
    I#4#1#5   OBJECTIV             1
    I#4#1#5   balan@23            -1
    I#4#2#0   init1_8              1
    I#4#2#0   balan@24             1
    I#4#2#1   OBJECTIV           1.1
    I#4#2#1   balan@25             1
    I#4#2#1   balan@24            -1
    I#4#2#2   OBJECTIV           1.1
    I#4#2#2   balan@26             1
    I#4#2#2   balan@25            -1
    I#4#2#3   OBJECTIV           1.1
    I#4#2#3   balan@27             1
    I#4#2#3   balan@26            -1
    I#4#2#4   OBJECTIV           1.1
    I#4#2#4   balan@28             1
    I#4#2#4   balan@27            -1
    I#4#2#5   OBJECTIV           1.1
    I#4#2#5   balan@28            -1
RHS
    RHS       select_1             1
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@4           669
    RHS       balanc@5           180
    RHS       balanc@b           333
    RHS       balanc@c           776
    RHS       balanc@d           466
    RHS       balanc@e           764
    RHS       balanc@f           166
    RHS       balan@10           239
    RHS       balan@11           425
    RHS       balan@12           220
    RHS       balan@13           452
    RHS       balan@14           519
    RHS       balan@15           136
    RHS       balan@16           621
    RHS       balan@17           192
    RHS       balan@18            74
    RHS       balan@19           510
    RHS       balan@1a             7
    RHS       balan@1b            27
    RHS       balan@1c           934
    RHS       balan@1d           620
    RHS       balan@1e           585
    RHS       balan@24           914
    RHS       balan@25           988
    RHS       balan@26           465
    RHS       balan@27           318
    RHS       balan@28           243
    RHS       valid_1           2171
    RHS       valid_2           2505
    RHS       valid_3           1855
    RHS       valid_4           1533
    RHS       valid_5           2173
    RHS       valid_6           2928
BOUNDS
 LO BOUND     B#1#1#0              0
 PL BOUND     B#1#1#0 
 LO BOUND     B#1#1#1              0
 PL BOUND     B#1#1#1 
 LO BOUND     B#1#1#2              0
 PL BOUND     B#1#1#2 
 LO BOUND     B#1#1#3              0
 PL BOUND     B#1#1#3 
 LO BOUND     B#1#1#4              0
 PL BOUND     B#1#1#4 
 LO BOUND     B#1#1#5              0
 PL BOUND     B#1#1#5 
 LO BOUND     B#1#2#0              0
 PL BOUND     B#1#2#0 
 LO BOUND     B#1#2#1              0
 PL BOUND     B#1#2#1 
 LO BOUND     B#1#2#2              0
 PL BOUND     B#1#2#2 
 LO BOUND     B#1#2#3              0
 PL BOUND     B#1#2#3 
 LO BOUND     B#1#2#4              0
 PL BOUND     B#1#2#4 
 LO BOUND     B#1#2#5              0
 PL BOUND     B#1#2#5 
 LO BOUND     B#2#1#0              0
 PL BOUND     B#2#1#0 
 LO BOUND     B#2#1#1              0
 PL BOUND     B#2#1#1 
 LO BOUND     B#2#1#2              0
 PL BOUND     B#2#1#2 
 LO BOUND     B#2#1#3              0
 PL BOUND     B#2#1#3 
 LO BOUND     B#2#1#4              0
 PL BOUND     B#2#1#4 
 LO BOUND     B#2#1#5              0
 PL BOUND     B#2#1#5 
 LO BOUND     B#2#2#0              0
 PL BOUND     B#2#2#0 
 LO BOUND     B#2#2#1              0
 PL BOUND     B#2#2#1 
 LO BOUND     B#2#2#2              0
 PL BOUND     B#2#2#2 
 LO BOUND     B#2#2#3              0
 PL BOUND     B#2#2#3 
 LO BOUND     B#2#2#4              0
 PL BOUND     B#2#2#4 
 LO BOUND     B#2#2#5              0
 PL BOUND     B#2#2#5 
 LO BOUND     B#3#1#0              0
 PL BOUND     B#3#1#0 
 LO BOUND     B#3#1#1              0
 PL BOUND     B#3#1#1 
 LO BOUND     B#3#1#2              0
 PL BOUND     B#3#1#2 
 LO BOUND     B#3#1#3              0
 PL BOUND     B#3#1#3 
 LO BOUND     B#3#1#4              0
 PL BOUND     B#3#1#4 
 LO BOUND     B#3#1#5              0
 PL BOUND     B#3#1#5 
 LO BOUND     B#3#2#0              0
 PL BOUND     B#3#2#0 
 LO BOUND     B#3#2#1              0
 PL BOUND     B#3#2#1 
 LO BOUND     B#3#2#2              0
 PL BOUND     B#3#2#2 
 LO BOUND     B#3#2#3              0
 PL BOUND     B#3#2#3 
 LO BOUND     B#3#2#4              0
 PL BOUND     B#3#2#4 
 LO BOUND     B#3#2#5              0
 PL BOUND     B#3#2#5 
 LO BOUND     B#4#1#0              0
 PL BOUND     B#4#1#0 
 LO BOUND     B#4#1#1              0
 PL BOUND     B#4#1#1 
 LO BOUND     B#4#1#2              0
 PL BOUND     B#4#1#2 
 LO BOUND     B#4#1#3              0
 PL BOUND     B#4#1#3 
 LO BOUND     B#4#1#4              0
 PL BOUND     B#4#1#4 
 LO BOUND     B#4#1#5              0
 PL BOUND     B#4#1#5 
 LO BOUND     B#4#2#0              0
 PL BOUND     B#4#2#0 
 LO BOUND     B#4#2#1              0
 PL BOUND     B#4#2#1 
 LO BOUND     B#4#2#2              0
 PL BOUND     B#4#2#2 
 LO BOUND     B#4#2#3              0
 PL BOUND     B#4#2#3 
 LO BOUND     B#4#2#4              0
 PL BOUND     B#4#2#4 
 LO BOUND     B#4#2#5              0
 PL BOUND     B#4#2#5 
 LO BOUND     I#1#1#0              0
 PL BOUND     I#1#1#0 
 LO BOUND     I#1#1#1              0
 PL BOUND     I#1#1#1 
 LO BOUND     I#1#1#2              0
 PL BOUND     I#1#1#2 
 LO BOUND     I#1#1#3              0
 PL BOUND     I#1#1#3 
 LO BOUND     I#1#1#4              0
 PL BOUND     I#1#1#4 
 LO BOUND     I#1#1#5              0
 PL BOUND     I#1#1#5 
 LO BOUND     I#1#2#0              0
 PL BOUND     I#1#2#0 
 LO BOUND     I#1#2#1              0
 PL BOUND     I#1#2#1 
 LO BOUND     I#1#2#2              0
 PL BOUND     I#1#2#2 
 LO BOUND     I#1#2#3              0
 PL BOUND     I#1#2#3 
 LO BOUND     I#1#2#4              0
 PL BOUND     I#1#2#4 
 LO BOUND     I#1#2#5              0
 PL BOUND     I#1#2#5 
 LO BOUND     I#2#1#0              0
 PL BOUND     I#2#1#0 
 LO BOUND     I#2#1#1              0
 PL BOUND     I#2#1#1 
 LO BOUND     I#2#1#2              0
 PL BOUND     I#2#1#2 
 LO BOUND     I#2#1#3              0
 PL BOUND     I#2#1#3 
 LO BOUND     I#2#1#4              0
 PL BOUND     I#2#1#4 
 LO BOUND     I#2#1#5              0
 PL BOUND     I#2#1#5 
 LO BOUND     I#2#2#0              0
 PL BOUND     I#2#2#0 
 LO BOUND     I#2#2#1              0
 PL BOUND     I#2#2#1 
 LO BOUND     I#2#2#2              0
 PL BOUND     I#2#2#2 
 LO BOUND     I#2#2#3              0
 PL BOUND     I#2#2#3 
 LO BOUND     I#2#2#4              0
 PL BOUND     I#2#2#4 
 LO BOUND     I#2#2#5              0
 PL BOUND     I#2#2#5 
 LO BOUND     I#3#1#0              0
 PL BOUND     I#3#1#0 
 LO BOUND     I#3#1#1              0
 PL BOUND     I#3#1#1 
 LO BOUND     I#3#1#2              0
 PL BOUND     I#3#1#2 
 LO BOUND     I#3#1#3              0
 PL BOUND     I#3#1#3 
 LO BOUND     I#3#1#4              0
 PL BOUND     I#3#1#4 
 LO BOUND     I#3#1#5              0
 PL BOUND     I#3#1#5 
 LO BOUND     I#3#2#0              0
 PL BOUND     I#3#2#0 
 LO BOUND     I#3#2#1              0
 PL BOUND     I#3#2#1 
 LO BOUND     I#3#2#2              0
 PL BOUND     I#3#2#2 
 LO BOUND     I#3#2#3              0
 PL BOUND     I#3#2#3 
 LO BOUND     I#3#2#4              0
 PL BOUND     I#3#2#4 
 LO BOUND     I#3#2#5              0
 PL BOUND     I#3#2#5 
 LO BOUND     I#4#1#0              0
 PL BOUND     I#4#1#0 
 LO BOUND     I#4#1#1              0
 PL BOUND     I#4#1#1 
 LO BOUND     I#4#1#2              0
 PL BOUND     I#4#1#2 
 LO BOUND     I#4#1#3              0
 PL BOUND     I#4#1#3 
 LO BOUND     I#4#1#4              0
 PL BOUND     I#4#1#4 
 LO BOUND     I#4#1#5              0
 PL BOUND     I#4#1#5 
 LO BOUND     I#4#2#0              0
 PL BOUND     I#4#2#0 
 LO BOUND     I#4#2#1              0
 PL BOUND     I#4#2#1 
 LO BOUND     I#4#2#2              0
 PL BOUND     I#4#2#2 
 LO BOUND     I#4#2#3              0
 PL BOUND     I#4#2#3 
 LO BOUND     I#4#2#4              0
 PL BOUND     I#4#2#4 
 LO BOUND     I#4#2#5              0
 PL BOUND     I#4#2#5 
 LO BOUND     f#1#1#1              0
 PL BOUND     f#1#1#1 
 LO BOUND     f#1#1#2              0
 PL BOUND     f#1#1#2 
 LO BOUND     f#1#1#3              0
 PL BOUND     f#1#1#3 
 LO BOUND     f#1#1#4              0
 PL BOUND     f#1#1#4 
 LO BOUND     f#1#1#5              0
 PL BOUND     f#1#1#5 
 LO BOUND     f#1#2#1              0
 PL BOUND     f#1#2#1 
 LO BOUND     f#1#2#2              0
 PL BOUND     f#1#2#2 
 LO BOUND     f#1#2#3              0
 PL BOUND     f#1#2#3 
 LO BOUND     f#1#2#4              0
 PL BOUND     f#1#2#4 
 LO BOUND     f#1#2#5              0
 PL BOUND     f#1#2#5 
 LO BOUND     f#2#1#1              0
 PL BOUND     f#2#1#1 
 LO BOUND     f#2#1#2              0
 PL BOUND     f#2#1#2 
 LO BOUND     f#2#1#3              0
 PL BOUND     f#2#1#3 
 LO BOUND     f#2#1#4              0
 PL BOUND     f#2#1#4 
 LO BOUND     f#2#1#5              0
 PL BOUND     f#2#1#5 
 LO BOUND     f#2#2#1              0
 PL BOUND     f#2#2#1 
 LO BOUND     f#2#2#2              0
 PL BOUND     f#2#2#2 
 LO BOUND     f#2#2#3              0
 PL BOUND     f#2#2#3 
 LO BOUND     f#2#2#4              0
 PL BOUND     f#2#2#4 
 LO BOUND     f#2#2#5              0
 PL BOUND     f#2#2#5 
 LO BOUND     f#3#1#1              0
 PL BOUND     f#3#1#1 
 LO BOUND     f#3#1#2              0
 PL BOUND     f#3#1#2 
 LO BOUND     f#3#1#3              0
 PL BOUND     f#3#1#3 
 LO BOUND     f#3#1#4              0
 PL BOUND     f#3#1#4 
 LO BOUND     f#3#1#5              0
 PL BOUND     f#3#1#5 
 LO BOUND     f#3#2#1              0
 PL BOUND     f#3#2#1 
 LO BOUND     f#3#2#2              0
 PL BOUND     f#3#2#2 
 LO BOUND     f#3#2#3              0
 PL BOUND     f#3#2#3 
 LO BOUND     f#3#2#4              0
 PL BOUND     f#3#2#4 
 LO BOUND     f#3#2#5              0
 PL BOUND     f#3#2#5 
 LO BOUND     f#4#1#1              0
 PL BOUND     f#4#1#1 
 LO BOUND     f#4#1#2              0
 PL BOUND     f#4#1#2 
 LO BOUND     f#4#1#3              0
 PL BOUND     f#4#1#3 
 LO BOUND     f#4#1#4              0
 PL BOUND     f#4#1#4 
 LO BOUND     f#4#1#5              0
 PL BOUND     f#4#1#5 
 LO BOUND     f#4#2#1              0
 PL BOUND     f#4#2#1 
 LO BOUND     f#4#2#2              0
 PL BOUND     f#4#2#2 
 LO BOUND     f#4#2#3              0
 PL BOUND     f#4#2#3 
 LO BOUND     f#4#2#4              0
 PL BOUND     f#4#2#4 
 LO BOUND     f#4#2#5              0
 PL BOUND     f#4#2#5 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#1#4              0
 PL BOUND     y#1#1#4 
 LO BOUND     y#1#1#5              0
 PL BOUND     y#1#1#5 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#2#4              0
 PL BOUND     y#1#2#4 
 LO BOUND     y#1#2#5              0
 PL BOUND     y#1#2#5 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#3#4              0
 PL BOUND     y#1#3#4 
 LO BOUND     y#1#3#5              0
 PL BOUND     y#1#3#5 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#4#4              0
 PL BOUND     y#1#4#4 
 LO BOUND     y#1#4#5              0
 PL BOUND     y#1#4#5 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#5#4              0
 PL BOUND     y#1#5#4 
 LO BOUND     y#1#5#5              0
 PL BOUND     y#1#5#5 
 LO BOUND     y#1#6#1              0
 PL BOUND     y#1#6#1 
 LO BOUND     y#1#6#2              0
 PL BOUND     y#1#6#2 
 LO BOUND     y#1#6#3              0
 PL BOUND     y#1#6#3 
 LO BOUND     y#1#6#4              0
 PL BOUND     y#1#6#4 
 LO BOUND     y#1#6#5              0
 PL BOUND     y#1#6#5 
 LO BOUND     y#1#7#1              0
 PL BOUND     y#1#7#1 
 LO BOUND     y#1#7#2              0
 PL BOUND     y#1#7#2 
 LO BOUND     y#1#7#3              0
 PL BOUND     y#1#7#3 
 LO BOUND     y#1#7#4              0
 PL BOUND     y#1#7#4 
 LO BOUND     y#1#7#5              0
 PL BOUND     y#1#7#5 
 LO BOUND     y#1#8#1              0
 PL BOUND     y#1#8#1 
 LO BOUND     y#1#8#2              0
 PL BOUND     y#1#8#2 
 LO BOUND     y#1#8#3              0
 PL BOUND     y#1#8#3 
 LO BOUND     y#1#8#4              0
 PL BOUND     y#1#8#4 
 LO BOUND     y#1#8#5              0
 PL BOUND     y#1#8#5 
 LO BOUND     y#1#9#1              0
 PL BOUND     y#1#9#1 
 LO BOUND     y#1#9#2              0
 PL BOUND     y#1#9#2 
 LO BOUND     y#1#9#3              0
 PL BOUND     y#1#9#3 
 LO BOUND     y#1#9#4              0
 PL BOUND     y#1#9#4 
 LO BOUND     y#1#9#5              0
 PL BOUND     y#1#9#5 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#1#4              0
 PL BOUND     y#2#1#4 
 LO BOUND     y#2#1#5              0
 PL BOUND     y#2#1#5 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#2#4              0
 PL BOUND     y#2#2#4 
 LO BOUND     y#2#2#5              0
 PL BOUND     y#2#2#5 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#3#4              0
 PL BOUND     y#2#3#4 
 LO BOUND     y#2#3#5              0
 PL BOUND     y#2#3#5 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#4#4              0
 PL BOUND     y#2#4#4 
 LO BOUND     y#2#4#5              0
 PL BOUND     y#2#4#5 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#5#4              0
 PL BOUND     y#2#5#4 
 LO BOUND     y#2#5#5              0
 PL BOUND     y#2#5#5 
 LO BOUND     y#2#6#1              0
 PL BOUND     y#2#6#1 
 LO BOUND     y#2#6#2              0
 PL BOUND     y#2#6#2 
 LO BOUND     y#2#6#3              0
 PL BOUND     y#2#6#3 
 LO BOUND     y#2#6#4              0
 PL BOUND     y#2#6#4 
 LO BOUND     y#2#6#5              0
 PL BOUND     y#2#6#5 
 LO BOUND     y#2#7#1              0
 PL BOUND     y#2#7#1 
 LO BOUND     y#2#7#2              0
 PL BOUND     y#2#7#2 
 LO BOUND     y#2#7#3              0
 PL BOUND     y#2#7#3 
 LO BOUND     y#2#7#4              0
 PL BOUND     y#2#7#4 
 LO BOUND     y#2#7#5              0
 PL BOUND     y#2#7#5 
 LO BOUND     y#2#8#1              0
 PL BOUND     y#2#8#1 
 LO BOUND     y#2#8#2              0
 PL BOUND     y#2#8#2 
 LO BOUND     y#2#8#3              0
 PL BOUND     y#2#8#3 
 LO BOUND     y#2#8#4              0
 PL BOUND     y#2#8#4 
 LO BOUND     y#2#8#5              0
 PL BOUND     y#2#8#5 
 LO BOUND     y#2#9#1              0
 PL BOUND     y#2#9#1 
 LO BOUND     y#2#9#2              0
 PL BOUND     y#2#9#2 
 LO BOUND     y#2#9#3              0
 PL BOUND     y#2#9#3 
 LO BOUND     y#2#9#4              0
 PL BOUND     y#2#9#4 
 LO BOUND     y#2#9#5              0
 PL BOUND     y#2#9#5 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#1#4              0
 PL BOUND     y#3#1#4 
 LO BOUND     y#3#1#5              0
 PL BOUND     y#3#1#5 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#2#4              0
 PL BOUND     y#3#2#4 
 LO BOUND     y#3#2#5              0
 PL BOUND     y#3#2#5 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#3#4              0
 PL BOUND     y#3#3#4 
 LO BOUND     y#3#3#5              0
 PL BOUND     y#3#3#5 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#4#4              0
 PL BOUND     y#3#4#4 
 LO BOUND     y#3#4#5              0
 PL BOUND     y#3#4#5 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#5#4              0
 PL BOUND     y#3#5#4 
 LO BOUND     y#3#5#5              0
 PL BOUND     y#3#5#5 
 LO BOUND     y#3#6#1              0
 PL BOUND     y#3#6#1 
 LO BOUND     y#3#6#2              0
 PL BOUND     y#3#6#2 
 LO BOUND     y#3#6#3              0
 PL BOUND     y#3#6#3 
 LO BOUND     y#3#6#4              0
 PL BOUND     y#3#6#4 
 LO BOUND     y#3#6#5              0
 PL BOUND     y#3#6#5 
 LO BOUND     y#3#7#1              0
 PL BOUND     y#3#7#1 
 LO BOUND     y#3#7#2              0
 PL BOUND     y#3#7#2 
 LO BOUND     y#3#7#3              0
 PL BOUND     y#3#7#3 
 LO BOUND     y#3#7#4              0
 PL BOUND     y#3#7#4 
 LO BOUND     y#3#7#5              0
 PL BOUND     y#3#7#5 
 LO BOUND     y#3#8#1              0
 PL BOUND     y#3#8#1 
 LO BOUND     y#3#8#2              0
 PL BOUND     y#3#8#2 
 LO BOUND     y#3#8#3              0
 PL BOUND     y#3#8#3 
 LO BOUND     y#3#8#4              0
 PL BOUND     y#3#8#4 
 LO BOUND     y#3#8#5              0
 PL BOUND     y#3#8#5 
 LO BOUND     y#3#9#1              0
 PL BOUND     y#3#9#1 
 LO BOUND     y#3#9#2              0
 PL BOUND     y#3#9#2 
 LO BOUND     y#3#9#3              0
 PL BOUND     y#3#9#3 
 LO BOUND     y#3#9#4              0
 PL BOUND     y#3#9#4 
 LO BOUND     y#3#9#5              0
 PL BOUND     y#3#9#5 
 LO BOUND     y#4#1#1              0
 PL BOUND     y#4#1#1 
 LO BOUND     y#4#1#2              0
 PL BOUND     y#4#1#2 
 LO BOUND     y#4#1#3              0
 PL BOUND     y#4#1#3 
 LO BOUND     y#4#1#4              0
 PL BOUND     y#4#1#4 
 LO BOUND     y#4#1#5              0
 PL BOUND     y#4#1#5 
 LO BOUND     y#4#2#1              0
 PL BOUND     y#4#2#1 
 LO BOUND     y#4#2#2              0
 PL BOUND     y#4#2#2 
 LO BOUND     y#4#2#3              0
 PL BOUND     y#4#2#3 
 LO BOUND     y#4#2#4              0
 PL BOUND     y#4#2#4 
 LO BOUND     y#4#2#5              0
 PL BOUND     y#4#2#5 
 LO BOUND     y#4#3#1              0
 PL BOUND     y#4#3#1 
 LO BOUND     y#4#3#2              0
 PL BOUND     y#4#3#2 
 LO BOUND     y#4#3#3              0
 PL BOUND     y#4#3#3 
 LO BOUND     y#4#3#4              0
 PL BOUND     y#4#3#4 
 LO BOUND     y#4#3#5              0
 PL BOUND     y#4#3#5 
 LO BOUND     y#4#4#1              0
 PL BOUND     y#4#4#1 
 LO BOUND     y#4#4#2              0
 PL BOUND     y#4#4#2 
 LO BOUND     y#4#4#3              0
 PL BOUND     y#4#4#3 
 LO BOUND     y#4#4#4              0
 PL BOUND     y#4#4#4 
 LO BOUND     y#4#4#5              0
 PL BOUND     y#4#4#5 
 LO BOUND     y#4#5#1              0
 PL BOUND     y#4#5#1 
 LO BOUND     y#4#5#2              0
 PL BOUND     y#4#5#2 
 LO BOUND     y#4#5#3              0
 PL BOUND     y#4#5#3 
 LO BOUND     y#4#5#4              0
 PL BOUND     y#4#5#4 
 LO BOUND     y#4#5#5              0
 PL BOUND     y#4#5#5 
 LO BOUND     y#4#6#1              0
 PL BOUND     y#4#6#1 
 LO BOUND     y#4#6#2              0
 PL BOUND     y#4#6#2 
 LO BOUND     y#4#6#3              0
 PL BOUND     y#4#6#3 
 LO BOUND     y#4#6#4              0
 PL BOUND     y#4#6#4 
 LO BOUND     y#4#6#5              0
 PL BOUND     y#4#6#5 
 LO BOUND     y#4#7#1              0
 PL BOUND     y#4#7#1 
 LO BOUND     y#4#7#2              0
 PL BOUND     y#4#7#2 
 LO BOUND     y#4#7#3              0
 PL BOUND     y#4#7#3 
 LO BOUND     y#4#7#4              0
 PL BOUND     y#4#7#4 
 LO BOUND     y#4#7#5              0
 PL BOUND     y#4#7#5 
 LO BOUND     y#4#8#1              0
 PL BOUND     y#4#8#1 
 LO BOUND     y#4#8#2              0
 PL BOUND     y#4#8#2 
 LO BOUND     y#4#8#3              0
 PL BOUND     y#4#8#3 
 LO BOUND     y#4#8#4              0
 PL BOUND     y#4#8#4 
 LO BOUND     y#4#8#5              0
 PL BOUND     y#4#8#5 
 LO BOUND     y#4#9#1              0
 PL BOUND     y#4#9#1 
 LO BOUND     y#4#9#2              0
 PL BOUND     y#4#9#2 
 LO BOUND     y#4#9#3              0
 PL BOUND     y#4#9#3 
 LO BOUND     y#4#9#4              0
 PL BOUND     y#4#9#4 
 LO BOUND     y#4#9#5              0
 PL BOUND     y#4#9#5 
 LO BOUND     p#1                  0
 UP BOUND     p#1                  1
 LO BOUND     p#2                  0
 UP BOUND     p#2                  1
 LO BOUND     p#3                  0
 UP BOUND     p#3                  1
 LO BOUND     p#4                  0
 UP BOUND     p#4                  1
 LO BOUND     p#5                  0
 UP BOUND     p#5                  1
 LO BOUND     p#6                  0
 UP BOUND     p#6                  1
 LO BOUND     p#7                  0
 UP BOUND     p#7                  1
 LO BOUND     p#8                  0
 UP BOUND     p#8                  1
 LO BOUND     p#9                  0
 UP BOUND     p#9                  1
ENDATA
