* This file was automatically generated by Zimpl
* param Q2 := 1;
* param M := 1000;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nN := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set N := { 1 .. nN };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[N] := read file1 as "<1n> 2n" skip 1 use nN;
* param backCost[N] := read file1 as "<1n> 2n" skip nN+1 use nN;
* param demand[C*N*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nN+1;
* param q[P*N] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*N] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in N with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <j> in P with q[j,i] > 0 };
* var B[C*N*T0] >= 0;
* var I[C*N*T0] >= 0;
* var f[C*N*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var p[P] binary;
* minimize cost: sum <i> in N: ( sum <t> in T: (sum <c> in C : (inveCost[i] * I[c,i,t]  + backCost[i] * B[c,i,t]) ));
* subto select:       sum <j> in P: p[j] <= m;
* subto balance:    forall <c,i,t> in C*N*T with t>=1 do       I[c,i,t-1] - B[c,i,t-1] + Q1*Q2*f[c,i,t] + Q2 * (sum <j> in Pc[c
* ]: q[j,i] * y[c,j,t]) == demand[c,i,t] + I[c,i,t] - B[c,i,t];
* subto valid:    forall <c,i> in C*N do       sum <t> in T: ( min(Q1, D[c,i]) * f[c,i,t] + sum <j> in Pc[c]: ( min(q[j,i], D[c
* ,i] ) * y[c,j,t]) ) >= D[c,i];
* subto BigM:    forall <c,j,t> in C*P*T with t>=1 do       y[c,j,t] <= M*p[j];
* subto init1:    forall <c,i> in C*N do       I[c,i,0] == 0;
* subto init2:    forall <c,i> in C*N do       B[c,i,0] == 0;
* subto init3:    forall <c,i> in C*N do       B[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 E  balan@25          
 E  balan@26          
 E  balan@27          
 E  balan@28          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 L  BigM_101          
 L  BigM_102          
 L  BigM_103          
 L  BigM_104          
 L  BigM_105          
 L  BigM_106          
 L  BigM_107          
 L  BigM_108          
 L  BigM_109          
 L  BigM_110          
 L  BigM_111          
 L  BigM_112          
 L  BigM_113          
 L  BigM_114          
 L  BigM_115          
 L  BigM_116          
 L  BigM_117          
 L  BigM_118          
 L  BigM_119          
 L  BigM_120          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    f#1#1#1   valid_1             72
    f#1#1#1   balanc@1            72
    f#1#1#2   valid_1             72
    f#1#1#2   balanc@2            72
    f#1#1#3   valid_1             72
    f#1#1#3   balanc@3            72
    f#1#1#4   valid_1             72
    f#1#1#4   balanc@4            72
    f#1#1#5   valid_1             72
    f#1#1#5   balanc@5            72
    f#1#2#1   balanc@6            72
    f#1#2#2   balanc@7            72
    f#1#2#3   balanc@8            72
    f#1#2#4   balanc@9            72
    f#1#2#5   balanc@a            72
    f#2#1#1   valid_2             72
    f#2#1#1   balanc@b            72
    f#2#1#2   valid_2             72
    f#2#1#2   balanc@c            72
    f#2#1#3   valid_2             72
    f#2#1#3   balanc@d            72
    f#2#1#4   valid_2             72
    f#2#1#4   balanc@e            72
    f#2#1#5   valid_2             72
    f#2#1#5   balanc@f            72
    f#2#2#1   valid_3             72
    f#2#2#1   balan@10            72
    f#2#2#2   valid_3             72
    f#2#2#2   balan@11            72
    f#2#2#3   valid_3             72
    f#2#2#3   balan@12            72
    f#2#2#4   valid_3             72
    f#2#2#4   balan@13            72
    f#2#2#5   valid_3             72
    f#2#2#5   balan@14            72
    f#3#1#1   valid_4             72
    f#3#1#1   balan@15            72
    f#3#1#2   valid_4             72
    f#3#1#2   balan@16            72
    f#3#1#3   valid_4             72
    f#3#1#3   balan@17            72
    f#3#1#4   valid_4             72
    f#3#1#4   balan@18            72
    f#3#1#5   valid_4             72
    f#3#1#5   balan@19            72
    f#3#2#1   valid_5             72
    f#3#2#1   balan@1a            72
    f#3#2#2   valid_5             72
    f#3#2#2   balan@1b            72
    f#3#2#3   valid_5             72
    f#3#2#3   balan@1c            72
    f#3#2#4   valid_5             72
    f#3#2#4   balan@1d            72
    f#3#2#5   valid_5             72
    f#3#2#5   balan@1e            72
    f#4#1#1   balan@1f            72
    f#4#1#2   balan@20            72
    f#4#1#3   balan@21            72
    f#4#1#4   balan@22            72
    f#4#1#5   balan@23            72
    f#4#2#1   valid_6             72
    f#4#2#1   balan@24            72
    f#4#2#2   valid_6             72
    f#4#2#2   balan@25            72
    f#4#2#3   valid_6             72
    f#4#2#3   balan@26            72
    f#4#2#4   valid_6             72
    f#4#2#4   balan@27            72
    f#4#2#5   valid_6             72
    f#4#2#5   balan@28            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_1             39
    y#1#1#1   balanc@6            33
    y#1#1#1   balanc@1            39
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_1             39
    y#1#1#2   balanc@7            33
    y#1#1#2   balanc@2            39
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_1             39
    y#1#1#3   balanc@8            33
    y#1#1#3   balanc@3            39
    y#1#1#4   BigM_4               1
    y#1#1#4   valid_1             39
    y#1#1#4   balanc@9            33
    y#1#1#4   balanc@4            39
    y#1#1#5   BigM_5               1
    y#1#1#5   valid_1             39
    y#1#1#5   balanc@a            33
    y#1#1#5   balanc@5            39
    y#1#2#1   BigM_6               1
    y#1#2#1   valid_1             28
    y#1#2#1   balanc@6            44
    y#1#2#1   balanc@1            28
    y#1#2#2   BigM_7               1
    y#1#2#2   valid_1             28
    y#1#2#2   balanc@7            44
    y#1#2#2   balanc@2            28
    y#1#2#3   BigM_8               1
    y#1#2#3   valid_1             28
    y#1#2#3   balanc@8            44
    y#1#2#3   balanc@3            28
    y#1#2#4   BigM_9               1
    y#1#2#4   valid_1             28
    y#1#2#4   balanc@9            44
    y#1#2#4   balanc@4            28
    y#1#2#5   BigM_10              1
    y#1#2#5   valid_1             28
    y#1#2#5   balanc@a            44
    y#1#2#5   balanc@5            28
    y#1#3#1   BigM_11              1
    y#1#3#1   valid_1             37
    y#1#3#1   balanc@6            35
    y#1#3#1   balanc@1            37
    y#1#3#2   BigM_12              1
    y#1#3#2   valid_1             37
    y#1#3#2   balanc@7            35
    y#1#3#2   balanc@2            37
    y#1#3#3   BigM_13              1
    y#1#3#3   valid_1             37
    y#1#3#3   balanc@8            35
    y#1#3#3   balanc@3            37
    y#1#3#4   BigM_14              1
    y#1#3#4   valid_1             37
    y#1#3#4   balanc@9            35
    y#1#3#4   balanc@4            37
    y#1#3#5   BigM_15              1
    y#1#3#5   valid_1             37
    y#1#3#5   balanc@a            35
    y#1#3#5   balanc@5            37
    y#1#4#1   BigM_16              1
    y#1#4#1   valid_1             25
    y#1#4#1   balanc@6            47
    y#1#4#1   balanc@1            25
    y#1#4#2   BigM_17              1
    y#1#4#2   valid_1             25
    y#1#4#2   balanc@7            47
    y#1#4#2   balanc@2            25
    y#1#4#3   BigM_18              1
    y#1#4#3   valid_1             25
    y#1#4#3   balanc@8            47
    y#1#4#3   balanc@3            25
    y#1#4#4   BigM_19              1
    y#1#4#4   valid_1             25
    y#1#4#4   balanc@9            47
    y#1#4#4   balanc@4            25
    y#1#4#5   BigM_20              1
    y#1#4#5   valid_1             25
    y#1#4#5   balanc@a            47
    y#1#4#5   balanc@5            25
    y#1#5#1   BigM_21              1
    y#1#5#1   valid_1             70
    y#1#5#1   balanc@6             2
    y#1#5#1   balanc@1            70
    y#1#5#2   BigM_22              1
    y#1#5#2   valid_1             70
    y#1#5#2   balanc@7             2
    y#1#5#2   balanc@2            70
    y#1#5#3   BigM_23              1
    y#1#5#3   valid_1             70
    y#1#5#3   balanc@8             2
    y#1#5#3   balanc@3            70
    y#1#5#4   BigM_24              1
    y#1#5#4   valid_1             70
    y#1#5#4   balanc@9             2
    y#1#5#4   balanc@4            70
    y#1#5#5   BigM_25              1
    y#1#5#5   valid_1             70
    y#1#5#5   balanc@a             2
    y#1#5#5   balanc@5            70
    y#1#6#1   BigM_26              1
    y#1#6#1   valid_1             40
    y#1#6#1   balanc@6            32
    y#1#6#1   balanc@1            40
    y#1#6#2   BigM_27              1
    y#1#6#2   valid_1             40
    y#1#6#2   balanc@7            32
    y#1#6#2   balanc@2            40
    y#1#6#3   BigM_28              1
    y#1#6#3   valid_1             40
    y#1#6#3   balanc@8            32
    y#1#6#3   balanc@3            40
    y#1#6#4   BigM_29              1
    y#1#6#4   valid_1             40
    y#1#6#4   balanc@9            32
    y#1#6#4   balanc@4            40
    y#1#6#5   BigM_30              1
    y#1#6#5   valid_1             40
    y#1#6#5   balanc@a            32
    y#1#6#5   balanc@5            40
    y#2#1#1   BigM_31              1
    y#2#1#1   valid_3             33
    y#2#1#1   valid_2             39
    y#2#1#1   balan@10            33
    y#2#1#1   balanc@b            39
    y#2#1#2   BigM_32              1
    y#2#1#2   valid_3             33
    y#2#1#2   valid_2             39
    y#2#1#2   balan@11            33
    y#2#1#2   balanc@c            39
    y#2#1#3   BigM_33              1
    y#2#1#3   valid_3             33
    y#2#1#3   valid_2             39
    y#2#1#3   balan@12            33
    y#2#1#3   balanc@d            39
    y#2#1#4   BigM_34              1
    y#2#1#4   valid_3             33
    y#2#1#4   valid_2             39
    y#2#1#4   balan@13            33
    y#2#1#4   balanc@e            39
    y#2#1#5   BigM_35              1
    y#2#1#5   valid_3             33
    y#2#1#5   valid_2             39
    y#2#1#5   balan@14            33
    y#2#1#5   balanc@f            39
    y#2#2#1   BigM_36              1
    y#2#2#1   valid_3             44
    y#2#2#1   valid_2             28
    y#2#2#1   balan@10            44
    y#2#2#1   balanc@b            28
    y#2#2#2   BigM_37              1
    y#2#2#2   valid_3             44
    y#2#2#2   valid_2             28
    y#2#2#2   balan@11            44
    y#2#2#2   balanc@c            28
    y#2#2#3   BigM_38              1
    y#2#2#3   valid_3             44
    y#2#2#3   valid_2             28
    y#2#2#3   balan@12            44
    y#2#2#3   balanc@d            28
    y#2#2#4   BigM_39              1
    y#2#2#4   valid_3             44
    y#2#2#4   valid_2             28
    y#2#2#4   balan@13            44
    y#2#2#4   balanc@e            28
    y#2#2#5   BigM_40              1
    y#2#2#5   valid_3             44
    y#2#2#5   valid_2             28
    y#2#2#5   balan@14            44
    y#2#2#5   balanc@f            28
    y#2#3#1   BigM_41              1
    y#2#3#1   valid_3             35
    y#2#3#1   valid_2             37
    y#2#3#1   balan@10            35
    y#2#3#1   balanc@b            37
    y#2#3#2   BigM_42              1
    y#2#3#2   valid_3             35
    y#2#3#2   valid_2             37
    y#2#3#2   balan@11            35
    y#2#3#2   balanc@c            37
    y#2#3#3   BigM_43              1
    y#2#3#3   valid_3             35
    y#2#3#3   valid_2             37
    y#2#3#3   balan@12            35
    y#2#3#3   balanc@d            37
    y#2#3#4   BigM_44              1
    y#2#3#4   valid_3             35
    y#2#3#4   valid_2             37
    y#2#3#4   balan@13            35
    y#2#3#4   balanc@e            37
    y#2#3#5   BigM_45              1
    y#2#3#5   valid_3             35
    y#2#3#5   valid_2             37
    y#2#3#5   balan@14            35
    y#2#3#5   balanc@f            37
    y#2#4#1   BigM_46              1
    y#2#4#1   valid_3             47
    y#2#4#1   valid_2             25
    y#2#4#1   balan@10            47
    y#2#4#1   balanc@b            25
    y#2#4#2   BigM_47              1
    y#2#4#2   valid_3             47
    y#2#4#2   valid_2             25
    y#2#4#2   balan@11            47
    y#2#4#2   balanc@c            25
    y#2#4#3   BigM_48              1
    y#2#4#3   valid_3             47
    y#2#4#3   valid_2             25
    y#2#4#3   balan@12            47
    y#2#4#3   balanc@d            25
    y#2#4#4   BigM_49              1
    y#2#4#4   valid_3             47
    y#2#4#4   valid_2             25
    y#2#4#4   balan@13            47
    y#2#4#4   balanc@e            25
    y#2#4#5   BigM_50              1
    y#2#4#5   valid_3             47
    y#2#4#5   valid_2             25
    y#2#4#5   balan@14            47
    y#2#4#5   balanc@f            25
    y#2#5#1   BigM_51              1
    y#2#5#1   valid_3              2
    y#2#5#1   valid_2             70
    y#2#5#1   balan@10             2
    y#2#5#1   balanc@b            70
    y#2#5#2   BigM_52              1
    y#2#5#2   valid_3              2
    y#2#5#2   valid_2             70
    y#2#5#2   balan@11             2
    y#2#5#2   balanc@c            70
    y#2#5#3   BigM_53              1
    y#2#5#3   valid_3              2
    y#2#5#3   valid_2             70
    y#2#5#3   balan@12             2
    y#2#5#3   balanc@d            70
    y#2#5#4   BigM_54              1
    y#2#5#4   valid_3              2
    y#2#5#4   valid_2             70
    y#2#5#4   balan@13             2
    y#2#5#4   balanc@e            70
    y#2#5#5   BigM_55              1
    y#2#5#5   valid_3              2
    y#2#5#5   valid_2             70
    y#2#5#5   balan@14             2
    y#2#5#5   balanc@f            70
    y#2#6#1   BigM_56              1
    y#2#6#1   valid_3             32
    y#2#6#1   valid_2             40
    y#2#6#1   balan@10            32
    y#2#6#1   balanc@b            40
    y#2#6#2   BigM_57              1
    y#2#6#2   valid_3             32
    y#2#6#2   valid_2             40
    y#2#6#2   balan@11            32
    y#2#6#2   balanc@c            40
    y#2#6#3   BigM_58              1
    y#2#6#3   valid_3             32
    y#2#6#3   valid_2             40
    y#2#6#3   balan@12            32
    y#2#6#3   balanc@d            40
    y#2#6#4   BigM_59              1
    y#2#6#4   valid_3             32
    y#2#6#4   valid_2             40
    y#2#6#4   balan@13            32
    y#2#6#4   balanc@e            40
    y#2#6#5   BigM_60              1
    y#2#6#5   valid_3             32
    y#2#6#5   valid_2             40
    y#2#6#5   balan@14            32
    y#2#6#5   balanc@f            40
    y#3#1#1   BigM_61              1
    y#3#1#1   valid_5             33
    y#3#1#1   valid_4             39
    y#3#1#1   balan@1a            33
    y#3#1#1   balan@15            39
    y#3#1#2   BigM_62              1
    y#3#1#2   valid_5             33
    y#3#1#2   valid_4             39
    y#3#1#2   balan@1b            33
    y#3#1#2   balan@16            39
    y#3#1#3   BigM_63              1
    y#3#1#3   valid_5             33
    y#3#1#3   valid_4             39
    y#3#1#3   balan@1c            33
    y#3#1#3   balan@17            39
    y#3#1#4   BigM_64              1
    y#3#1#4   valid_5             33
    y#3#1#4   valid_4             39
    y#3#1#4   balan@1d            33
    y#3#1#4   balan@18            39
    y#3#1#5   BigM_65              1
    y#3#1#5   valid_5             33
    y#3#1#5   valid_4             39
    y#3#1#5   balan@1e            33
    y#3#1#5   balan@19            39
    y#3#2#1   BigM_66              1
    y#3#2#1   valid_5             44
    y#3#2#1   valid_4             28
    y#3#2#1   balan@1a            44
    y#3#2#1   balan@15            28
    y#3#2#2   BigM_67              1
    y#3#2#2   valid_5             44
    y#3#2#2   valid_4             28
    y#3#2#2   balan@1b            44
    y#3#2#2   balan@16            28
    y#3#2#3   BigM_68              1
    y#3#2#3   valid_5             44
    y#3#2#3   valid_4             28
    y#3#2#3   balan@1c            44
    y#3#2#3   balan@17            28
    y#3#2#4   BigM_69              1
    y#3#2#4   valid_5             44
    y#3#2#4   valid_4             28
    y#3#2#4   balan@1d            44
    y#3#2#4   balan@18            28
    y#3#2#5   BigM_70              1
    y#3#2#5   valid_5             44
    y#3#2#5   valid_4             28
    y#3#2#5   balan@1e            44
    y#3#2#5   balan@19            28
    y#3#3#1   BigM_71              1
    y#3#3#1   valid_5             35
    y#3#3#1   valid_4             37
    y#3#3#1   balan@1a            35
    y#3#3#1   balan@15            37
    y#3#3#2   BigM_72              1
    y#3#3#2   valid_5             35
    y#3#3#2   valid_4             37
    y#3#3#2   balan@1b            35
    y#3#3#2   balan@16            37
    y#3#3#3   BigM_73              1
    y#3#3#3   valid_5             35
    y#3#3#3   valid_4             37
    y#3#3#3   balan@1c            35
    y#3#3#3   balan@17            37
    y#3#3#4   BigM_74              1
    y#3#3#4   valid_5             35
    y#3#3#4   valid_4             37
    y#3#3#4   balan@1d            35
    y#3#3#4   balan@18            37
    y#3#3#5   BigM_75              1
    y#3#3#5   valid_5             35
    y#3#3#5   valid_4             37
    y#3#3#5   balan@1e            35
    y#3#3#5   balan@19            37
    y#3#4#1   BigM_76              1
    y#3#4#1   valid_5             47
    y#3#4#1   valid_4             25
    y#3#4#1   balan@1a            47
    y#3#4#1   balan@15            25
    y#3#4#2   BigM_77              1
    y#3#4#2   valid_5             47
    y#3#4#2   valid_4             25
    y#3#4#2   balan@1b            47
    y#3#4#2   balan@16            25
    y#3#4#3   BigM_78              1
    y#3#4#3   valid_5             47
    y#3#4#3   valid_4             25
    y#3#4#3   balan@1c            47
    y#3#4#3   balan@17            25
    y#3#4#4   BigM_79              1
    y#3#4#4   valid_5             47
    y#3#4#4   valid_4             25
    y#3#4#4   balan@1d            47
    y#3#4#4   balan@18            25
    y#3#4#5   BigM_80              1
    y#3#4#5   valid_5             47
    y#3#4#5   valid_4             25
    y#3#4#5   balan@1e            47
    y#3#4#5   balan@19            25
    y#3#5#1   BigM_81              1
    y#3#5#1   valid_5              2
    y#3#5#1   valid_4             70
    y#3#5#1   balan@1a             2
    y#3#5#1   balan@15            70
    y#3#5#2   BigM_82              1
    y#3#5#2   valid_5              2
    y#3#5#2   valid_4             70
    y#3#5#2   balan@1b             2
    y#3#5#2   balan@16            70
    y#3#5#3   BigM_83              1
    y#3#5#3   valid_5              2
    y#3#5#3   valid_4             70
    y#3#5#3   balan@1c             2
    y#3#5#3   balan@17            70
    y#3#5#4   BigM_84              1
    y#3#5#4   valid_5              2
    y#3#5#4   valid_4             70
    y#3#5#4   balan@1d             2
    y#3#5#4   balan@18            70
    y#3#5#5   BigM_85              1
    y#3#5#5   valid_5              2
    y#3#5#5   valid_4             70
    y#3#5#5   balan@1e             2
    y#3#5#5   balan@19            70
    y#3#6#1   BigM_86              1
    y#3#6#1   valid_5             32
    y#3#6#1   valid_4             40
    y#3#6#1   balan@1a            32
    y#3#6#1   balan@15            40
    y#3#6#2   BigM_87              1
    y#3#6#2   valid_5             32
    y#3#6#2   valid_4             40
    y#3#6#2   balan@1b            32
    y#3#6#2   balan@16            40
    y#3#6#3   BigM_88              1
    y#3#6#3   valid_5             32
    y#3#6#3   valid_4             40
    y#3#6#3   balan@1c            32
    y#3#6#3   balan@17            40
    y#3#6#4   BigM_89              1
    y#3#6#4   valid_5             32
    y#3#6#4   valid_4             40
    y#3#6#4   balan@1d            32
    y#3#6#4   balan@18            40
    y#3#6#5   BigM_90              1
    y#3#6#5   valid_5             32
    y#3#6#5   valid_4             40
    y#3#6#5   balan@1e            32
    y#3#6#5   balan@19            40
    y#4#1#1   BigM_91              1
    y#4#1#1   valid_6             33
    y#4#1#1   balan@24            33
    y#4#1#1   balan@1f            39
    y#4#1#2   BigM_92              1
    y#4#1#2   valid_6             33
    y#4#1#2   balan@25            33
    y#4#1#2   balan@20            39
    y#4#1#3   BigM_93              1
    y#4#1#3   valid_6             33
    y#4#1#3   balan@26            33
    y#4#1#3   balan@21            39
    y#4#1#4   BigM_94              1
    y#4#1#4   valid_6             33
    y#4#1#4   balan@27            33
    y#4#1#4   balan@22            39
    y#4#1#5   BigM_95              1
    y#4#1#5   valid_6             33
    y#4#1#5   balan@28            33
    y#4#1#5   balan@23            39
    y#4#2#1   BigM_96              1
    y#4#2#1   valid_6             44
    y#4#2#1   balan@24            44
    y#4#2#1   balan@1f            28
    y#4#2#2   BigM_97              1
    y#4#2#2   valid_6             44
    y#4#2#2   balan@25            44
    y#4#2#2   balan@20            28
    y#4#2#3   BigM_98              1
    y#4#2#3   valid_6             44
    y#4#2#3   balan@26            44
    y#4#2#3   balan@21            28
    y#4#2#4   BigM_99              1
    y#4#2#4   valid_6             44
    y#4#2#4   balan@27            44
    y#4#2#4   balan@22            28
    y#4#2#5   BigM_100             1
    y#4#2#5   valid_6             44
    y#4#2#5   balan@28            44
    y#4#2#5   balan@23            28
    y#4#3#1   BigM_101             1
    y#4#3#1   valid_6             35
    y#4#3#1   balan@24            35
    y#4#3#1   balan@1f            37
    y#4#3#2   BigM_102             1
    y#4#3#2   valid_6             35
    y#4#3#2   balan@25            35
    y#4#3#2   balan@20            37
    y#4#3#3   BigM_103             1
    y#4#3#3   valid_6             35
    y#4#3#3   balan@26            35
    y#4#3#3   balan@21            37
    y#4#3#4   BigM_104             1
    y#4#3#4   valid_6             35
    y#4#3#4   balan@27            35
    y#4#3#4   balan@22            37
    y#4#3#5   BigM_105             1
    y#4#3#5   valid_6             35
    y#4#3#5   balan@28            35
    y#4#3#5   balan@23            37
    y#4#4#1   BigM_106             1
    y#4#4#1   valid_6             47
    y#4#4#1   balan@24            47
    y#4#4#1   balan@1f            25
    y#4#4#2   BigM_107             1
    y#4#4#2   valid_6             47
    y#4#4#2   balan@25            47
    y#4#4#2   balan@20            25
    y#4#4#3   BigM_108             1
    y#4#4#3   valid_6             47
    y#4#4#3   balan@26            47
    y#4#4#3   balan@21            25
    y#4#4#4   BigM_109             1
    y#4#4#4   valid_6             47
    y#4#4#4   balan@27            47
    y#4#4#4   balan@22            25
    y#4#4#5   BigM_110             1
    y#4#4#5   valid_6             47
    y#4#4#5   balan@28            47
    y#4#4#5   balan@23            25
    y#4#5#1   BigM_111             1
    y#4#5#1   valid_6              2
    y#4#5#1   balan@24             2
    y#4#5#1   balan@1f            70
    y#4#5#2   BigM_112             1
    y#4#5#2   valid_6              2
    y#4#5#2   balan@25             2
    y#4#5#2   balan@20            70
    y#4#5#3   BigM_113             1
    y#4#5#3   valid_6              2
    y#4#5#3   balan@26             2
    y#4#5#3   balan@21            70
    y#4#5#4   BigM_114             1
    y#4#5#4   valid_6              2
    y#4#5#4   balan@27             2
    y#4#5#4   balan@22            70
    y#4#5#5   BigM_115             1
    y#4#5#5   valid_6              2
    y#4#5#5   balan@28             2
    y#4#5#5   balan@23            70
    y#4#6#1   BigM_116             1
    y#4#6#1   valid_6             32
    y#4#6#1   balan@24            32
    y#4#6#1   balan@1f            40
    y#4#6#2   BigM_117             1
    y#4#6#2   valid_6             32
    y#4#6#2   balan@25            32
    y#4#6#2   balan@20            40
    y#4#6#3   BigM_118             1
    y#4#6#3   valid_6             32
    y#4#6#3   balan@26            32
    y#4#6#3   balan@21            40
    y#4#6#4   BigM_119             1
    y#4#6#4   valid_6             32
    y#4#6#4   balan@27            32
    y#4#6#4   balan@22            40
    y#4#6#5   BigM_120             1
    y#4#6#5   valid_6             32
    y#4#6#5   balan@28            32
    y#4#6#5   balan@23            40
    p#1       BigM_95          -1000
    p#1       BigM_94          -1000
    p#1       BigM_93          -1000
    p#1       BigM_92          -1000
    p#1       BigM_91          -1000
    p#1       BigM_65          -1000
    p#1       BigM_64          -1000
    p#1       BigM_63          -1000
    p#1       BigM_62          -1000
    p#1       BigM_61          -1000
    p#1       BigM_35          -1000
    p#1       BigM_34          -1000
    p#1       BigM_33          -1000
    p#1       BigM_32          -1000
    p#1       BigM_31          -1000
    p#1       BigM_5           -1000
    p#1       BigM_4           -1000
    p#1       BigM_3           -1000
    p#1       BigM_2           -1000
    p#1       BigM_1           -1000
    p#1       select_1             1
    p#2       BigM_100         -1000
    p#2       BigM_99          -1000
    p#2       BigM_98          -1000
    p#2       BigM_97          -1000
    p#2       BigM_96          -1000
    p#2       BigM_70          -1000
    p#2       BigM_69          -1000
    p#2       BigM_68          -1000
    p#2       BigM_67          -1000
    p#2       BigM_66          -1000
    p#2       BigM_40          -1000
    p#2       BigM_39          -1000
    p#2       BigM_38          -1000
    p#2       BigM_37          -1000
    p#2       BigM_36          -1000
    p#2       BigM_10          -1000
    p#2       BigM_9           -1000
    p#2       BigM_8           -1000
    p#2       BigM_7           -1000
    p#2       BigM_6           -1000
    p#2       select_1             1
    p#3       BigM_105         -1000
    p#3       BigM_104         -1000
    p#3       BigM_103         -1000
    p#3       BigM_102         -1000
    p#3       BigM_101         -1000
    p#3       BigM_75          -1000
    p#3       BigM_74          -1000
    p#3       BigM_73          -1000
    p#3       BigM_72          -1000
    p#3       BigM_71          -1000
    p#3       BigM_45          -1000
    p#3       BigM_44          -1000
    p#3       BigM_43          -1000
    p#3       BigM_42          -1000
    p#3       BigM_41          -1000
    p#3       BigM_15          -1000
    p#3       BigM_14          -1000
    p#3       BigM_13          -1000
    p#3       BigM_12          -1000
    p#3       BigM_11          -1000
    p#3       select_1             1
    p#4       BigM_110         -1000
    p#4       BigM_109         -1000
    p#4       BigM_108         -1000
    p#4       BigM_107         -1000
    p#4       BigM_106         -1000
    p#4       BigM_80          -1000
    p#4       BigM_79          -1000
    p#4       BigM_78          -1000
    p#4       BigM_77          -1000
    p#4       BigM_76          -1000
    p#4       BigM_50          -1000
    p#4       BigM_49          -1000
    p#4       BigM_48          -1000
    p#4       BigM_47          -1000
    p#4       BigM_46          -1000
    p#4       BigM_20          -1000
    p#4       BigM_19          -1000
    p#4       BigM_18          -1000
    p#4       BigM_17          -1000
    p#4       BigM_16          -1000
    p#4       select_1             1
    p#5       BigM_115         -1000
    p#5       BigM_114         -1000
    p#5       BigM_113         -1000
    p#5       BigM_112         -1000
    p#5       BigM_111         -1000
    p#5       BigM_85          -1000
    p#5       BigM_84          -1000
    p#5       BigM_83          -1000
    p#5       BigM_82          -1000
    p#5       BigM_81          -1000
    p#5       BigM_55          -1000
    p#5       BigM_54          -1000
    p#5       BigM_53          -1000
    p#5       BigM_52          -1000
    p#5       BigM_51          -1000
    p#5       BigM_25          -1000
    p#5       BigM_24          -1000
    p#5       BigM_23          -1000
    p#5       BigM_22          -1000
    p#5       BigM_21          -1000
    p#5       select_1             1
    p#6       BigM_120         -1000
    p#6       BigM_119         -1000
    p#6       BigM_118         -1000
    p#6       BigM_117         -1000
    p#6       BigM_116         -1000
    p#6       BigM_90          -1000
    p#6       BigM_89          -1000
    p#6       BigM_88          -1000
    p#6       BigM_87          -1000
    p#6       BigM_86          -1000
    p#6       BigM_60          -1000
    p#6       BigM_59          -1000
    p#6       BigM_58          -1000
    p#6       BigM_57          -1000
    p#6       BigM_56          -1000
    p#6       BigM_30          -1000
    p#6       BigM_29          -1000
    p#6       BigM_28          -1000
    p#6       BigM_27          -1000
    p#6       BigM_26          -1000
    p#6       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    B#1#1#0   init2_1              1
    B#1#1#0   balanc@1            -1
    B#1#1#1   OBJECTIV             5
    B#1#1#1   balanc@2            -1
    B#1#1#1   balanc@1             1
    B#1#1#2   OBJECTIV             5
    B#1#1#2   balanc@3            -1
    B#1#1#2   balanc@2             1
    B#1#1#3   OBJECTIV             5
    B#1#1#3   balanc@4            -1
    B#1#1#3   balanc@3             1
    B#1#1#4   OBJECTIV             5
    B#1#1#4   balanc@5            -1
    B#1#1#4   balanc@4             1
    B#1#1#5   OBJECTIV             5
    B#1#1#5   init3_1              1
    B#1#1#5   balanc@5             1
    B#1#2#0   init2_2              1
    B#1#2#0   balanc@6            -1
    B#1#2#1   OBJECTIV           5.5
    B#1#2#1   balanc@7            -1
    B#1#2#1   balanc@6             1
    B#1#2#2   OBJECTIV           5.5
    B#1#2#2   balanc@8            -1
    B#1#2#2   balanc@7             1
    B#1#2#3   OBJECTIV           5.5
    B#1#2#3   balanc@9            -1
    B#1#2#3   balanc@8             1
    B#1#2#4   OBJECTIV           5.5
    B#1#2#4   balanc@a            -1
    B#1#2#4   balanc@9             1
    B#1#2#5   OBJECTIV           5.5
    B#1#2#5   init3_2              1
    B#1#2#5   balanc@a             1
    B#2#1#0   init2_3              1
    B#2#1#0   balanc@b            -1
    B#2#1#1   OBJECTIV             5
    B#2#1#1   balanc@c            -1
    B#2#1#1   balanc@b             1
    B#2#1#2   OBJECTIV             5
    B#2#1#2   balanc@d            -1
    B#2#1#2   balanc@c             1
    B#2#1#3   OBJECTIV             5
    B#2#1#3   balanc@e            -1
    B#2#1#3   balanc@d             1
    B#2#1#4   OBJECTIV             5
    B#2#1#4   balanc@f            -1
    B#2#1#4   balanc@e             1
    B#2#1#5   OBJECTIV             5
    B#2#1#5   init3_3              1
    B#2#1#5   balanc@f             1
    B#2#2#0   init2_4              1
    B#2#2#0   balan@10            -1
    B#2#2#1   OBJECTIV           5.5
    B#2#2#1   balan@11            -1
    B#2#2#1   balan@10             1
    B#2#2#2   OBJECTIV           5.5
    B#2#2#2   balan@12            -1
    B#2#2#2   balan@11             1
    B#2#2#3   OBJECTIV           5.5
    B#2#2#3   balan@13            -1
    B#2#2#3   balan@12             1
    B#2#2#4   OBJECTIV           5.5
    B#2#2#4   balan@14            -1
    B#2#2#4   balan@13             1
    B#2#2#5   OBJECTIV           5.5
    B#2#2#5   init3_4              1
    B#2#2#5   balan@14             1
    B#3#1#0   init2_5              1
    B#3#1#0   balan@15            -1
    B#3#1#1   OBJECTIV             5
    B#3#1#1   balan@16            -1
    B#3#1#1   balan@15             1
    B#3#1#2   OBJECTIV             5
    B#3#1#2   balan@17            -1
    B#3#1#2   balan@16             1
    B#3#1#3   OBJECTIV             5
    B#3#1#3   balan@18            -1
    B#3#1#3   balan@17             1
    B#3#1#4   OBJECTIV             5
    B#3#1#4   balan@19            -1
    B#3#1#4   balan@18             1
    B#3#1#5   OBJECTIV             5
    B#3#1#5   init3_5              1
    B#3#1#5   balan@19             1
    B#3#2#0   init2_6              1
    B#3#2#0   balan@1a            -1
    B#3#2#1   OBJECTIV           5.5
    B#3#2#1   balan@1b            -1
    B#3#2#1   balan@1a             1
    B#3#2#2   OBJECTIV           5.5
    B#3#2#2   balan@1c            -1
    B#3#2#2   balan@1b             1
    B#3#2#3   OBJECTIV           5.5
    B#3#2#3   balan@1d            -1
    B#3#2#3   balan@1c             1
    B#3#2#4   OBJECTIV           5.5
    B#3#2#4   balan@1e            -1
    B#3#2#4   balan@1d             1
    B#3#2#5   OBJECTIV           5.5
    B#3#2#5   init3_6              1
    B#3#2#5   balan@1e             1
    B#4#1#0   init2_7              1
    B#4#1#0   balan@1f            -1
    B#4#1#1   OBJECTIV             5
    B#4#1#1   balan@20            -1
    B#4#1#1   balan@1f             1
    B#4#1#2   OBJECTIV             5
    B#4#1#2   balan@21            -1
    B#4#1#2   balan@20             1
    B#4#1#3   OBJECTIV             5
    B#4#1#3   balan@22            -1
    B#4#1#3   balan@21             1
    B#4#1#4   OBJECTIV             5
    B#4#1#4   balan@23            -1
    B#4#1#4   balan@22             1
    B#4#1#5   OBJECTIV             5
    B#4#1#5   init3_7              1
    B#4#1#5   balan@23             1
    B#4#2#0   init2_8              1
    B#4#2#0   balan@24            -1
    B#4#2#1   OBJECTIV           5.5
    B#4#2#1   balan@25            -1
    B#4#2#1   balan@24             1
    B#4#2#2   OBJECTIV           5.5
    B#4#2#2   balan@26            -1
    B#4#2#2   balan@25             1
    B#4#2#3   OBJECTIV           5.5
    B#4#2#3   balan@27            -1
    B#4#2#3   balan@26             1
    B#4#2#4   OBJECTIV           5.5
    B#4#2#4   balan@28            -1
    B#4#2#4   balan@27             1
    B#4#2#5   OBJECTIV           5.5
    B#4#2#5   init3_8              1
    B#4#2#5   balan@28             1
    I#1#1#0   init1_1              1
    I#1#1#0   balanc@1             1
    I#1#1#1   OBJECTIV             1
    I#1#1#1   balanc@2             1
    I#1#1#1   balanc@1            -1
    I#1#1#2   OBJECTIV             1
    I#1#1#2   balanc@3             1
    I#1#1#2   balanc@2            -1
    I#1#1#3   OBJECTIV             1
    I#1#1#3   balanc@4             1
    I#1#1#3   balanc@3            -1
    I#1#1#4   OBJECTIV             1
    I#1#1#4   balanc@5             1
    I#1#1#4   balanc@4            -1
    I#1#1#5   OBJECTIV             1
    I#1#1#5   balanc@5            -1
    I#1#2#0   init1_2              1
    I#1#2#0   balanc@6             1
    I#1#2#1   OBJECTIV           1.1
    I#1#2#1   balanc@7             1
    I#1#2#1   balanc@6            -1
    I#1#2#2   OBJECTIV           1.1
    I#1#2#2   balanc@8             1
    I#1#2#2   balanc@7            -1
    I#1#2#3   OBJECTIV           1.1
    I#1#2#3   balanc@9             1
    I#1#2#3   balanc@8            -1
    I#1#2#4   OBJECTIV           1.1
    I#1#2#4   balanc@a             1
    I#1#2#4   balanc@9            -1
    I#1#2#5   OBJECTIV           1.1
    I#1#2#5   balanc@a            -1
    I#2#1#0   init1_3              1
    I#2#1#0   balanc@b             1
    I#2#1#1   OBJECTIV             1
    I#2#1#1   balanc@c             1
    I#2#1#1   balanc@b            -1
    I#2#1#2   OBJECTIV             1
    I#2#1#2   balanc@d             1
    I#2#1#2   balanc@c            -1
    I#2#1#3   OBJECTIV             1
    I#2#1#3   balanc@e             1
    I#2#1#3   balanc@d            -1
    I#2#1#4   OBJECTIV             1
    I#2#1#4   balanc@f             1
    I#2#1#4   balanc@e            -1
    I#2#1#5   OBJECTIV             1
    I#2#1#5   balanc@f            -1
    I#2#2#0   init1_4              1
    I#2#2#0   balan@10             1
    I#2#2#1   OBJECTIV           1.1
    I#2#2#1   balan@11             1
    I#2#2#1   balan@10            -1
    I#2#2#2   OBJECTIV           1.1
    I#2#2#2   balan@12             1
    I#2#2#2   balan@11            -1
    I#2#2#3   OBJECTIV           1.1
    I#2#2#3   balan@13             1
    I#2#2#3   balan@12            -1
    I#2#2#4   OBJECTIV           1.1
    I#2#2#4   balan@14             1
    I#2#2#4   balan@13            -1
    I#2#2#5   OBJECTIV           1.1
    I#2#2#5   balan@14            -1
    I#3#1#0   init1_5              1
    I#3#1#0   balan@15             1
    I#3#1#1   OBJECTIV             1
    I#3#1#1   balan@16             1
    I#3#1#1   balan@15            -1
    I#3#1#2   OBJECTIV             1
    I#3#1#2   balan@17             1
    I#3#1#2   balan@16            -1
    I#3#1#3   OBJECTIV             1
    I#3#1#3   balan@18             1
    I#3#1#3   balan@17            -1
    I#3#1#4   OBJECTIV             1
    I#3#1#4   balan@19             1
    I#3#1#4   balan@18            -1
    I#3#1#5   OBJECTIV             1
    I#3#1#5   balan@19            -1
    I#3#2#0   init1_6              1
    I#3#2#0   balan@1a             1
    I#3#2#1   OBJECTIV           1.1
    I#3#2#1   balan@1b             1
    I#3#2#1   balan@1a            -1
    I#3#2#2   OBJECTIV           1.1
    I#3#2#2   balan@1c             1
    I#3#2#2   balan@1b            -1
    I#3#2#3   OBJECTIV           1.1
    I#3#2#3   balan@1d             1
    I#3#2#3   balan@1c            -1
    I#3#2#4   OBJECTIV           1.1
    I#3#2#4   balan@1e             1
    I#3#2#4   balan@1d            -1
    I#3#2#5   OBJECTIV           1.1
    I#3#2#5   balan@1e            -1
    I#4#1#0   init1_7              1
    I#4#1#0   balan@1f             1
    I#4#1#1   OBJECTIV             1
    I#4#1#1   balan@20             1
    I#4#1#1   balan@1f            -1
    I#4#1#2   OBJECTIV             1
    I#4#1#2   balan@21             1
    I#4#1#2   balan@20            -1
    I#4#1#3   OBJECTIV             1
    I#4#1#3   balan@22             1
    I#4#1#3   balan@21            -1
    I#4#1#4   OBJECTIV             1
    I#4#1#4   balan@23             1
    I#4#1#4   balan@22            -1
    I#4#1#5   OBJECTIV             1
    I#4#1#5   balan@23            -1
    I#4#2#0   init1_8              1
    I#4#2#0   balan@24             1
    I#4#2#1   OBJECTIV           1.1
    I#4#2#1   balan@25             1
    I#4#2#1   balan@24            -1
    I#4#2#2   OBJECTIV           1.1
    I#4#2#2   balan@26             1
    I#4#2#2   balan@25            -1
    I#4#2#3   OBJECTIV           1.1
    I#4#2#3   balan@27             1
    I#4#2#3   balan@26            -1
    I#4#2#4   OBJECTIV           1.1
    I#4#2#4   balan@28             1
    I#4#2#4   balan@27            -1
    I#4#2#5   OBJECTIV           1.1
    I#4#2#5   balan@28            -1
RHS
    RHS       select_1             2
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@4           669
    RHS       balanc@5           180
    RHS       balanc@b           333
    RHS       balanc@c           776
    RHS       balanc@d           466
    RHS       balanc@e           764
    RHS       balanc@f           166
    RHS       balan@10           239
    RHS       balan@11           425
    RHS       balan@12           220
    RHS       balan@13           452
    RHS       balan@14           519
    RHS       balan@15           136
    RHS       balan@16           621
    RHS       balan@17           192
    RHS       balan@18            74
    RHS       balan@19           510
    RHS       balan@1a             7
    RHS       balan@1b            27
    RHS       balan@1c           934
    RHS       balan@1d           620
    RHS       balan@1e           585
    RHS       balan@24           914
    RHS       balan@25           988
    RHS       balan@26           465
    RHS       balan@27           318
    RHS       balan@28           243
    RHS       valid_1           2171
    RHS       valid_2           2505
    RHS       valid_3           1855
    RHS       valid_4           1533
    RHS       valid_5           2173
    RHS       valid_6           2928
BOUNDS
 LO BOUND     B#1#1#0              0
 PL BOUND     B#1#1#0 
 LO BOUND     B#1#1#1              0
 PL BOUND     B#1#1#1 
 LO BOUND     B#1#1#2              0
 PL BOUND     B#1#1#2 
 LO BOUND     B#1#1#3              0
 PL BOUND     B#1#1#3 
 LO BOUND     B#1#1#4              0
 PL BOUND     B#1#1#4 
 LO BOUND     B#1#1#5              0
 PL BOUND     B#1#1#5 
 LO BOUND     B#1#2#0              0
 PL BOUND     B#1#2#0 
 LO BOUND     B#1#2#1              0
 PL BOUND     B#1#2#1 
 LO BOUND     B#1#2#2              0
 PL BOUND     B#1#2#2 
 LO BOUND     B#1#2#3              0
 PL BOUND     B#1#2#3 
 LO BOUND     B#1#2#4              0
 PL BOUND     B#1#2#4 
 LO BOUND     B#1#2#5              0
 PL BOUND     B#1#2#5 
 LO BOUND     B#2#1#0              0
 PL BOUND     B#2#1#0 
 LO BOUND     B#2#1#1              0
 PL BOUND     B#2#1#1 
 LO BOUND     B#2#1#2              0
 PL BOUND     B#2#1#2 
 LO BOUND     B#2#1#3              0
 PL BOUND     B#2#1#3 
 LO BOUND     B#2#1#4              0
 PL BOUND     B#2#1#4 
 LO BOUND     B#2#1#5              0
 PL BOUND     B#2#1#5 
 LO BOUND     B#2#2#0              0
 PL BOUND     B#2#2#0 
 LO BOUND     B#2#2#1              0
 PL BOUND     B#2#2#1 
 LO BOUND     B#2#2#2              0
 PL BOUND     B#2#2#2 
 LO BOUND     B#2#2#3              0
 PL BOUND     B#2#2#3 
 LO BOUND     B#2#2#4              0
 PL BOUND     B#2#2#4 
 LO BOUND     B#2#2#5              0
 PL BOUND     B#2#2#5 
 LO BOUND     B#3#1#0              0
 PL BOUND     B#3#1#0 
 LO BOUND     B#3#1#1              0
 PL BOUND     B#3#1#1 
 LO BOUND     B#3#1#2              0
 PL BOUND     B#3#1#2 
 LO BOUND     B#3#1#3              0
 PL BOUND     B#3#1#3 
 LO BOUND     B#3#1#4              0
 PL BOUND     B#3#1#4 
 LO BOUND     B#3#1#5              0
 PL BOUND     B#3#1#5 
 LO BOUND     B#3#2#0              0
 PL BOUND     B#3#2#0 
 LO BOUND     B#3#2#1              0
 PL BOUND     B#3#2#1 
 LO BOUND     B#3#2#2              0
 PL BOUND     B#3#2#2 
 LO BOUND     B#3#2#3              0
 PL BOUND     B#3#2#3 
 LO BOUND     B#3#2#4              0
 PL BOUND     B#3#2#4 
 LO BOUND     B#3#2#5              0
 PL BOUND     B#3#2#5 
 LO BOUND     B#4#1#0              0
 PL BOUND     B#4#1#0 
 LO BOUND     B#4#1#1              0
 PL BOUND     B#4#1#1 
 LO BOUND     B#4#1#2              0
 PL BOUND     B#4#1#2 
 LO BOUND     B#4#1#3              0
 PL BOUND     B#4#1#3 
 LO BOUND     B#4#1#4              0
 PL BOUND     B#4#1#4 
 LO BOUND     B#4#1#5              0
 PL BOUND     B#4#1#5 
 LO BOUND     B#4#2#0              0
 PL BOUND     B#4#2#0 
 LO BOUND     B#4#2#1              0
 PL BOUND     B#4#2#1 
 LO BOUND     B#4#2#2              0
 PL BOUND     B#4#2#2 
 LO BOUND     B#4#2#3              0
 PL BOUND     B#4#2#3 
 LO BOUND     B#4#2#4              0
 PL BOUND     B#4#2#4 
 LO BOUND     B#4#2#5              0
 PL BOUND     B#4#2#5 
 LO BOUND     I#1#1#0              0
 PL BOUND     I#1#1#0 
 LO BOUND     I#1#1#1              0
 PL BOUND     I#1#1#1 
 LO BOUND     I#1#1#2              0
 PL BOUND     I#1#1#2 
 LO BOUND     I#1#1#3              0
 PL BOUND     I#1#1#3 
 LO BOUND     I#1#1#4              0
 PL BOUND     I#1#1#4 
 LO BOUND     I#1#1#5              0
 PL BOUND     I#1#1#5 
 LO BOUND     I#1#2#0              0
 PL BOUND     I#1#2#0 
 LO BOUND     I#1#2#1              0
 PL BOUND     I#1#2#1 
 LO BOUND     I#1#2#2              0
 PL BOUND     I#1#2#2 
 LO BOUND     I#1#2#3              0
 PL BOUND     I#1#2#3 
 LO BOUND     I#1#2#4              0
 PL BOUND     I#1#2#4 
 LO BOUND     I#1#2#5              0
 PL BOUND     I#1#2#5 
 LO BOUND     I#2#1#0              0
 PL BOUND     I#2#1#0 
 LO BOUND     I#2#1#1              0
 PL BOUND     I#2#1#1 
 LO BOUND     I#2#1#2              0
 PL BOUND     I#2#1#2 
 LO BOUND     I#2#1#3              0
 PL BOUND     I#2#1#3 
 LO BOUND     I#2#1#4              0
 PL BOUND     I#2#1#4 
 LO BOUND     I#2#1#5              0
 PL BOUND     I#2#1#5 
 LO BOUND     I#2#2#0              0
 PL BOUND     I#2#2#0 
 LO BOUND     I#2#2#1              0
 PL BOUND     I#2#2#1 
 LO BOUND     I#2#2#2              0
 PL BOUND     I#2#2#2 
 LO BOUND     I#2#2#3              0
 PL BOUND     I#2#2#3 
 LO BOUND     I#2#2#4              0
 PL BOUND     I#2#2#4 
 LO BOUND     I#2#2#5              0
 PL BOUND     I#2#2#5 
 LO BOUND     I#3#1#0              0
 PL BOUND     I#3#1#0 
 LO BOUND     I#3#1#1              0
 PL BOUND     I#3#1#1 
 LO BOUND     I#3#1#2              0
 PL BOUND     I#3#1#2 
 LO BOUND     I#3#1#3              0
 PL BOUND     I#3#1#3 
 LO BOUND     I#3#1#4              0
 PL BOUND     I#3#1#4 
 LO BOUND     I#3#1#5              0
 PL BOUND     I#3#1#5 
 LO BOUND     I#3#2#0              0
 PL BOUND     I#3#2#0 
 LO BOUND     I#3#2#1              0
 PL BOUND     I#3#2#1 
 LO BOUND     I#3#2#2              0
 PL BOUND     I#3#2#2 
 LO BOUND     I#3#2#3              0
 PL BOUND     I#3#2#3 
 LO BOUND     I#3#2#4              0
 PL BOUND     I#3#2#4 
 LO BOUND     I#3#2#5              0
 PL BOUND     I#3#2#5 
 LO BOUND     I#4#1#0              0
 PL BOUND     I#4#1#0 
 LO BOUND     I#4#1#1              0
 PL BOUND     I#4#1#1 
 LO BOUND     I#4#1#2              0
 PL BOUND     I#4#1#2 
 LO BOUND     I#4#1#3              0
 PL BOUND     I#4#1#3 
 LO BOUND     I#4#1#4              0
 PL BOUND     I#4#1#4 
 LO BOUND     I#4#1#5              0
 PL BOUND     I#4#1#5 
 LO BOUND     I#4#2#0              0
 PL BOUND     I#4#2#0 
 LO BOUND     I#4#2#1              0
 PL BOUND     I#4#2#1 
 LO BOUND     I#4#2#2              0
 PL BOUND     I#4#2#2 
 LO BOUND     I#4#2#3              0
 PL BOUND     I#4#2#3 
 LO BOUND     I#4#2#4              0
 PL BOUND     I#4#2#4 
 LO BOUND     I#4#2#5              0
 PL BOUND     I#4#2#5 
 LO BOUND     f#1#1#1              0
 PL BOUND     f#1#1#1 
 LO BOUND     f#1#1#2              0
 PL BOUND     f#1#1#2 
 LO BOUND     f#1#1#3              0
 PL BOUND     f#1#1#3 
 LO BOUND     f#1#1#4              0
 PL BOUND     f#1#1#4 
 LO BOUND     f#1#1#5              0
 PL BOUND     f#1#1#5 
 LO BOUND     f#1#2#1              0
 PL BOUND     f#1#2#1 
 LO BOUND     f#1#2#2              0
 PL BOUND     f#1#2#2 
 LO BOUND     f#1#2#3              0
 PL BOUND     f#1#2#3 
 LO BOUND     f#1#2#4              0
 PL BOUND     f#1#2#4 
 LO BOUND     f#1#2#5              0
 PL BOUND     f#1#2#5 
 LO BOUND     f#2#1#1              0
 PL BOUND     f#2#1#1 
 LO BOUND     f#2#1#2              0
 PL BOUND     f#2#1#2 
 LO BOUND     f#2#1#3              0
 PL BOUND     f#2#1#3 
 LO BOUND     f#2#1#4              0
 PL BOUND     f#2#1#4 
 LO BOUND     f#2#1#5              0
 PL BOUND     f#2#1#5 
 LO BOUND     f#2#2#1              0
 PL BOUND     f#2#2#1 
 LO BOUND     f#2#2#2              0
 PL BOUND     f#2#2#2 
 LO BOUND     f#2#2#3              0
 PL BOUND     f#2#2#3 
 LO BOUND     f#2#2#4              0
 PL BOUND     f#2#2#4 
 LO BOUND     f#2#2#5              0
 PL BOUND     f#2#2#5 
 LO BOUND     f#3#1#1              0
 PL BOUND     f#3#1#1 
 LO BOUND     f#3#1#2              0
 PL BOUND     f#3#1#2 
 LO BOUND     f#3#1#3              0
 PL BOUND     f#3#1#3 
 LO BOUND     f#3#1#4              0
 PL BOUND     f#3#1#4 
 LO BOUND     f#3#1#5              0
 PL BOUND     f#3#1#5 
 LO BOUND     f#3#2#1              0
 PL BOUND     f#3#2#1 
 LO BOUND     f#3#2#2              0
 PL BOUND     f#3#2#2 
 LO BOUND     f#3#2#3              0
 PL BOUND     f#3#2#3 
 LO BOUND     f#3#2#4              0
 PL BOUND     f#3#2#4 
 LO BOUND     f#3#2#5              0
 PL BOUND     f#3#2#5 
 LO BOUND     f#4#1#1              0
 PL BOUND     f#4#1#1 
 LO BOUND     f#4#1#2              0
 PL BOUND     f#4#1#2 
 LO BOUND     f#4#1#3              0
 PL BOUND     f#4#1#3 
 LO BOUND     f#4#1#4              0
 PL BOUND     f#4#1#4 
 LO BOUND     f#4#1#5              0
 PL BOUND     f#4#1#5 
 LO BOUND     f#4#2#1              0
 PL BOUND     f#4#2#1 
 LO BOUND     f#4#2#2              0
 PL BOUND     f#4#2#2 
 LO BOUND     f#4#2#3              0
 PL BOUND     f#4#2#3 
 LO BOUND     f#4#2#4              0
 PL BOUND     f#4#2#4 
 LO BOUND     f#4#2#5              0
 PL BOUND     f#4#2#5 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#1#4              0
 PL BOUND     y#1#1#4 
 LO BOUND     y#1#1#5              0
 PL BOUND     y#1#1#5 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#2#4              0
 PL BOUND     y#1#2#4 
 LO BOUND     y#1#2#5              0
 PL BOUND     y#1#2#5 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#3#4              0
 PL BOUND     y#1#3#4 
 LO BOUND     y#1#3#5              0
 PL BOUND     y#1#3#5 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#4#4              0
 PL BOUND     y#1#4#4 
 LO BOUND     y#1#4#5              0
 PL BOUND     y#1#4#5 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#5#4              0
 PL BOUND     y#1#5#4 
 LO BOUND     y#1#5#5              0
 PL BOUND     y#1#5#5 
 LO BOUND     y#1#6#1              0
 PL BOUND     y#1#6#1 
 LO BOUND     y#1#6#2              0
 PL BOUND     y#1#6#2 
 LO BOUND     y#1#6#3              0
 PL BOUND     y#1#6#3 
 LO BOUND     y#1#6#4              0
 PL BOUND     y#1#6#4 
 LO BOUND     y#1#6#5              0
 PL BOUND     y#1#6#5 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#1#4              0
 PL BOUND     y#2#1#4 
 LO BOUND     y#2#1#5              0
 PL BOUND     y#2#1#5 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#2#4              0
 PL BOUND     y#2#2#4 
 LO BOUND     y#2#2#5              0
 PL BOUND     y#2#2#5 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#3#4              0
 PL BOUND     y#2#3#4 
 LO BOUND     y#2#3#5              0
 PL BOUND     y#2#3#5 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#4#4              0
 PL BOUND     y#2#4#4 
 LO BOUND     y#2#4#5              0
 PL BOUND     y#2#4#5 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#5#4              0
 PL BOUND     y#2#5#4 
 LO BOUND     y#2#5#5              0
 PL BOUND     y#2#5#5 
 LO BOUND     y#2#6#1              0
 PL BOUND     y#2#6#1 
 LO BOUND     y#2#6#2              0
 PL BOUND     y#2#6#2 
 LO BOUND     y#2#6#3              0
 PL BOUND     y#2#6#3 
 LO BOUND     y#2#6#4              0
 PL BOUND     y#2#6#4 
 LO BOUND     y#2#6#5              0
 PL BOUND     y#2#6#5 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#1#4              0
 PL BOUND     y#3#1#4 
 LO BOUND     y#3#1#5              0
 PL BOUND     y#3#1#5 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#2#4              0
 PL BOUND     y#3#2#4 
 LO BOUND     y#3#2#5              0
 PL BOUND     y#3#2#5 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#3#4              0
 PL BOUND     y#3#3#4 
 LO BOUND     y#3#3#5              0
 PL BOUND     y#3#3#5 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#4#4              0
 PL BOUND     y#3#4#4 
 LO BOUND     y#3#4#5              0
 PL BOUND     y#3#4#5 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#5#4              0
 PL BOUND     y#3#5#4 
 LO BOUND     y#3#5#5              0
 PL BOUND     y#3#5#5 
 LO BOUND     y#3#6#1              0
 PL BOUND     y#3#6#1 
 LO BOUND     y#3#6#2              0
 PL BOUND     y#3#6#2 
 LO BOUND     y#3#6#3              0
 PL BOUND     y#3#6#3 
 LO BOUND     y#3#6#4              0
 PL BOUND     y#3#6#4 
 LO BOUND     y#3#6#5              0
 PL BOUND     y#3#6#5 
 LO BOUND     y#4#1#1              0
 PL BOUND     y#4#1#1 
 LO BOUND     y#4#1#2              0
 PL BOUND     y#4#1#2 
 LO BOUND     y#4#1#3              0
 PL BOUND     y#4#1#3 
 LO BOUND     y#4#1#4              0
 PL BOUND     y#4#1#4 
 LO BOUND     y#4#1#5              0
 PL BOUND     y#4#1#5 
 LO BOUND     y#4#2#1              0
 PL BOUND     y#4#2#1 
 LO BOUND     y#4#2#2              0
 PL BOUND     y#4#2#2 
 LO BOUND     y#4#2#3              0
 PL BOUND     y#4#2#3 
 LO BOUND     y#4#2#4              0
 PL BOUND     y#4#2#4 
 LO BOUND     y#4#2#5              0
 PL BOUND     y#4#2#5 
 LO BOUND     y#4#3#1              0
 PL BOUND     y#4#3#1 
 LO BOUND     y#4#3#2              0
 PL BOUND     y#4#3#2 
 LO BOUND     y#4#3#3              0
 PL BOUND     y#4#3#3 
 LO BOUND     y#4#3#4              0
 PL BOUND     y#4#3#4 
 LO BOUND     y#4#3#5              0
 PL BOUND     y#4#3#5 
 LO BOUND     y#4#4#1              0
 PL BOUND     y#4#4#1 
 LO BOUND     y#4#4#2              0
 PL BOUND     y#4#4#2 
 LO BOUND     y#4#4#3              0
 PL BOUND     y#4#4#3 
 LO BOUND     y#4#4#4              0
 PL BOUND     y#4#4#4 
 LO BOUND     y#4#4#5              0
 PL BOUND     y#4#4#5 
 LO BOUND     y#4#5#1              0
 PL BOUND     y#4#5#1 
 LO BOUND     y#4#5#2              0
 PL BOUND     y#4#5#2 
 LO BOUND     y#4#5#3              0
 PL BOUND     y#4#5#3 
 LO BOUND     y#4#5#4              0
 PL BOUND     y#4#5#4 
 LO BOUND     y#4#5#5              0
 PL BOUND     y#4#5#5 
 LO BOUND     y#4#6#1              0
 PL BOUND     y#4#6#1 
 LO BOUND     y#4#6#2              0
 PL BOUND     y#4#6#2 
 LO BOUND     y#4#6#3              0
 PL BOUND     y#4#6#3 
 LO BOUND     y#4#6#4              0
 PL BOUND     y#4#6#4 
 LO BOUND     y#4#6#5              0
 PL BOUND     y#4#6#5 
 LO BOUND     p#1                  0
 UP BOUND     p#1                  1
 LO BOUND     p#2                  0
 UP BOUND     p#2                  1
 LO BOUND     p#3                  0
 UP BOUND     p#3                  1
 LO BOUND     p#4                  0
 UP BOUND     p#4                  1
 LO BOUND     p#5                  0
 UP BOUND     p#5                  1
 LO BOUND     p#6                  0
 UP BOUND     p#6                  1
ENDATA
