* This file was automatically generated by Zimpl
* param Q2 := 1;
* param M := 1000;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nN := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set N := { 1 .. nN };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[N] := read file1 as "<1n> 2n" skip 1 use nN;
* param backCost[N] := read file1 as "<1n> 2n" skip nN+1 use nN;
* param demand[C*N*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nN+1;
* param q[P*N] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*N] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in N with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <j> in P with q[j,i] > 0 };
* var B[C*N*T0] >= 0;
* var I[C*N*T0] >= 0;
* var f[C*N*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var p[P] binary;
* minimize cost: sum <i> in N: ( sum <t> in T: (sum <c> in C : (inveCost[i] * I[c,i,t]  + backCost[i] * B[c,i,t]) ));
* subto select:       sum <j> in P: p[j] <= m;
* subto balance:    forall <c,i,t> in C*N*T with t>=1 do       I[c,i,t-1] - B[c,i,t-1] + Q1*Q2*f[c,i,t] + Q2 * (sum <j> in Pc[c
* ]: q[j,i] * y[c,j,t]) == demand[c,i,t] + I[c,i,t] - B[c,i,t];
* subto valid:    forall <c,i> in C*N do       sum <t> in T: ( min(Q1, D[c,i]) * f[c,i,t] + sum <j> in Pc[c]: ( min(q[j,i], D[c
* ,i] ) * y[c,j,t]) ) >= D[c,i];
* subto BigM:    forall <c,j,t> in C*P*T with t>=1 do       y[c,j,t] <= M*p[j];
* subto init1:    forall <c,i> in C*N do       I[c,i,0] == 0;
* subto init2:    forall <c,i> in C*N do       B[c,i,0] == 0;
* subto init3:    forall <c,i> in C*N do       B[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 E  balan@25          
 E  balan@26          
 E  balan@27          
 E  balan@28          
 E  balan@29          
 E  balan@2a          
 E  balan@2b          
 E  balan@2c          
 E  balan@2d          
 E  balan@2e          
 E  balan@2f          
 E  balan@30          
 E  balan@31          
 E  balan@32          
 E  balan@33          
 E  balan@34          
 E  balan@35          
 E  balan@36          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 G  valid_7           
 G  valid_8           
 G  valid_9           
 G  valid_10          
 G  valid_11          
 G  valid_12          
 G  valid_13          
 G  valid_14          
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 L  BigM_101          
 L  BigM_102          
 L  BigM_103          
 L  BigM_104          
 L  BigM_105          
 L  BigM_106          
 L  BigM_107          
 L  BigM_108          
 L  BigM_109          
 L  BigM_110          
 L  BigM_111          
 L  BigM_112          
 L  BigM_113          
 L  BigM_114          
 L  BigM_115          
 L  BigM_116          
 L  BigM_117          
 L  BigM_118          
 L  BigM_119          
 L  BigM_120          
 L  BigM_121          
 L  BigM_122          
 L  BigM_123          
 L  BigM_124          
 L  BigM_125          
 L  BigM_126          
 L  BigM_127          
 L  BigM_128          
 L  BigM_129          
 L  BigM_130          
 L  BigM_131          
 L  BigM_132          
 L  BigM_133          
 L  BigM_134          
 L  BigM_135          
 L  BigM_136          
 L  BigM_137          
 L  BigM_138          
 L  BigM_139          
 L  BigM_140          
 L  BigM_141          
 L  BigM_142          
 L  BigM_143          
 L  BigM_144          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init1_9           
 E  init1_10          
 E  init1_11          
 E  init1_12          
 E  init1_13          
 E  init1_14          
 E  init1_15          
 E  init1_16          
 E  init1_17          
 E  init1_18          
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init2_9           
 E  init2_10          
 E  init2_11          
 E  init2_12          
 E  init2_13          
 E  init2_14          
 E  init2_15          
 E  init2_16          
 E  init2_17          
 E  init2_18          
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
 E  init3_9           
 E  init3_10          
 E  init3_11          
 E  init3_12          
 E  init3_13          
 E  init3_14          
 E  init3_15          
 E  init3_16          
 E  init3_17          
 E  init3_18          
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    f#1#1#1   valid_1             72
    f#1#1#1   balanc@1            72
    f#1#1#2   valid_1             72
    f#1#1#2   balanc@2            72
    f#1#1#3   valid_1             72
    f#1#1#3   balanc@3            72
    f#1#2#1   balanc@4            72
    f#1#2#2   balanc@5            72
    f#1#2#3   balanc@6            72
    f#1#3#1   valid_2             72
    f#1#3#1   balanc@7            72
    f#1#3#2   valid_2             72
    f#1#3#2   balanc@8            72
    f#1#3#3   valid_2             72
    f#1#3#3   balanc@9            72
    f#2#1#1   valid_3             72
    f#2#1#1   balanc@a            72
    f#2#1#2   valid_3             72
    f#2#1#2   balanc@b            72
    f#2#1#3   valid_3             72
    f#2#1#3   balanc@c            72
    f#2#2#1   valid_4             72
    f#2#2#1   balanc@d            72
    f#2#2#2   valid_4             72
    f#2#2#2   balanc@e            72
    f#2#2#3   valid_4             72
    f#2#2#3   balanc@f            72
    f#2#3#1   valid_5             72
    f#2#3#1   balan@10            72
    f#2#3#2   valid_5             72
    f#2#3#2   balan@11            72
    f#2#3#3   valid_5             72
    f#2#3#3   balan@12            72
    f#3#1#1   valid_6             72
    f#3#1#1   balan@13            72
    f#3#1#2   valid_6             72
    f#3#1#2   balan@14            72
    f#3#1#3   valid_6             72
    f#3#1#3   balan@15            72
    f#3#2#1   valid_7             72
    f#3#2#1   balan@16            72
    f#3#2#2   valid_7             72
    f#3#2#2   balan@17            72
    f#3#2#3   valid_7             72
    f#3#2#3   balan@18            72
    f#3#3#1   valid_8             72
    f#3#3#1   balan@19            72
    f#3#3#2   valid_8             72
    f#3#3#2   balan@1a            72
    f#3#3#3   valid_8             72
    f#3#3#3   balan@1b            72
    f#4#1#1   balan@1c            72
    f#4#1#2   balan@1d            72
    f#4#1#3   balan@1e            72
    f#4#2#1   valid_9             72
    f#4#2#1   balan@1f            72
    f#4#2#2   valid_9             72
    f#4#2#2   balan@20            72
    f#4#2#3   valid_9             72
    f#4#2#3   balan@21            72
    f#4#3#1   valid_10            72
    f#4#3#1   balan@22            72
    f#4#3#2   valid_10            72
    f#4#3#2   balan@23            72
    f#4#3#3   valid_10            72
    f#4#3#3   balan@24            72
    f#5#1#1   valid_11            72
    f#5#1#1   balan@25            72
    f#5#1#2   valid_11            72
    f#5#1#2   balan@26            72
    f#5#1#3   valid_11            72
    f#5#1#3   balan@27            72
    f#5#2#1   valid_12            72
    f#5#2#1   balan@28            72
    f#5#2#2   valid_12            72
    f#5#2#2   balan@29            72
    f#5#2#3   valid_12            72
    f#5#2#3   balan@2a            72
    f#5#3#1   balan@2b            72
    f#5#3#2   balan@2c            72
    f#5#3#3   balan@2d            72
    f#6#1#1   valid_13            72
    f#6#1#1   balan@2e            72
    f#6#1#2   valid_13            72
    f#6#1#2   balan@2f            72
    f#6#1#3   valid_13            72
    f#6#1#3   balan@30            72
    f#6#2#1   valid_14            72
    f#6#2#1   balan@31            72
    f#6#2#2   valid_14            72
    f#6#2#2   balan@32            72
    f#6#2#3   valid_14            72
    f#6#2#3   balan@33            72
    f#6#3#1   balan@34            72
    f#6#3#2   balan@35            72
    f#6#3#3   balan@36            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_2             12
    y#1#1#1   valid_1             43
    y#1#1#1   balanc@7            12
    y#1#1#1   balanc@4            17
    y#1#1#1   balanc@1            43
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_2             12
    y#1#1#2   valid_1             43
    y#1#1#2   balanc@8            12
    y#1#1#2   balanc@5            17
    y#1#1#2   balanc@2            43
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_2             12
    y#1#1#3   valid_1             43
    y#1#1#3   balanc@9            12
    y#1#1#3   balanc@6            17
    y#1#1#3   balanc@3            43
    y#1#2#1   BigM_4               1
    y#1#2#1   valid_2              6
    y#1#2#1   valid_1             64
    y#1#2#1   balanc@7             6
    y#1#2#1   balanc@4             2
    y#1#2#1   balanc@1            64
    y#1#2#2   BigM_5               1
    y#1#2#2   valid_2              6
    y#1#2#2   valid_1             64
    y#1#2#2   balanc@8             6
    y#1#2#2   balanc@5             2
    y#1#2#2   balanc@2            64
    y#1#2#3   BigM_6               1
    y#1#2#3   valid_2              6
    y#1#2#3   valid_1             64
    y#1#2#3   balanc@9             6
    y#1#2#3   balanc@6             2
    y#1#2#3   balanc@3            64
    y#1#3#1   BigM_7               1
    y#1#3#1   valid_2             12
    y#1#3#1   valid_1             41
    y#1#3#1   balanc@7            12
    y#1#3#1   balanc@4            19
    y#1#3#1   balanc@1            41
    y#1#3#2   BigM_8               1
    y#1#3#2   valid_2             12
    y#1#3#2   valid_1             41
    y#1#3#2   balanc@8            12
    y#1#3#2   balanc@5            19
    y#1#3#2   balanc@2            41
    y#1#3#3   BigM_9               1
    y#1#3#3   valid_2             12
    y#1#3#3   valid_1             41
    y#1#3#3   balanc@9            12
    y#1#3#3   balanc@6            19
    y#1#3#3   balanc@3            41
    y#1#4#1   BigM_10              1
    y#1#4#1   valid_2              3
    y#1#4#1   valid_1             32
    y#1#4#1   balanc@7             3
    y#1#4#1   balanc@4            37
    y#1#4#1   balanc@1            32
    y#1#4#2   BigM_11              1
    y#1#4#2   valid_2              3
    y#1#4#2   valid_1             32
    y#1#4#2   balanc@8             3
    y#1#4#2   balanc@5            37
    y#1#4#2   balanc@2            32
    y#1#4#3   BigM_12              1
    y#1#4#3   valid_2              3
    y#1#4#3   valid_1             32
    y#1#4#3   balanc@9             3
    y#1#4#3   balanc@6            37
    y#1#4#3   balanc@3            32
    y#1#5#1   BigM_13              1
    y#1#5#1   valid_2             22
    y#1#5#1   valid_1             25
    y#1#5#1   balanc@7            22
    y#1#5#1   balanc@4            25
    y#1#5#1   balanc@1            25
    y#1#5#2   BigM_14              1
    y#1#5#2   valid_2             22
    y#1#5#2   valid_1             25
    y#1#5#2   balanc@8            22
    y#1#5#2   balanc@5            25
    y#1#5#2   balanc@2            25
    y#1#5#3   BigM_15              1
    y#1#5#3   valid_2             22
    y#1#5#3   valid_1             25
    y#1#5#3   balanc@9            22
    y#1#5#3   balanc@6            25
    y#1#5#3   balanc@3            25
    y#1#6#1   BigM_16              1
    y#1#6#1   valid_2             51
    y#1#6#1   valid_1             12
    y#1#6#1   balanc@7            51
    y#1#6#1   balanc@4             9
    y#1#6#1   balanc@1            12
    y#1#6#2   BigM_17              1
    y#1#6#2   valid_2             51
    y#1#6#2   valid_1             12
    y#1#6#2   balanc@8            51
    y#1#6#2   balanc@5             9
    y#1#6#2   balanc@2            12
    y#1#6#3   BigM_18              1
    y#1#6#3   valid_2             51
    y#1#6#3   valid_1             12
    y#1#6#3   balanc@9            51
    y#1#6#3   balanc@6             9
    y#1#6#3   balanc@3            12
    y#1#7#1   BigM_19              1
    y#1#7#1   valid_2              9
    y#1#7#1   valid_1             13
    y#1#7#1   balanc@7             9
    y#1#7#1   balanc@4            50
    y#1#7#1   balanc@1            13
    y#1#7#2   BigM_20              1
    y#1#7#2   valid_2              9
    y#1#7#2   valid_1             13
    y#1#7#2   balanc@8             9
    y#1#7#2   balanc@5            50
    y#1#7#2   balanc@2            13
    y#1#7#3   BigM_21              1
    y#1#7#3   valid_2              9
    y#1#7#3   valid_1             13
    y#1#7#3   balanc@9             9
    y#1#7#3   balanc@6            50
    y#1#7#3   balanc@3            13
    y#1#8#1   BigM_22              1
    y#1#8#1   valid_2              5
    y#1#8#1   valid_1             36
    y#1#8#1   balanc@7             5
    y#1#8#1   balanc@4            31
    y#1#8#1   balanc@1            36
    y#1#8#2   BigM_23              1
    y#1#8#2   valid_2              5
    y#1#8#2   valid_1             36
    y#1#8#2   balanc@8             5
    y#1#8#2   balanc@5            31
    y#1#8#2   balanc@2            36
    y#1#8#3   BigM_24              1
    y#1#8#3   valid_2              5
    y#1#8#3   valid_1             36
    y#1#8#3   balanc@9             5
    y#1#8#3   balanc@6            31
    y#1#8#3   balanc@3            36
    y#2#1#1   BigM_25              1
    y#2#1#1   valid_5             12
    y#2#1#1   valid_4             17
    y#2#1#1   valid_3             43
    y#2#1#1   balan@10            12
    y#2#1#1   balanc@d            17
    y#2#1#1   balanc@a            43
    y#2#1#2   BigM_26              1
    y#2#1#2   valid_5             12
    y#2#1#2   valid_4             17
    y#2#1#2   valid_3             43
    y#2#1#2   balan@11            12
    y#2#1#2   balanc@e            17
    y#2#1#2   balanc@b            43
    y#2#1#3   BigM_27              1
    y#2#1#3   valid_5             12
    y#2#1#3   valid_4             17
    y#2#1#3   valid_3             43
    y#2#1#3   balan@12            12
    y#2#1#3   balanc@f            17
    y#2#1#3   balanc@c            43
    y#2#2#1   BigM_28              1
    y#2#2#1   valid_5              6
    y#2#2#1   valid_4              2
    y#2#2#1   valid_3             64
    y#2#2#1   balan@10             6
    y#2#2#1   balanc@d             2
    y#2#2#1   balanc@a            64
    y#2#2#2   BigM_29              1
    y#2#2#2   valid_5              6
    y#2#2#2   valid_4              2
    y#2#2#2   valid_3             64
    y#2#2#2   balan@11             6
    y#2#2#2   balanc@e             2
    y#2#2#2   balanc@b            64
    y#2#2#3   BigM_30              1
    y#2#2#3   valid_5              6
    y#2#2#3   valid_4              2
    y#2#2#3   valid_3             64
    y#2#2#3   balan@12             6
    y#2#2#3   balanc@f             2
    y#2#2#3   balanc@c            64
    y#2#3#1   BigM_31              1
    y#2#3#1   valid_5             12
    y#2#3#1   valid_4             19
    y#2#3#1   valid_3             41
    y#2#3#1   balan@10            12
    y#2#3#1   balanc@d            19
    y#2#3#1   balanc@a            41
    y#2#3#2   BigM_32              1
    y#2#3#2   valid_5             12
    y#2#3#2   valid_4             19
    y#2#3#2   valid_3             41
    y#2#3#2   balan@11            12
    y#2#3#2   balanc@e            19
    y#2#3#2   balanc@b            41
    y#2#3#3   BigM_33              1
    y#2#3#3   valid_5             12
    y#2#3#3   valid_4             19
    y#2#3#3   valid_3             41
    y#2#3#3   balan@12            12
    y#2#3#3   balanc@f            19
    y#2#3#3   balanc@c            41
    y#2#4#1   BigM_34              1
    y#2#4#1   valid_5              3
    y#2#4#1   valid_4             37
    y#2#4#1   valid_3             32
    y#2#4#1   balan@10             3
    y#2#4#1   balanc@d            37
    y#2#4#1   balanc@a            32
    y#2#4#2   BigM_35              1
    y#2#4#2   valid_5              3
    y#2#4#2   valid_4             37
    y#2#4#2   valid_3             32
    y#2#4#2   balan@11             3
    y#2#4#2   balanc@e            37
    y#2#4#2   balanc@b            32
    y#2#4#3   BigM_36              1
    y#2#4#3   valid_5              3
    y#2#4#3   valid_4             37
    y#2#4#3   valid_3             32
    y#2#4#3   balan@12             3
    y#2#4#3   balanc@f            37
    y#2#4#3   balanc@c            32
    y#2#5#1   BigM_37              1
    y#2#5#1   valid_5             22
    y#2#5#1   valid_4             25
    y#2#5#1   valid_3             25
    y#2#5#1   balan@10            22
    y#2#5#1   balanc@d            25
    y#2#5#1   balanc@a            25
    y#2#5#2   BigM_38              1
    y#2#5#2   valid_5             22
    y#2#5#2   valid_4             25
    y#2#5#2   valid_3             25
    y#2#5#2   balan@11            22
    y#2#5#2   balanc@e            25
    y#2#5#2   balanc@b            25
    y#2#5#3   BigM_39              1
    y#2#5#3   valid_5             22
    y#2#5#3   valid_4             25
    y#2#5#3   valid_3             25
    y#2#5#3   balan@12            22
    y#2#5#3   balanc@f            25
    y#2#5#3   balanc@c            25
    y#2#6#1   BigM_40              1
    y#2#6#1   valid_5             51
    y#2#6#1   valid_4              9
    y#2#6#1   valid_3             12
    y#2#6#1   balan@10            51
    y#2#6#1   balanc@d             9
    y#2#6#1   balanc@a            12
    y#2#6#2   BigM_41              1
    y#2#6#2   valid_5             51
    y#2#6#2   valid_4              9
    y#2#6#2   valid_3             12
    y#2#6#2   balan@11            51
    y#2#6#2   balanc@e             9
    y#2#6#2   balanc@b            12
    y#2#6#3   BigM_42              1
    y#2#6#3   valid_5             51
    y#2#6#3   valid_4              9
    y#2#6#3   valid_3             12
    y#2#6#3   balan@12            51
    y#2#6#3   balanc@f             9
    y#2#6#3   balanc@c            12
    y#2#7#1   BigM_43              1
    y#2#7#1   valid_5              9
    y#2#7#1   valid_4             50
    y#2#7#1   valid_3             13
    y#2#7#1   balan@10             9
    y#2#7#1   balanc@d            50
    y#2#7#1   balanc@a            13
    y#2#7#2   BigM_44              1
    y#2#7#2   valid_5              9
    y#2#7#2   valid_4             50
    y#2#7#2   valid_3             13
    y#2#7#2   balan@11             9
    y#2#7#2   balanc@e            50
    y#2#7#2   balanc@b            13
    y#2#7#3   BigM_45              1
    y#2#7#3   valid_5              9
    y#2#7#3   valid_4             50
    y#2#7#3   valid_3             13
    y#2#7#3   balan@12             9
    y#2#7#3   balanc@f            50
    y#2#7#3   balanc@c            13
    y#2#8#1   BigM_46              1
    y#2#8#1   valid_5              5
    y#2#8#1   valid_4             31
    y#2#8#1   valid_3             36
    y#2#8#1   balan@10             5
    y#2#8#1   balanc@d            31
    y#2#8#1   balanc@a            36
    y#2#8#2   BigM_47              1
    y#2#8#2   valid_5              5
    y#2#8#2   valid_4             31
    y#2#8#2   valid_3             36
    y#2#8#2   balan@11             5
    y#2#8#2   balanc@e            31
    y#2#8#2   balanc@b            36
    y#2#8#3   BigM_48              1
    y#2#8#3   valid_5              5
    y#2#8#3   valid_4             31
    y#2#8#3   valid_3             36
    y#2#8#3   balan@12             5
    y#2#8#3   balanc@f            31
    y#2#8#3   balanc@c            36
    y#3#1#1   BigM_49              1
    y#3#1#1   valid_8             12
    y#3#1#1   valid_7             17
    y#3#1#1   valid_6             43
    y#3#1#1   balan@19            12
    y#3#1#1   balan@16            17
    y#3#1#1   balan@13            43
    y#3#1#2   BigM_50              1
    y#3#1#2   valid_8             12
    y#3#1#2   valid_7             17
    y#3#1#2   valid_6             43
    y#3#1#2   balan@1a            12
    y#3#1#2   balan@17            17
    y#3#1#2   balan@14            43
    y#3#1#3   BigM_51              1
    y#3#1#3   valid_8             12
    y#3#1#3   valid_7             17
    y#3#1#3   valid_6             43
    y#3#1#3   balan@1b            12
    y#3#1#3   balan@18            17
    y#3#1#3   balan@15            43
    y#3#2#1   BigM_52              1
    y#3#2#1   valid_8              6
    y#3#2#1   valid_7              2
    y#3#2#1   valid_6             64
    y#3#2#1   balan@19             6
    y#3#2#1   balan@16             2
    y#3#2#1   balan@13            64
    y#3#2#2   BigM_53              1
    y#3#2#2   valid_8              6
    y#3#2#2   valid_7              2
    y#3#2#2   valid_6             64
    y#3#2#2   balan@1a             6
    y#3#2#2   balan@17             2
    y#3#2#2   balan@14            64
    y#3#2#3   BigM_54              1
    y#3#2#3   valid_8              6
    y#3#2#3   valid_7              2
    y#3#2#3   valid_6             64
    y#3#2#3   balan@1b             6
    y#3#2#3   balan@18             2
    y#3#2#3   balan@15            64
    y#3#3#1   BigM_55              1
    y#3#3#1   valid_8             12
    y#3#3#1   valid_7             19
    y#3#3#1   valid_6             41
    y#3#3#1   balan@19            12
    y#3#3#1   balan@16            19
    y#3#3#1   balan@13            41
    y#3#3#2   BigM_56              1
    y#3#3#2   valid_8             12
    y#3#3#2   valid_7             19
    y#3#3#2   valid_6             41
    y#3#3#2   balan@1a            12
    y#3#3#2   balan@17            19
    y#3#3#2   balan@14            41
    y#3#3#3   BigM_57              1
    y#3#3#3   valid_8             12
    y#3#3#3   valid_7             19
    y#3#3#3   valid_6             41
    y#3#3#3   balan@1b            12
    y#3#3#3   balan@18            19
    y#3#3#3   balan@15            41
    y#3#4#1   BigM_58              1
    y#3#4#1   valid_8              3
    y#3#4#1   valid_7             37
    y#3#4#1   valid_6             32
    y#3#4#1   balan@19             3
    y#3#4#1   balan@16            37
    y#3#4#1   balan@13            32
    y#3#4#2   BigM_59              1
    y#3#4#2   valid_8              3
    y#3#4#2   valid_7             37
    y#3#4#2   valid_6             32
    y#3#4#2   balan@1a             3
    y#3#4#2   balan@17            37
    y#3#4#2   balan@14            32
    y#3#4#3   BigM_60              1
    y#3#4#3   valid_8              3
    y#3#4#3   valid_7             37
    y#3#4#3   valid_6             32
    y#3#4#3   balan@1b             3
    y#3#4#3   balan@18            37
    y#3#4#3   balan@15            32
    y#3#5#1   BigM_61              1
    y#3#5#1   valid_8             22
    y#3#5#1   valid_7             25
    y#3#5#1   valid_6             25
    y#3#5#1   balan@19            22
    y#3#5#1   balan@16            25
    y#3#5#1   balan@13            25
    y#3#5#2   BigM_62              1
    y#3#5#2   valid_8             22
    y#3#5#2   valid_7             25
    y#3#5#2   valid_6             25
    y#3#5#2   balan@1a            22
    y#3#5#2   balan@17            25
    y#3#5#2   balan@14            25
    y#3#5#3   BigM_63              1
    y#3#5#3   valid_8             22
    y#3#5#3   valid_7             25
    y#3#5#3   valid_6             25
    y#3#5#3   balan@1b            22
    y#3#5#3   balan@18            25
    y#3#5#3   balan@15            25
    y#3#6#1   BigM_64              1
    y#3#6#1   valid_8             51
    y#3#6#1   valid_7              9
    y#3#6#1   valid_6             12
    y#3#6#1   balan@19            51
    y#3#6#1   balan@16             9
    y#3#6#1   balan@13            12
    y#3#6#2   BigM_65              1
    y#3#6#2   valid_8             51
    y#3#6#2   valid_7              9
    y#3#6#2   valid_6             12
    y#3#6#2   balan@1a            51
    y#3#6#2   balan@17             9
    y#3#6#2   balan@14            12
    y#3#6#3   BigM_66              1
    y#3#6#3   valid_8             51
    y#3#6#3   valid_7              9
    y#3#6#3   valid_6             12
    y#3#6#3   balan@1b            51
    y#3#6#3   balan@18             9
    y#3#6#3   balan@15            12
    y#3#7#1   BigM_67              1
    y#3#7#1   valid_8              9
    y#3#7#1   valid_7             50
    y#3#7#1   valid_6             13
    y#3#7#1   balan@19             9
    y#3#7#1   balan@16            50
    y#3#7#1   balan@13            13
    y#3#7#2   BigM_68              1
    y#3#7#2   valid_8              9
    y#3#7#2   valid_7             50
    y#3#7#2   valid_6             13
    y#3#7#2   balan@1a             9
    y#3#7#2   balan@17            50
    y#3#7#2   balan@14            13
    y#3#7#3   BigM_69              1
    y#3#7#3   valid_8              9
    y#3#7#3   valid_7             50
    y#3#7#3   valid_6             13
    y#3#7#3   balan@1b             9
    y#3#7#3   balan@18            50
    y#3#7#3   balan@15            13
    y#3#8#1   BigM_70              1
    y#3#8#1   valid_8              5
    y#3#8#1   valid_7             31
    y#3#8#1   valid_6             36
    y#3#8#1   balan@19             5
    y#3#8#1   balan@16            31
    y#3#8#1   balan@13            36
    y#3#8#2   BigM_71              1
    y#3#8#2   valid_8              5
    y#3#8#2   valid_7             31
    y#3#8#2   valid_6             36
    y#3#8#2   balan@1a             5
    y#3#8#2   balan@17            31
    y#3#8#2   balan@14            36
    y#3#8#3   BigM_72              1
    y#3#8#3   valid_8              5
    y#3#8#3   valid_7             31
    y#3#8#3   valid_6             36
    y#3#8#3   balan@1b             5
    y#3#8#3   balan@18            31
    y#3#8#3   balan@15            36
    y#4#1#1   BigM_73              1
    y#4#1#1   valid_10            12
    y#4#1#1   valid_9             17
    y#4#1#1   balan@22            12
    y#4#1#1   balan@1f            17
    y#4#1#1   balan@1c            43
    y#4#1#2   BigM_74              1
    y#4#1#2   valid_10            12
    y#4#1#2   valid_9             17
    y#4#1#2   balan@23            12
    y#4#1#2   balan@20            17
    y#4#1#2   balan@1d            43
    y#4#1#3   BigM_75              1
    y#4#1#3   valid_10            12
    y#4#1#3   valid_9             17
    y#4#1#3   balan@24            12
    y#4#1#3   balan@21            17
    y#4#1#3   balan@1e            43
    y#4#2#1   BigM_76              1
    y#4#2#1   valid_10             6
    y#4#2#1   valid_9              2
    y#4#2#1   balan@22             6
    y#4#2#1   balan@1f             2
    y#4#2#1   balan@1c            64
    y#4#2#2   BigM_77              1
    y#4#2#2   valid_10             6
    y#4#2#2   valid_9              2
    y#4#2#2   balan@23             6
    y#4#2#2   balan@20             2
    y#4#2#2   balan@1d            64
    y#4#2#3   BigM_78              1
    y#4#2#3   valid_10             6
    y#4#2#3   valid_9              2
    y#4#2#3   balan@24             6
    y#4#2#3   balan@21             2
    y#4#2#3   balan@1e            64
    y#4#3#1   BigM_79              1
    y#4#3#1   valid_10            12
    y#4#3#1   valid_9             19
    y#4#3#1   balan@22            12
    y#4#3#1   balan@1f            19
    y#4#3#1   balan@1c            41
    y#4#3#2   BigM_80              1
    y#4#3#2   valid_10            12
    y#4#3#2   valid_9             19
    y#4#3#2   balan@23            12
    y#4#3#2   balan@20            19
    y#4#3#2   balan@1d            41
    y#4#3#3   BigM_81              1
    y#4#3#3   valid_10            12
    y#4#3#3   valid_9             19
    y#4#3#3   balan@24            12
    y#4#3#3   balan@21            19
    y#4#3#3   balan@1e            41
    y#4#4#1   BigM_82              1
    y#4#4#1   valid_10             3
    y#4#4#1   valid_9             37
    y#4#4#1   balan@22             3
    y#4#4#1   balan@1f            37
    y#4#4#1   balan@1c            32
    y#4#4#2   BigM_83              1
    y#4#4#2   valid_10             3
    y#4#4#2   valid_9             37
    y#4#4#2   balan@23             3
    y#4#4#2   balan@20            37
    y#4#4#2   balan@1d            32
    y#4#4#3   BigM_84              1
    y#4#4#3   valid_10             3
    y#4#4#3   valid_9             37
    y#4#4#3   balan@24             3
    y#4#4#3   balan@21            37
    y#4#4#3   balan@1e            32
    y#4#5#1   BigM_85              1
    y#4#5#1   valid_10            22
    y#4#5#1   valid_9             25
    y#4#5#1   balan@22            22
    y#4#5#1   balan@1f            25
    y#4#5#1   balan@1c            25
    y#4#5#2   BigM_86              1
    y#4#5#2   valid_10            22
    y#4#5#2   valid_9             25
    y#4#5#2   balan@23            22
    y#4#5#2   balan@20            25
    y#4#5#2   balan@1d            25
    y#4#5#3   BigM_87              1
    y#4#5#3   valid_10            22
    y#4#5#3   valid_9             25
    y#4#5#3   balan@24            22
    y#4#5#3   balan@21            25
    y#4#5#3   balan@1e            25
    y#4#6#1   BigM_88              1
    y#4#6#1   valid_10            51
    y#4#6#1   valid_9              9
    y#4#6#1   balan@22            51
    y#4#6#1   balan@1f             9
    y#4#6#1   balan@1c            12
    y#4#6#2   BigM_89              1
    y#4#6#2   valid_10            51
    y#4#6#2   valid_9              9
    y#4#6#2   balan@23            51
    y#4#6#2   balan@20             9
    y#4#6#2   balan@1d            12
    y#4#6#3   BigM_90              1
    y#4#6#3   valid_10            51
    y#4#6#3   valid_9              9
    y#4#6#3   balan@24            51
    y#4#6#3   balan@21             9
    y#4#6#3   balan@1e            12
    y#4#7#1   BigM_91              1
    y#4#7#1   valid_10             9
    y#4#7#1   valid_9             50
    y#4#7#1   balan@22             9
    y#4#7#1   balan@1f            50
    y#4#7#1   balan@1c            13
    y#4#7#2   BigM_92              1
    y#4#7#2   valid_10             9
    y#4#7#2   valid_9             50
    y#4#7#2   balan@23             9
    y#4#7#2   balan@20            50
    y#4#7#2   balan@1d            13
    y#4#7#3   BigM_93              1
    y#4#7#3   valid_10             9
    y#4#7#3   valid_9             50
    y#4#7#3   balan@24             9
    y#4#7#3   balan@21            50
    y#4#7#3   balan@1e            13
    y#4#8#1   BigM_94              1
    y#4#8#1   valid_10             5
    y#4#8#1   valid_9             31
    y#4#8#1   balan@22             5
    y#4#8#1   balan@1f            31
    y#4#8#1   balan@1c            36
    y#4#8#2   BigM_95              1
    y#4#8#2   valid_10             5
    y#4#8#2   valid_9             31
    y#4#8#2   balan@23             5
    y#4#8#2   balan@20            31
    y#4#8#2   balan@1d            36
    y#4#8#3   BigM_96              1
    y#4#8#3   valid_10             5
    y#4#8#3   valid_9             31
    y#4#8#3   balan@24             5
    y#4#8#3   balan@21            31
    y#4#8#3   balan@1e            36
    y#5#1#1   BigM_97              1
    y#5#1#1   valid_12            17
    y#5#1#1   valid_11            43
    y#5#1#1   balan@2b            12
    y#5#1#1   balan@28            17
    y#5#1#1   balan@25            43
    y#5#1#2   BigM_98              1
    y#5#1#2   valid_12            17
    y#5#1#2   valid_11            43
    y#5#1#2   balan@2c            12
    y#5#1#2   balan@29            17
    y#5#1#2   balan@26            43
    y#5#1#3   BigM_99              1
    y#5#1#3   valid_12            17
    y#5#1#3   valid_11            43
    y#5#1#3   balan@2d            12
    y#5#1#3   balan@2a            17
    y#5#1#3   balan@27            43
    y#5#2#1   BigM_100             1
    y#5#2#1   valid_12             2
    y#5#2#1   valid_11            64
    y#5#2#1   balan@2b             6
    y#5#2#1   balan@28             2
    y#5#2#1   balan@25            64
    y#5#2#2   BigM_101             1
    y#5#2#2   valid_12             2
    y#5#2#2   valid_11            64
    y#5#2#2   balan@2c             6
    y#5#2#2   balan@29             2
    y#5#2#2   balan@26            64
    y#5#2#3   BigM_102             1
    y#5#2#3   valid_12             2
    y#5#2#3   valid_11            64
    y#5#2#3   balan@2d             6
    y#5#2#3   balan@2a             2
    y#5#2#3   balan@27            64
    y#5#3#1   BigM_103             1
    y#5#3#1   valid_12            19
    y#5#3#1   valid_11            41
    y#5#3#1   balan@2b            12
    y#5#3#1   balan@28            19
    y#5#3#1   balan@25            41
    y#5#3#2   BigM_104             1
    y#5#3#2   valid_12            19
    y#5#3#2   valid_11            41
    y#5#3#2   balan@2c            12
    y#5#3#2   balan@29            19
    y#5#3#2   balan@26            41
    y#5#3#3   BigM_105             1
    y#5#3#3   valid_12            19
    y#5#3#3   valid_11            41
    y#5#3#3   balan@2d            12
    y#5#3#3   balan@2a            19
    y#5#3#3   balan@27            41
    y#5#4#1   BigM_106             1
    y#5#4#1   valid_12            37
    y#5#4#1   valid_11            32
    y#5#4#1   balan@2b             3
    y#5#4#1   balan@28            37
    y#5#4#1   balan@25            32
    y#5#4#2   BigM_107             1
    y#5#4#2   valid_12            37
    y#5#4#2   valid_11            32
    y#5#4#2   balan@2c             3
    y#5#4#2   balan@29            37
    y#5#4#2   balan@26            32
    y#5#4#3   BigM_108             1
    y#5#4#3   valid_12            37
    y#5#4#3   valid_11            32
    y#5#4#3   balan@2d             3
    y#5#4#3   balan@2a            37
    y#5#4#3   balan@27            32
    y#5#5#1   BigM_109             1
    y#5#5#1   valid_12            25
    y#5#5#1   valid_11            25
    y#5#5#1   balan@2b            22
    y#5#5#1   balan@28            25
    y#5#5#1   balan@25            25
    y#5#5#2   BigM_110             1
    y#5#5#2   valid_12            25
    y#5#5#2   valid_11            25
    y#5#5#2   balan@2c            22
    y#5#5#2   balan@29            25
    y#5#5#2   balan@26            25
    y#5#5#3   BigM_111             1
    y#5#5#3   valid_12            25
    y#5#5#3   valid_11            25
    y#5#5#3   balan@2d            22
    y#5#5#3   balan@2a            25
    y#5#5#3   balan@27            25
    y#5#6#1   BigM_112             1
    y#5#6#1   valid_12             9
    y#5#6#1   valid_11            12
    y#5#6#1   balan@2b            51
    y#5#6#1   balan@28             9
    y#5#6#1   balan@25            12
    y#5#6#2   BigM_113             1
    y#5#6#2   valid_12             9
    y#5#6#2   valid_11            12
    y#5#6#2   balan@2c            51
    y#5#6#2   balan@29             9
    y#5#6#2   balan@26            12
    y#5#6#3   BigM_114             1
    y#5#6#3   valid_12             9
    y#5#6#3   valid_11            12
    y#5#6#3   balan@2d            51
    y#5#6#3   balan@2a             9
    y#5#6#3   balan@27            12
    y#5#7#1   BigM_115             1
    y#5#7#1   valid_12            50
    y#5#7#1   valid_11            13
    y#5#7#1   balan@2b             9
    y#5#7#1   balan@28            50
    y#5#7#1   balan@25            13
    y#5#7#2   BigM_116             1
    y#5#7#2   valid_12            50
    y#5#7#2   valid_11            13
    y#5#7#2   balan@2c             9
    y#5#7#2   balan@29            50
    y#5#7#2   balan@26            13
    y#5#7#3   BigM_117             1
    y#5#7#3   valid_12            50
    y#5#7#3   valid_11            13
    y#5#7#3   balan@2d             9
    y#5#7#3   balan@2a            50
    y#5#7#3   balan@27            13
    y#5#8#1   BigM_118             1
    y#5#8#1   valid_12            31
    y#5#8#1   valid_11            36
    y#5#8#1   balan@2b             5
    y#5#8#1   balan@28            31
    y#5#8#1   balan@25            36
    y#5#8#2   BigM_119             1
    y#5#8#2   valid_12            31
    y#5#8#2   valid_11            36
    y#5#8#2   balan@2c             5
    y#5#8#2   balan@29            31
    y#5#8#2   balan@26            36
    y#5#8#3   BigM_120             1
    y#5#8#3   valid_12            31
    y#5#8#3   valid_11            36
    y#5#8#3   balan@2d             5
    y#5#8#3   balan@2a            31
    y#5#8#3   balan@27            36
    y#6#1#1   BigM_121             1
    y#6#1#1   valid_14            17
    y#6#1#1   valid_13            43
    y#6#1#1   balan@34            12
    y#6#1#1   balan@31            17
    y#6#1#1   balan@2e            43
    y#6#1#2   BigM_122             1
    y#6#1#2   valid_14            17
    y#6#1#2   valid_13            43
    y#6#1#2   balan@35            12
    y#6#1#2   balan@32            17
    y#6#1#2   balan@2f            43
    y#6#1#3   BigM_123             1
    y#6#1#3   valid_14            17
    y#6#1#3   valid_13            43
    y#6#1#3   balan@36            12
    y#6#1#3   balan@33            17
    y#6#1#3   balan@30            43
    y#6#2#1   BigM_124             1
    y#6#2#1   valid_14             2
    y#6#2#1   valid_13            64
    y#6#2#1   balan@34             6
    y#6#2#1   balan@31             2
    y#6#2#1   balan@2e            64
    y#6#2#2   BigM_125             1
    y#6#2#2   valid_14             2
    y#6#2#2   valid_13            64
    y#6#2#2   balan@35             6
    y#6#2#2   balan@32             2
    y#6#2#2   balan@2f            64
    y#6#2#3   BigM_126             1
    y#6#2#3   valid_14             2
    y#6#2#3   valid_13            64
    y#6#2#3   balan@36             6
    y#6#2#3   balan@33             2
    y#6#2#3   balan@30            64
    y#6#3#1   BigM_127             1
    y#6#3#1   valid_14            19
    y#6#3#1   valid_13            41
    y#6#3#1   balan@34            12
    y#6#3#1   balan@31            19
    y#6#3#1   balan@2e            41
    y#6#3#2   BigM_128             1
    y#6#3#2   valid_14            19
    y#6#3#2   valid_13            41
    y#6#3#2   balan@35            12
    y#6#3#2   balan@32            19
    y#6#3#2   balan@2f            41
    y#6#3#3   BigM_129             1
    y#6#3#3   valid_14            19
    y#6#3#3   valid_13            41
    y#6#3#3   balan@36            12
    y#6#3#3   balan@33            19
    y#6#3#3   balan@30            41
    y#6#4#1   BigM_130             1
    y#6#4#1   valid_14            37
    y#6#4#1   valid_13            32
    y#6#4#1   balan@34             3
    y#6#4#1   balan@31            37
    y#6#4#1   balan@2e            32
    y#6#4#2   BigM_131             1
    y#6#4#2   valid_14            37
    y#6#4#2   valid_13            32
    y#6#4#2   balan@35             3
    y#6#4#2   balan@32            37
    y#6#4#2   balan@2f            32
    y#6#4#3   BigM_132             1
    y#6#4#3   valid_14            37
    y#6#4#3   valid_13            32
    y#6#4#3   balan@36             3
    y#6#4#3   balan@33            37
    y#6#4#3   balan@30            32
    y#6#5#1   BigM_133             1
    y#6#5#1   valid_14            25
    y#6#5#1   valid_13            25
    y#6#5#1   balan@34            22
    y#6#5#1   balan@31            25
    y#6#5#1   balan@2e            25
    y#6#5#2   BigM_134             1
    y#6#5#2   valid_14            25
    y#6#5#2   valid_13            25
    y#6#5#2   balan@35            22
    y#6#5#2   balan@32            25
    y#6#5#2   balan@2f            25
    y#6#5#3   BigM_135             1
    y#6#5#3   valid_14            25
    y#6#5#3   valid_13            25
    y#6#5#3   balan@36            22
    y#6#5#3   balan@33            25
    y#6#5#3   balan@30            25
    y#6#6#1   BigM_136             1
    y#6#6#1   valid_14             9
    y#6#6#1   valid_13            12
    y#6#6#1   balan@34            51
    y#6#6#1   balan@31             9
    y#6#6#1   balan@2e            12
    y#6#6#2   BigM_137             1
    y#6#6#2   valid_14             9
    y#6#6#2   valid_13            12
    y#6#6#2   balan@35            51
    y#6#6#2   balan@32             9
    y#6#6#2   balan@2f            12
    y#6#6#3   BigM_138             1
    y#6#6#3   valid_14             9
    y#6#6#3   valid_13            12
    y#6#6#3   balan@36            51
    y#6#6#3   balan@33             9
    y#6#6#3   balan@30            12
    y#6#7#1   BigM_139             1
    y#6#7#1   valid_14            50
    y#6#7#1   valid_13            13
    y#6#7#1   balan@34             9
    y#6#7#1   balan@31            50
    y#6#7#1   balan@2e            13
    y#6#7#2   BigM_140             1
    y#6#7#2   valid_14            50
    y#6#7#2   valid_13            13
    y#6#7#2   balan@35             9
    y#6#7#2   balan@32            50
    y#6#7#2   balan@2f            13
    y#6#7#3   BigM_141             1
    y#6#7#3   valid_14            50
    y#6#7#3   valid_13            13
    y#6#7#3   balan@36             9
    y#6#7#3   balan@33            50
    y#6#7#3   balan@30            13
    y#6#8#1   BigM_142             1
    y#6#8#1   valid_14            31
    y#6#8#1   valid_13            36
    y#6#8#1   balan@34             5
    y#6#8#1   balan@31            31
    y#6#8#1   balan@2e            36
    y#6#8#2   BigM_143             1
    y#6#8#2   valid_14            31
    y#6#8#2   valid_13            36
    y#6#8#2   balan@35             5
    y#6#8#2   balan@32            31
    y#6#8#2   balan@2f            36
    y#6#8#3   BigM_144             1
    y#6#8#3   valid_14            31
    y#6#8#3   valid_13            36
    y#6#8#3   balan@36             5
    y#6#8#3   balan@33            31
    y#6#8#3   balan@30            36
    p#1       BigM_123         -1000
    p#1       BigM_122         -1000
    p#1       BigM_121         -1000
    p#1       BigM_99          -1000
    p#1       BigM_98          -1000
    p#1       BigM_97          -1000
    p#1       BigM_75          -1000
    p#1       BigM_74          -1000
    p#1       BigM_73          -1000
    p#1       BigM_51          -1000
    p#1       BigM_50          -1000
    p#1       BigM_49          -1000
    p#1       BigM_27          -1000
    p#1       BigM_26          -1000
    p#1       BigM_25          -1000
    p#1       BigM_3           -1000
    p#1       BigM_2           -1000
    p#1       BigM_1           -1000
    p#1       select_1             1
    p#2       BigM_126         -1000
    p#2       BigM_125         -1000
    p#2       BigM_124         -1000
    p#2       BigM_102         -1000
    p#2       BigM_101         -1000
    p#2       BigM_100         -1000
    p#2       BigM_78          -1000
    p#2       BigM_77          -1000
    p#2       BigM_76          -1000
    p#2       BigM_54          -1000
    p#2       BigM_53          -1000
    p#2       BigM_52          -1000
    p#2       BigM_30          -1000
    p#2       BigM_29          -1000
    p#2       BigM_28          -1000
    p#2       BigM_6           -1000
    p#2       BigM_5           -1000
    p#2       BigM_4           -1000
    p#2       select_1             1
    p#3       BigM_129         -1000
    p#3       BigM_128         -1000
    p#3       BigM_127         -1000
    p#3       BigM_105         -1000
    p#3       BigM_104         -1000
    p#3       BigM_103         -1000
    p#3       BigM_81          -1000
    p#3       BigM_80          -1000
    p#3       BigM_79          -1000
    p#3       BigM_57          -1000
    p#3       BigM_56          -1000
    p#3       BigM_55          -1000
    p#3       BigM_33          -1000
    p#3       BigM_32          -1000
    p#3       BigM_31          -1000
    p#3       BigM_9           -1000
    p#3       BigM_8           -1000
    p#3       BigM_7           -1000
    p#3       select_1             1
    p#4       BigM_132         -1000
    p#4       BigM_131         -1000
    p#4       BigM_130         -1000
    p#4       BigM_108         -1000
    p#4       BigM_107         -1000
    p#4       BigM_106         -1000
    p#4       BigM_84          -1000
    p#4       BigM_83          -1000
    p#4       BigM_82          -1000
    p#4       BigM_60          -1000
    p#4       BigM_59          -1000
    p#4       BigM_58          -1000
    p#4       BigM_36          -1000
    p#4       BigM_35          -1000
    p#4       BigM_34          -1000
    p#4       BigM_12          -1000
    p#4       BigM_11          -1000
    p#4       BigM_10          -1000
    p#4       select_1             1
    p#5       BigM_135         -1000
    p#5       BigM_134         -1000
    p#5       BigM_133         -1000
    p#5       BigM_111         -1000
    p#5       BigM_110         -1000
    p#5       BigM_109         -1000
    p#5       BigM_87          -1000
    p#5       BigM_86          -1000
    p#5       BigM_85          -1000
    p#5       BigM_63          -1000
    p#5       BigM_62          -1000
    p#5       BigM_61          -1000
    p#5       BigM_39          -1000
    p#5       BigM_38          -1000
    p#5       BigM_37          -1000
    p#5       BigM_15          -1000
    p#5       BigM_14          -1000
    p#5       BigM_13          -1000
    p#5       select_1             1
    p#6       BigM_138         -1000
    p#6       BigM_137         -1000
    p#6       BigM_136         -1000
    p#6       BigM_114         -1000
    p#6       BigM_113         -1000
    p#6       BigM_112         -1000
    p#6       BigM_90          -1000
    p#6       BigM_89          -1000
    p#6       BigM_88          -1000
    p#6       BigM_66          -1000
    p#6       BigM_65          -1000
    p#6       BigM_64          -1000
    p#6       BigM_42          -1000
    p#6       BigM_41          -1000
    p#6       BigM_40          -1000
    p#6       BigM_18          -1000
    p#6       BigM_17          -1000
    p#6       BigM_16          -1000
    p#6       select_1             1
    p#7       BigM_141         -1000
    p#7       BigM_140         -1000
    p#7       BigM_139         -1000
    p#7       BigM_117         -1000
    p#7       BigM_116         -1000
    p#7       BigM_115         -1000
    p#7       BigM_93          -1000
    p#7       BigM_92          -1000
    p#7       BigM_91          -1000
    p#7       BigM_69          -1000
    p#7       BigM_68          -1000
    p#7       BigM_67          -1000
    p#7       BigM_45          -1000
    p#7       BigM_44          -1000
    p#7       BigM_43          -1000
    p#7       BigM_21          -1000
    p#7       BigM_20          -1000
    p#7       BigM_19          -1000
    p#7       select_1             1
    p#8       BigM_144         -1000
    p#8       BigM_143         -1000
    p#8       BigM_142         -1000
    p#8       BigM_120         -1000
    p#8       BigM_119         -1000
    p#8       BigM_118         -1000
    p#8       BigM_96          -1000
    p#8       BigM_95          -1000
    p#8       BigM_94          -1000
    p#8       BigM_72          -1000
    p#8       BigM_71          -1000
    p#8       BigM_70          -1000
    p#8       BigM_48          -1000
    p#8       BigM_47          -1000
    p#8       BigM_46          -1000
    p#8       BigM_24          -1000
    p#8       BigM_23          -1000
    p#8       BigM_22          -1000
    p#8       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    B#1#1#0   init2_1              1
    B#1#1#0   balanc@1            -1
    B#1#1#1   OBJECTIV             5
    B#1#1#1   balanc@2            -1
    B#1#1#1   balanc@1             1
    B#1#1#2   OBJECTIV             5
    B#1#1#2   balanc@3            -1
    B#1#1#2   balanc@2             1
    B#1#1#3   OBJECTIV             5
    B#1#1#3   init3_1              1
    B#1#1#3   balanc@3             1
    B#1#2#0   init2_2              1
    B#1#2#0   balanc@4            -1
    B#1#2#1   OBJECTIV           5.5
    B#1#2#1   balanc@5            -1
    B#1#2#1   balanc@4             1
    B#1#2#2   OBJECTIV           5.5
    B#1#2#2   balanc@6            -1
    B#1#2#2   balanc@5             1
    B#1#2#3   OBJECTIV           5.5
    B#1#2#3   init3_2              1
    B#1#2#3   balanc@6             1
    B#1#3#0   init2_3              1
    B#1#3#0   balanc@7            -1
    B#1#3#1   OBJECTIV           5.5
    B#1#3#1   balanc@8            -1
    B#1#3#1   balanc@7             1
    B#1#3#2   OBJECTIV           5.5
    B#1#3#2   balanc@9            -1
    B#1#3#2   balanc@8             1
    B#1#3#3   OBJECTIV           5.5
    B#1#3#3   init3_3              1
    B#1#3#3   balanc@9             1
    B#2#1#0   init2_4              1
    B#2#1#0   balanc@a            -1
    B#2#1#1   OBJECTIV             5
    B#2#1#1   balanc@b            -1
    B#2#1#1   balanc@a             1
    B#2#1#2   OBJECTIV             5
    B#2#1#2   balanc@c            -1
    B#2#1#2   balanc@b             1
    B#2#1#3   OBJECTIV             5
    B#2#1#3   init3_4              1
    B#2#1#3   balanc@c             1
    B#2#2#0   init2_5              1
    B#2#2#0   balanc@d            -1
    B#2#2#1   OBJECTIV           5.5
    B#2#2#1   balanc@e            -1
    B#2#2#1   balanc@d             1
    B#2#2#2   OBJECTIV           5.5
    B#2#2#2   balanc@f            -1
    B#2#2#2   balanc@e             1
    B#2#2#3   OBJECTIV           5.5
    B#2#2#3   init3_5              1
    B#2#2#3   balanc@f             1
    B#2#3#0   init2_6              1
    B#2#3#0   balan@10            -1
    B#2#3#1   OBJECTIV           5.5
    B#2#3#1   balan@11            -1
    B#2#3#1   balan@10             1
    B#2#3#2   OBJECTIV           5.5
    B#2#3#2   balan@12            -1
    B#2#3#2   balan@11             1
    B#2#3#3   OBJECTIV           5.5
    B#2#3#3   init3_6              1
    B#2#3#3   balan@12             1
    B#3#1#0   init2_7              1
    B#3#1#0   balan@13            -1
    B#3#1#1   OBJECTIV             5
    B#3#1#1   balan@14            -1
    B#3#1#1   balan@13             1
    B#3#1#2   OBJECTIV             5
    B#3#1#2   balan@15            -1
    B#3#1#2   balan@14             1
    B#3#1#3   OBJECTIV             5
    B#3#1#3   init3_7              1
    B#3#1#3   balan@15             1
    B#3#2#0   init2_8              1
    B#3#2#0   balan@16            -1
    B#3#2#1   OBJECTIV           5.5
    B#3#2#1   balan@17            -1
    B#3#2#1   balan@16             1
    B#3#2#2   OBJECTIV           5.5
    B#3#2#2   balan@18            -1
    B#3#2#2   balan@17             1
    B#3#2#3   OBJECTIV           5.5
    B#3#2#3   init3_8              1
    B#3#2#3   balan@18             1
    B#3#3#0   init2_9              1
    B#3#3#0   balan@19            -1
    B#3#3#1   OBJECTIV           5.5
    B#3#3#1   balan@1a            -1
    B#3#3#1   balan@19             1
    B#3#3#2   OBJECTIV           5.5
    B#3#3#2   balan@1b            -1
    B#3#3#2   balan@1a             1
    B#3#3#3   OBJECTIV           5.5
    B#3#3#3   init3_9              1
    B#3#3#3   balan@1b             1
    B#4#1#0   init2_10             1
    B#4#1#0   balan@1c            -1
    B#4#1#1   OBJECTIV             5
    B#4#1#1   balan@1d            -1
    B#4#1#1   balan@1c             1
    B#4#1#2   OBJECTIV             5
    B#4#1#2   balan@1e            -1
    B#4#1#2   balan@1d             1
    B#4#1#3   OBJECTIV             5
    B#4#1#3   init3_10             1
    B#4#1#3   balan@1e             1
    B#4#2#0   init2_11             1
    B#4#2#0   balan@1f            -1
    B#4#2#1   OBJECTIV           5.5
    B#4#2#1   balan@20            -1
    B#4#2#1   balan@1f             1
    B#4#2#2   OBJECTIV           5.5
    B#4#2#2   balan@21            -1
    B#4#2#2   balan@20             1
    B#4#2#3   OBJECTIV           5.5
    B#4#2#3   init3_11             1
    B#4#2#3   balan@21             1
    B#4#3#0   init2_12             1
    B#4#3#0   balan@22            -1
    B#4#3#1   OBJECTIV           5.5
    B#4#3#1   balan@23            -1
    B#4#3#1   balan@22             1
    B#4#3#2   OBJECTIV           5.5
    B#4#3#2   balan@24            -1
    B#4#3#2   balan@23             1
    B#4#3#3   OBJECTIV           5.5
    B#4#3#3   init3_12             1
    B#4#3#3   balan@24             1
    B#5#1#0   init2_13             1
    B#5#1#0   balan@25            -1
    B#5#1#1   OBJECTIV             5
    B#5#1#1   balan@26            -1
    B#5#1#1   balan@25             1
    B#5#1#2   OBJECTIV             5
    B#5#1#2   balan@27            -1
    B#5#1#2   balan@26             1
    B#5#1#3   OBJECTIV             5
    B#5#1#3   init3_13             1
    B#5#1#3   balan@27             1
    B#5#2#0   init2_14             1
    B#5#2#0   balan@28            -1
    B#5#2#1   OBJECTIV           5.5
    B#5#2#1   balan@29            -1
    B#5#2#1   balan@28             1
    B#5#2#2   OBJECTIV           5.5
    B#5#2#2   balan@2a            -1
    B#5#2#2   balan@29             1
    B#5#2#3   OBJECTIV           5.5
    B#5#2#3   init3_14             1
    B#5#2#3   balan@2a             1
    B#5#3#0   init2_15             1
    B#5#3#0   balan@2b            -1
    B#5#3#1   OBJECTIV           5.5
    B#5#3#1   balan@2c            -1
    B#5#3#1   balan@2b             1
    B#5#3#2   OBJECTIV           5.5
    B#5#3#2   balan@2d            -1
    B#5#3#2   balan@2c             1
    B#5#3#3   OBJECTIV           5.5
    B#5#3#3   init3_15             1
    B#5#3#3   balan@2d             1
    B#6#1#0   init2_16             1
    B#6#1#0   balan@2e            -1
    B#6#1#1   OBJECTIV             5
    B#6#1#1   balan@2f            -1
    B#6#1#1   balan@2e             1
    B#6#1#2   OBJECTIV             5
    B#6#1#2   balan@30            -1
    B#6#1#2   balan@2f             1
    B#6#1#3   OBJECTIV             5
    B#6#1#3   init3_16             1
    B#6#1#3   balan@30             1
    B#6#2#0   init2_17             1
    B#6#2#0   balan@31            -1
    B#6#2#1   OBJECTIV           5.5
    B#6#2#1   balan@32            -1
    B#6#2#1   balan@31             1
    B#6#2#2   OBJECTIV           5.5
    B#6#2#2   balan@33            -1
    B#6#2#2   balan@32             1
    B#6#2#3   OBJECTIV           5.5
    B#6#2#3   init3_17             1
    B#6#2#3   balan@33             1
    B#6#3#0   init2_18             1
    B#6#3#0   balan@34            -1
    B#6#3#1   OBJECTIV           5.5
    B#6#3#1   balan@35            -1
    B#6#3#1   balan@34             1
    B#6#3#2   OBJECTIV           5.5
    B#6#3#2   balan@36            -1
    B#6#3#2   balan@35             1
    B#6#3#3   OBJECTIV           5.5
    B#6#3#3   init3_18             1
    B#6#3#3   balan@36             1
    I#1#1#0   init1_1              1
    I#1#1#0   balanc@1             1
    I#1#1#1   OBJECTIV             1
    I#1#1#1   balanc@2             1
    I#1#1#1   balanc@1            -1
    I#1#1#2   OBJECTIV             1
    I#1#1#2   balanc@3             1
    I#1#1#2   balanc@2            -1
    I#1#1#3   OBJECTIV             1
    I#1#1#3   balanc@3            -1
    I#1#2#0   init1_2              1
    I#1#2#0   balanc@4             1
    I#1#2#1   OBJECTIV           1.1
    I#1#2#1   balanc@5             1
    I#1#2#1   balanc@4            -1
    I#1#2#2   OBJECTIV           1.1
    I#1#2#2   balanc@6             1
    I#1#2#2   balanc@5            -1
    I#1#2#3   OBJECTIV           1.1
    I#1#2#3   balanc@6            -1
    I#1#3#0   init1_3              1
    I#1#3#0   balanc@7             1
    I#1#3#1   OBJECTIV           1.1
    I#1#3#1   balanc@8             1
    I#1#3#1   balanc@7            -1
    I#1#3#2   OBJECTIV           1.1
    I#1#3#2   balanc@9             1
    I#1#3#2   balanc@8            -1
    I#1#3#3   OBJECTIV           1.1
    I#1#3#3   balanc@9            -1
    I#2#1#0   init1_4              1
    I#2#1#0   balanc@a             1
    I#2#1#1   OBJECTIV             1
    I#2#1#1   balanc@b             1
    I#2#1#1   balanc@a            -1
    I#2#1#2   OBJECTIV             1
    I#2#1#2   balanc@c             1
    I#2#1#2   balanc@b            -1
    I#2#1#3   OBJECTIV             1
    I#2#1#3   balanc@c            -1
    I#2#2#0   init1_5              1
    I#2#2#0   balanc@d             1
    I#2#2#1   OBJECTIV           1.1
    I#2#2#1   balanc@e             1
    I#2#2#1   balanc@d            -1
    I#2#2#2   OBJECTIV           1.1
    I#2#2#2   balanc@f             1
    I#2#2#2   balanc@e            -1
    I#2#2#3   OBJECTIV           1.1
    I#2#2#3   balanc@f            -1
    I#2#3#0   init1_6              1
    I#2#3#0   balan@10             1
    I#2#3#1   OBJECTIV           1.1
    I#2#3#1   balan@11             1
    I#2#3#1   balan@10            -1
    I#2#3#2   OBJECTIV           1.1
    I#2#3#2   balan@12             1
    I#2#3#2   balan@11            -1
    I#2#3#3   OBJECTIV           1.1
    I#2#3#3   balan@12            -1
    I#3#1#0   init1_7              1
    I#3#1#0   balan@13             1
    I#3#1#1   OBJECTIV             1
    I#3#1#1   balan@14             1
    I#3#1#1   balan@13            -1
    I#3#1#2   OBJECTIV             1
    I#3#1#2   balan@15             1
    I#3#1#2   balan@14            -1
    I#3#1#3   OBJECTIV             1
    I#3#1#3   balan@15            -1
    I#3#2#0   init1_8              1
    I#3#2#0   balan@16             1
    I#3#2#1   OBJECTIV           1.1
    I#3#2#1   balan@17             1
    I#3#2#1   balan@16            -1
    I#3#2#2   OBJECTIV           1.1
    I#3#2#2   balan@18             1
    I#3#2#2   balan@17            -1
    I#3#2#3   OBJECTIV           1.1
    I#3#2#3   balan@18            -1
    I#3#3#0   init1_9              1
    I#3#3#0   balan@19             1
    I#3#3#1   OBJECTIV           1.1
    I#3#3#1   balan@1a             1
    I#3#3#1   balan@19            -1
    I#3#3#2   OBJECTIV           1.1
    I#3#3#2   balan@1b             1
    I#3#3#2   balan@1a            -1
    I#3#3#3   OBJECTIV           1.1
    I#3#3#3   balan@1b            -1
    I#4#1#0   init1_10             1
    I#4#1#0   balan@1c             1
    I#4#1#1   OBJECTIV             1
    I#4#1#1   balan@1d             1
    I#4#1#1   balan@1c            -1
    I#4#1#2   OBJECTIV             1
    I#4#1#2   balan@1e             1
    I#4#1#2   balan@1d            -1
    I#4#1#3   OBJECTIV             1
    I#4#1#3   balan@1e            -1
    I#4#2#0   init1_11             1
    I#4#2#0   balan@1f             1
    I#4#2#1   OBJECTIV           1.1
    I#4#2#1   balan@20             1
    I#4#2#1   balan@1f            -1
    I#4#2#2   OBJECTIV           1.1
    I#4#2#2   balan@21             1
    I#4#2#2   balan@20            -1
    I#4#2#3   OBJECTIV           1.1
    I#4#2#3   balan@21            -1
    I#4#3#0   init1_12             1
    I#4#3#0   balan@22             1
    I#4#3#1   OBJECTIV           1.1
    I#4#3#1   balan@23             1
    I#4#3#1   balan@22            -1
    I#4#3#2   OBJECTIV           1.1
    I#4#3#2   balan@24             1
    I#4#3#2   balan@23            -1
    I#4#3#3   OBJECTIV           1.1
    I#4#3#3   balan@24            -1
    I#5#1#0   init1_13             1
    I#5#1#0   balan@25             1
    I#5#1#1   OBJECTIV             1
    I#5#1#1   balan@26             1
    I#5#1#1   balan@25            -1
    I#5#1#2   OBJECTIV             1
    I#5#1#2   balan@27             1
    I#5#1#2   balan@26            -1
    I#5#1#3   OBJECTIV             1
    I#5#1#3   balan@27            -1
    I#5#2#0   init1_14             1
    I#5#2#0   balan@28             1
    I#5#2#1   OBJECTIV           1.1
    I#5#2#1   balan@29             1
    I#5#2#1   balan@28            -1
    I#5#2#2   OBJECTIV           1.1
    I#5#2#2   balan@2a             1
    I#5#2#2   balan@29            -1
    I#5#2#3   OBJECTIV           1.1
    I#5#2#3   balan@2a            -1
    I#5#3#0   init1_15             1
    I#5#3#0   balan@2b             1
    I#5#3#1   OBJECTIV           1.1
    I#5#3#1   balan@2c             1
    I#5#3#1   balan@2b            -1
    I#5#3#2   OBJECTIV           1.1
    I#5#3#2   balan@2d             1
    I#5#3#2   balan@2c            -1
    I#5#3#3   OBJECTIV           1.1
    I#5#3#3   balan@2d            -1
    I#6#1#0   init1_16             1
    I#6#1#0   balan@2e             1
    I#6#1#1   OBJECTIV             1
    I#6#1#1   balan@2f             1
    I#6#1#1   balan@2e            -1
    I#6#1#2   OBJECTIV             1
    I#6#1#2   balan@30             1
    I#6#1#2   balan@2f            -1
    I#6#1#3   OBJECTIV             1
    I#6#1#3   balan@30            -1
    I#6#2#0   init1_17             1
    I#6#2#0   balan@31             1
    I#6#2#1   OBJECTIV           1.1
    I#6#2#1   balan@32             1
    I#6#2#1   balan@31            -1
    I#6#2#2   OBJECTIV           1.1
    I#6#2#2   balan@33             1
    I#6#2#2   balan@32            -1
    I#6#2#3   OBJECTIV           1.1
    I#6#2#3   balan@33            -1
    I#6#3#0   init1_18             1
    I#6#3#0   balan@34             1
    I#6#3#1   OBJECTIV           1.1
    I#6#3#1   balan@35             1
    I#6#3#1   balan@34            -1
    I#6#3#2   OBJECTIV           1.1
    I#6#3#2   balan@36             1
    I#6#3#2   balan@35            -1
    I#6#3#3   OBJECTIV           1.1
    I#6#3#3   balan@36            -1
RHS
    RHS       select_1             2
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@7           371
    RHS       balanc@8           573
    RHS       balanc@9           153
    RHS       balanc@a           333
    RHS       balanc@b           776
    RHS       balanc@c           466
    RHS       balanc@d           239
    RHS       balanc@e           425
    RHS       balanc@f           220
    RHS       balan@10           852
    RHS       balan@11            50
    RHS       balan@12           791
    RHS       balan@13           136
    RHS       balan@14           621
    RHS       balan@15           192
    RHS       balan@16             7
    RHS       balan@17            27
    RHS       balan@18           934
    RHS       balan@19          1000
    RHS       balan@1a           237
    RHS       balan@1b           292
    RHS       balan@1f           914
    RHS       balan@20           988
    RHS       balan@21           465
    RHS       balan@22           734
    RHS       balan@23           911
    RHS       balan@24            27
    RHS       balan@25           936
    RHS       balan@26           931
    RHS       balan@27           895
    RHS       balan@28           249
    RHS       balan@29           352
    RHS       balan@2a           188
    RHS       balan@2e           892
    RHS       balan@2f           869
    RHS       balan@30           833
    RHS       balan@31           956
    RHS       balan@32           226
    RHS       balan@33           725
    RHS       valid_1           1322
    RHS       valid_2           1097
    RHS       valid_3           1575
    RHS       valid_4            884
    RHS       valid_5           1693
    RHS       valid_6            949
    RHS       valid_7            968
    RHS       valid_8           1529
    RHS       valid_9           2367
    RHS       valid_10          1672
    RHS       valid_11          2762
    RHS       valid_12           789
    RHS       valid_13          2594
    RHS       valid_14          1907
BOUNDS
 LO BOUND     B#1#1#0              0
 PL BOUND     B#1#1#0 
 LO BOUND     B#1#1#1              0
 PL BOUND     B#1#1#1 
 LO BOUND     B#1#1#2              0
 PL BOUND     B#1#1#2 
 LO BOUND     B#1#1#3              0
 PL BOUND     B#1#1#3 
 LO BOUND     B#1#2#0              0
 PL BOUND     B#1#2#0 
 LO BOUND     B#1#2#1              0
 PL BOUND     B#1#2#1 
 LO BOUND     B#1#2#2              0
 PL BOUND     B#1#2#2 
 LO BOUND     B#1#2#3              0
 PL BOUND     B#1#2#3 
 LO BOUND     B#1#3#0              0
 PL BOUND     B#1#3#0 
 LO BOUND     B#1#3#1              0
 PL BOUND     B#1#3#1 
 LO BOUND     B#1#3#2              0
 PL BOUND     B#1#3#2 
 LO BOUND     B#1#3#3              0
 PL BOUND     B#1#3#3 
 LO BOUND     B#2#1#0              0
 PL BOUND     B#2#1#0 
 LO BOUND     B#2#1#1              0
 PL BOUND     B#2#1#1 
 LO BOUND     B#2#1#2              0
 PL BOUND     B#2#1#2 
 LO BOUND     B#2#1#3              0
 PL BOUND     B#2#1#3 
 LO BOUND     B#2#2#0              0
 PL BOUND     B#2#2#0 
 LO BOUND     B#2#2#1              0
 PL BOUND     B#2#2#1 
 LO BOUND     B#2#2#2              0
 PL BOUND     B#2#2#2 
 LO BOUND     B#2#2#3              0
 PL BOUND     B#2#2#3 
 LO BOUND     B#2#3#0              0
 PL BOUND     B#2#3#0 
 LO BOUND     B#2#3#1              0
 PL BOUND     B#2#3#1 
 LO BOUND     B#2#3#2              0
 PL BOUND     B#2#3#2 
 LO BOUND     B#2#3#3              0
 PL BOUND     B#2#3#3 
 LO BOUND     B#3#1#0              0
 PL BOUND     B#3#1#0 
 LO BOUND     B#3#1#1              0
 PL BOUND     B#3#1#1 
 LO BOUND     B#3#1#2              0
 PL BOUND     B#3#1#2 
 LO BOUND     B#3#1#3              0
 PL BOUND     B#3#1#3 
 LO BOUND     B#3#2#0              0
 PL BOUND     B#3#2#0 
 LO BOUND     B#3#2#1              0
 PL BOUND     B#3#2#1 
 LO BOUND     B#3#2#2              0
 PL BOUND     B#3#2#2 
 LO BOUND     B#3#2#3              0
 PL BOUND     B#3#2#3 
 LO BOUND     B#3#3#0              0
 PL BOUND     B#3#3#0 
 LO BOUND     B#3#3#1              0
 PL BOUND     B#3#3#1 
 LO BOUND     B#3#3#2              0
 PL BOUND     B#3#3#2 
 LO BOUND     B#3#3#3              0
 PL BOUND     B#3#3#3 
 LO BOUND     B#4#1#0              0
 PL BOUND     B#4#1#0 
 LO BOUND     B#4#1#1              0
 PL BOUND     B#4#1#1 
 LO BOUND     B#4#1#2              0
 PL BOUND     B#4#1#2 
 LO BOUND     B#4#1#3              0
 PL BOUND     B#4#1#3 
 LO BOUND     B#4#2#0              0
 PL BOUND     B#4#2#0 
 LO BOUND     B#4#2#1              0
 PL BOUND     B#4#2#1 
 LO BOUND     B#4#2#2              0
 PL BOUND     B#4#2#2 
 LO BOUND     B#4#2#3              0
 PL BOUND     B#4#2#3 
 LO BOUND     B#4#3#0              0
 PL BOUND     B#4#3#0 
 LO BOUND     B#4#3#1              0
 PL BOUND     B#4#3#1 
 LO BOUND     B#4#3#2              0
 PL BOUND     B#4#3#2 
 LO BOUND     B#4#3#3              0
 PL BOUND     B#4#3#3 
 LO BOUND     B#5#1#0              0
 PL BOUND     B#5#1#0 
 LO BOUND     B#5#1#1              0
 PL BOUND     B#5#1#1 
 LO BOUND     B#5#1#2              0
 PL BOUND     B#5#1#2 
 LO BOUND     B#5#1#3              0
 PL BOUND     B#5#1#3 
 LO BOUND     B#5#2#0              0
 PL BOUND     B#5#2#0 
 LO BOUND     B#5#2#1              0
 PL BOUND     B#5#2#1 
 LO BOUND     B#5#2#2              0
 PL BOUND     B#5#2#2 
 LO BOUND     B#5#2#3              0
 PL BOUND     B#5#2#3 
 LO BOUND     B#5#3#0              0
 PL BOUND     B#5#3#0 
 LO BOUND     B#5#3#1              0
 PL BOUND     B#5#3#1 
 LO BOUND     B#5#3#2              0
 PL BOUND     B#5#3#2 
 LO BOUND     B#5#3#3              0
 PL BOUND     B#5#3#3 
 LO BOUND     B#6#1#0              0
 PL BOUND     B#6#1#0 
 LO BOUND     B#6#1#1              0
 PL BOUND     B#6#1#1 
 LO BOUND     B#6#1#2              0
 PL BOUND     B#6#1#2 
 LO BOUND     B#6#1#3              0
 PL BOUND     B#6#1#3 
 LO BOUND     B#6#2#0              0
 PL BOUND     B#6#2#0 
 LO BOUND     B#6#2#1              0
 PL BOUND     B#6#2#1 
 LO BOUND     B#6#2#2              0
 PL BOUND     B#6#2#2 
 LO BOUND     B#6#2#3              0
 PL BOUND     B#6#2#3 
 LO BOUND     B#6#3#0              0
 PL BOUND     B#6#3#0 
 LO BOUND     B#6#3#1              0
 PL BOUND     B#6#3#1 
 LO BOUND     B#6#3#2              0
 PL BOUND     B#6#3#2 
 LO BOUND     B#6#3#3              0
 PL BOUND     B#6#3#3 
 LO BOUND     I#1#1#0              0
 PL BOUND     I#1#1#0 
 LO BOUND     I#1#1#1              0
 PL BOUND     I#1#1#1 
 LO BOUND     I#1#1#2              0
 PL BOUND     I#1#1#2 
 LO BOUND     I#1#1#3              0
 PL BOUND     I#1#1#3 
 LO BOUND     I#1#2#0              0
 PL BOUND     I#1#2#0 
 LO BOUND     I#1#2#1              0
 PL BOUND     I#1#2#1 
 LO BOUND     I#1#2#2              0
 PL BOUND     I#1#2#2 
 LO BOUND     I#1#2#3              0
 PL BOUND     I#1#2#3 
 LO BOUND     I#1#3#0              0
 PL BOUND     I#1#3#0 
 LO BOUND     I#1#3#1              0
 PL BOUND     I#1#3#1 
 LO BOUND     I#1#3#2              0
 PL BOUND     I#1#3#2 
 LO BOUND     I#1#3#3              0
 PL BOUND     I#1#3#3 
 LO BOUND     I#2#1#0              0
 PL BOUND     I#2#1#0 
 LO BOUND     I#2#1#1              0
 PL BOUND     I#2#1#1 
 LO BOUND     I#2#1#2              0
 PL BOUND     I#2#1#2 
 LO BOUND     I#2#1#3              0
 PL BOUND     I#2#1#3 
 LO BOUND     I#2#2#0              0
 PL BOUND     I#2#2#0 
 LO BOUND     I#2#2#1              0
 PL BOUND     I#2#2#1 
 LO BOUND     I#2#2#2              0
 PL BOUND     I#2#2#2 
 LO BOUND     I#2#2#3              0
 PL BOUND     I#2#2#3 
 LO BOUND     I#2#3#0              0
 PL BOUND     I#2#3#0 
 LO BOUND     I#2#3#1              0
 PL BOUND     I#2#3#1 
 LO BOUND     I#2#3#2              0
 PL BOUND     I#2#3#2 
 LO BOUND     I#2#3#3              0
 PL BOUND     I#2#3#3 
 LO BOUND     I#3#1#0              0
 PL BOUND     I#3#1#0 
 LO BOUND     I#3#1#1              0
 PL BOUND     I#3#1#1 
 LO BOUND     I#3#1#2              0
 PL BOUND     I#3#1#2 
 LO BOUND     I#3#1#3              0
 PL BOUND     I#3#1#3 
 LO BOUND     I#3#2#0              0
 PL BOUND     I#3#2#0 
 LO BOUND     I#3#2#1              0
 PL BOUND     I#3#2#1 
 LO BOUND     I#3#2#2              0
 PL BOUND     I#3#2#2 
 LO BOUND     I#3#2#3              0
 PL BOUND     I#3#2#3 
 LO BOUND     I#3#3#0              0
 PL BOUND     I#3#3#0 
 LO BOUND     I#3#3#1              0
 PL BOUND     I#3#3#1 
 LO BOUND     I#3#3#2              0
 PL BOUND     I#3#3#2 
 LO BOUND     I#3#3#3              0
 PL BOUND     I#3#3#3 
 LO BOUND     I#4#1#0              0
 PL BOUND     I#4#1#0 
 LO BOUND     I#4#1#1              0
 PL BOUND     I#4#1#1 
 LO BOUND     I#4#1#2              0
 PL BOUND     I#4#1#2 
 LO BOUND     I#4#1#3              0
 PL BOUND     I#4#1#3 
 LO BOUND     I#4#2#0              0
 PL BOUND     I#4#2#0 
 LO BOUND     I#4#2#1              0
 PL BOUND     I#4#2#1 
 LO BOUND     I#4#2#2              0
 PL BOUND     I#4#2#2 
 LO BOUND     I#4#2#3              0
 PL BOUND     I#4#2#3 
 LO BOUND     I#4#3#0              0
 PL BOUND     I#4#3#0 
 LO BOUND     I#4#3#1              0
 PL BOUND     I#4#3#1 
 LO BOUND     I#4#3#2              0
 PL BOUND     I#4#3#2 
 LO BOUND     I#4#3#3              0
 PL BOUND     I#4#3#3 
 LO BOUND     I#5#1#0              0
 PL BOUND     I#5#1#0 
 LO BOUND     I#5#1#1              0
 PL BOUND     I#5#1#1 
 LO BOUND     I#5#1#2              0
 PL BOUND     I#5#1#2 
 LO BOUND     I#5#1#3              0
 PL BOUND     I#5#1#3 
 LO BOUND     I#5#2#0              0
 PL BOUND     I#5#2#0 
 LO BOUND     I#5#2#1              0
 PL BOUND     I#5#2#1 
 LO BOUND     I#5#2#2              0
 PL BOUND     I#5#2#2 
 LO BOUND     I#5#2#3              0
 PL BOUND     I#5#2#3 
 LO BOUND     I#5#3#0              0
 PL BOUND     I#5#3#0 
 LO BOUND     I#5#3#1              0
 PL BOUND     I#5#3#1 
 LO BOUND     I#5#3#2              0
 PL BOUND     I#5#3#2 
 LO BOUND     I#5#3#3              0
 PL BOUND     I#5#3#3 
 LO BOUND     I#6#1#0              0
 PL BOUND     I#6#1#0 
 LO BOUND     I#6#1#1              0
 PL BOUND     I#6#1#1 
 LO BOUND     I#6#1#2              0
 PL BOUND     I#6#1#2 
 LO BOUND     I#6#1#3              0
 PL BOUND     I#6#1#3 
 LO BOUND     I#6#2#0              0
 PL BOUND     I#6#2#0 
 LO BOUND     I#6#2#1              0
 PL BOUND     I#6#2#1 
 LO BOUND     I#6#2#2              0
 PL BOUND     I#6#2#2 
 LO BOUND     I#6#2#3              0
 PL BOUND     I#6#2#3 
 LO BOUND     I#6#3#0              0
 PL BOUND     I#6#3#0 
 LO BOUND     I#6#3#1              0
 PL BOUND     I#6#3#1 
 LO BOUND     I#6#3#2              0
 PL BOUND     I#6#3#2 
 LO BOUND     I#6#3#3              0
 PL BOUND     I#6#3#3 
 LO BOUND     f#1#1#1              0
 PL BOUND     f#1#1#1 
 LO BOUND     f#1#1#2              0
 PL BOUND     f#1#1#2 
 LO BOUND     f#1#1#3              0
 PL BOUND     f#1#1#3 
 LO BOUND     f#1#2#1              0
 PL BOUND     f#1#2#1 
 LO BOUND     f#1#2#2              0
 PL BOUND     f#1#2#2 
 LO BOUND     f#1#2#3              0
 PL BOUND     f#1#2#3 
 LO BOUND     f#1#3#1              0
 PL BOUND     f#1#3#1 
 LO BOUND     f#1#3#2              0
 PL BOUND     f#1#3#2 
 LO BOUND     f#1#3#3              0
 PL BOUND     f#1#3#3 
 LO BOUND     f#2#1#1              0
 PL BOUND     f#2#1#1 
 LO BOUND     f#2#1#2              0
 PL BOUND     f#2#1#2 
 LO BOUND     f#2#1#3              0
 PL BOUND     f#2#1#3 
 LO BOUND     f#2#2#1              0
 PL BOUND     f#2#2#1 
 LO BOUND     f#2#2#2              0
 PL BOUND     f#2#2#2 
 LO BOUND     f#2#2#3              0
 PL BOUND     f#2#2#3 
 LO BOUND     f#2#3#1              0
 PL BOUND     f#2#3#1 
 LO BOUND     f#2#3#2              0
 PL BOUND     f#2#3#2 
 LO BOUND     f#2#3#3              0
 PL BOUND     f#2#3#3 
 LO BOUND     f#3#1#1              0
 PL BOUND     f#3#1#1 
 LO BOUND     f#3#1#2              0
 PL BOUND     f#3#1#2 
 LO BOUND     f#3#1#3              0
 PL BOUND     f#3#1#3 
 LO BOUND     f#3#2#1              0
 PL BOUND     f#3#2#1 
 LO BOUND     f#3#2#2              0
 PL BOUND     f#3#2#2 
 LO BOUND     f#3#2#3              0
 PL BOUND     f#3#2#3 
 LO BOUND     f#3#3#1              0
 PL BOUND     f#3#3#1 
 LO BOUND     f#3#3#2              0
 PL BOUND     f#3#3#2 
 LO BOUND     f#3#3#3              0
 PL BOUND     f#3#3#3 
 LO BOUND     f#4#1#1              0
 PL BOUND     f#4#1#1 
 LO BOUND     f#4#1#2              0
 PL BOUND     f#4#1#2 
 LO BOUND     f#4#1#3              0
 PL BOUND     f#4#1#3 
 LO BOUND     f#4#2#1              0
 PL BOUND     f#4#2#1 
 LO BOUND     f#4#2#2              0
 PL BOUND     f#4#2#2 
 LO BOUND     f#4#2#3              0
 PL BOUND     f#4#2#3 
 LO BOUND     f#4#3#1              0
 PL BOUND     f#4#3#1 
 LO BOUND     f#4#3#2              0
 PL BOUND     f#4#3#2 
 LO BOUND     f#4#3#3              0
 PL BOUND     f#4#3#3 
 LO BOUND     f#5#1#1              0
 PL BOUND     f#5#1#1 
 LO BOUND     f#5#1#2              0
 PL BOUND     f#5#1#2 
 LO BOUND     f#5#1#3              0
 PL BOUND     f#5#1#3 
 LO BOUND     f#5#2#1              0
 PL BOUND     f#5#2#1 
 LO BOUND     f#5#2#2              0
 PL BOUND     f#5#2#2 
 LO BOUND     f#5#2#3              0
 PL BOUND     f#5#2#3 
 LO BOUND     f#5#3#1              0
 PL BOUND     f#5#3#1 
 LO BOUND     f#5#3#2              0
 PL BOUND     f#5#3#2 
 LO BOUND     f#5#3#3              0
 PL BOUND     f#5#3#3 
 LO BOUND     f#6#1#1              0
 PL BOUND     f#6#1#1 
 LO BOUND     f#6#1#2              0
 PL BOUND     f#6#1#2 
 LO BOUND     f#6#1#3              0
 PL BOUND     f#6#1#3 
 LO BOUND     f#6#2#1              0
 PL BOUND     f#6#2#1 
 LO BOUND     f#6#2#2              0
 PL BOUND     f#6#2#2 
 LO BOUND     f#6#2#3              0
 PL BOUND     f#6#2#3 
 LO BOUND     f#6#3#1              0
 PL BOUND     f#6#3#1 
 LO BOUND     f#6#3#2              0
 PL BOUND     f#6#3#2 
 LO BOUND     f#6#3#3              0
 PL BOUND     f#6#3#3 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#6#1              0
 PL BOUND     y#1#6#1 
 LO BOUND     y#1#6#2              0
 PL BOUND     y#1#6#2 
 LO BOUND     y#1#6#3              0
 PL BOUND     y#1#6#3 
 LO BOUND     y#1#7#1              0
 PL BOUND     y#1#7#1 
 LO BOUND     y#1#7#2              0
 PL BOUND     y#1#7#2 
 LO BOUND     y#1#7#3              0
 PL BOUND     y#1#7#3 
 LO BOUND     y#1#8#1              0
 PL BOUND     y#1#8#1 
 LO BOUND     y#1#8#2              0
 PL BOUND     y#1#8#2 
 LO BOUND     y#1#8#3              0
 PL BOUND     y#1#8#3 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#6#1              0
 PL BOUND     y#2#6#1 
 LO BOUND     y#2#6#2              0
 PL BOUND     y#2#6#2 
 LO BOUND     y#2#6#3              0
 PL BOUND     y#2#6#3 
 LO BOUND     y#2#7#1              0
 PL BOUND     y#2#7#1 
 LO BOUND     y#2#7#2              0
 PL BOUND     y#2#7#2 
 LO BOUND     y#2#7#3              0
 PL BOUND     y#2#7#3 
 LO BOUND     y#2#8#1              0
 PL BOUND     y#2#8#1 
 LO BOUND     y#2#8#2              0
 PL BOUND     y#2#8#2 
 LO BOUND     y#2#8#3              0
 PL BOUND     y#2#8#3 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#6#1              0
 PL BOUND     y#3#6#1 
 LO BOUND     y#3#6#2              0
 PL BOUND     y#3#6#2 
 LO BOUND     y#3#6#3              0
 PL BOUND     y#3#6#3 
 LO BOUND     y#3#7#1              0
 PL BOUND     y#3#7#1 
 LO BOUND     y#3#7#2              0
 PL BOUND     y#3#7#2 
 LO BOUND     y#3#7#3              0
 PL BOUND     y#3#7#3 
 LO BOUND     y#3#8#1              0
 PL BOUND     y#3#8#1 
 LO BOUND     y#3#8#2              0
 PL BOUND     y#3#8#2 
 LO BOUND     y#3#8#3              0
 PL BOUND     y#3#8#3 
 LO BOUND     y#4#1#1              0
 PL BOUND     y#4#1#1 
 LO BOUND     y#4#1#2              0
 PL BOUND     y#4#1#2 
 LO BOUND     y#4#1#3              0
 PL BOUND     y#4#1#3 
 LO BOUND     y#4#2#1              0
 PL BOUND     y#4#2#1 
 LO BOUND     y#4#2#2              0
 PL BOUND     y#4#2#2 
 LO BOUND     y#4#2#3              0
 PL BOUND     y#4#2#3 
 LO BOUND     y#4#3#1              0
 PL BOUND     y#4#3#1 
 LO BOUND     y#4#3#2              0
 PL BOUND     y#4#3#2 
 LO BOUND     y#4#3#3              0
 PL BOUND     y#4#3#3 
 LO BOUND     y#4#4#1              0
 PL BOUND     y#4#4#1 
 LO BOUND     y#4#4#2              0
 PL BOUND     y#4#4#2 
 LO BOUND     y#4#4#3              0
 PL BOUND     y#4#4#3 
 LO BOUND     y#4#5#1              0
 PL BOUND     y#4#5#1 
 LO BOUND     y#4#5#2              0
 PL BOUND     y#4#5#2 
 LO BOUND     y#4#5#3              0
 PL BOUND     y#4#5#3 
 LO BOUND     y#4#6#1              0
 PL BOUND     y#4#6#1 
 LO BOUND     y#4#6#2              0
 PL BOUND     y#4#6#2 
 LO BOUND     y#4#6#3              0
 PL BOUND     y#4#6#3 
 LO BOUND     y#4#7#1              0
 PL BOUND     y#4#7#1 
 LO BOUND     y#4#7#2              0
 PL BOUND     y#4#7#2 
 LO BOUND     y#4#7#3              0
 PL BOUND     y#4#7#3 
 LO BOUND     y#4#8#1              0
 PL BOUND     y#4#8#1 
 LO BOUND     y#4#8#2              0
 PL BOUND     y#4#8#2 
 LO BOUND     y#4#8#3              0
 PL BOUND     y#4#8#3 
 LO BOUND     y#5#1#1              0
 PL BOUND     y#5#1#1 
 LO BOUND     y#5#1#2              0
 PL BOUND     y#5#1#2 
 LO BOUND     y#5#1#3              0
 PL BOUND     y#5#1#3 
 LO BOUND     y#5#2#1              0
 PL BOUND     y#5#2#1 
 LO BOUND     y#5#2#2              0
 PL BOUND     y#5#2#2 
 LO BOUND     y#5#2#3              0
 PL BOUND     y#5#2#3 
 LO BOUND     y#5#3#1              0
 PL BOUND     y#5#3#1 
 LO BOUND     y#5#3#2              0
 PL BOUND     y#5#3#2 
 LO BOUND     y#5#3#3              0
 PL BOUND     y#5#3#3 
 LO BOUND     y#5#4#1              0
 PL BOUND     y#5#4#1 
 LO BOUND     y#5#4#2              0
 PL BOUND     y#5#4#2 
 LO BOUND     y#5#4#3              0
 PL BOUND     y#5#4#3 
 LO BOUND     y#5#5#1              0
 PL BOUND     y#5#5#1 
 LO BOUND     y#5#5#2              0
 PL BOUND     y#5#5#2 
 LO BOUND     y#5#5#3              0
 PL BOUND     y#5#5#3 
 LO BOUND     y#5#6#1              0
 PL BOUND     y#5#6#1 
 LO BOUND     y#5#6#2              0
 PL BOUND     y#5#6#2 
 LO BOUND     y#5#6#3              0
 PL BOUND     y#5#6#3 
 LO BOUND     y#5#7#1              0
 PL BOUND     y#5#7#1 
 LO BOUND     y#5#7#2              0
 PL BOUND     y#5#7#2 
 LO BOUND     y#5#7#3              0
 PL BOUND     y#5#7#3 
 LO BOUND     y#5#8#1              0
 PL BOUND     y#5#8#1 
 LO BOUND     y#5#8#2              0
 PL BOUND     y#5#8#2 
 LO BOUND     y#5#8#3              0
 PL BOUND     y#5#8#3 
 LO BOUND     y#6#1#1              0
 PL BOUND     y#6#1#1 
 LO BOUND     y#6#1#2              0
 PL BOUND     y#6#1#2 
 LO BOUND     y#6#1#3              0
 PL BOUND     y#6#1#3 
 LO BOUND     y#6#2#1              0
 PL BOUND     y#6#2#1 
 LO BOUND     y#6#2#2              0
 PL BOUND     y#6#2#2 
 LO BOUND     y#6#2#3              0
 PL BOUND     y#6#2#3 
 LO BOUND     y#6#3#1              0
 PL BOUND     y#6#3#1 
 LO BOUND     y#6#3#2              0
 PL BOUND     y#6#3#2 
 LO BOUND     y#6#3#3              0
 PL BOUND     y#6#3#3 
 LO BOUND     y#6#4#1              0
 PL BOUND     y#6#4#1 
 LO BOUND     y#6#4#2              0
 PL BOUND     y#6#4#2 
 LO BOUND     y#6#4#3              0
 PL BOUND     y#6#4#3 
 LO BOUND     y#6#5#1              0
 PL BOUND     y#6#5#1 
 LO BOUND     y#6#5#2              0
 PL BOUND     y#6#5#2 
 LO BOUND     y#6#5#3              0
 PL BOUND     y#6#5#3 
 LO BOUND     y#6#6#1              0
 PL BOUND     y#6#6#1 
 LO BOUND     y#6#6#2              0
 PL BOUND     y#6#6#2 
 LO BOUND     y#6#6#3              0
 PL BOUND     y#6#6#3 
 LO BOUND     y#6#7#1              0
 PL BOUND     y#6#7#1 
 LO BOUND     y#6#7#2              0
 PL BOUND     y#6#7#2 
 LO BOUND     y#6#7#3              0
 PL BOUND     y#6#7#3 
 LO BOUND     y#6#8#1              0
 PL BOUND     y#6#8#1 
 LO BOUND     y#6#8#2              0
 PL BOUND     y#6#8#2 
 LO BOUND     y#6#8#3              0
 PL BOUND     y#6#8#3 
 LO BOUND     p#1                  0
 UP BOUND     p#1                  1
 LO BOUND     p#2                  0
 UP BOUND     p#2                  1
 LO BOUND     p#3                  0
 UP BOUND     p#3                  1
 LO BOUND     p#4                  0
 UP BOUND     p#4                  1
 LO BOUND     p#5                  0
 UP BOUND     p#5                  1
 LO BOUND     p#6                  0
 UP BOUND     p#6                  1
 LO BOUND     p#7                  0
 UP BOUND     p#7                  1
 LO BOUND     p#8                  0
 UP BOUND     p#8                  1
ENDATA
